### ISSUE TITLE
API aggregation docs don't work on systems that aren't running Kubernetes

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#1002]
On systems that are not running Kubernetes natively (i.e. when Kubernetes is running inside Minikube or a cloud), the following commands won't work:

```console
cp /var/run/kubernetes/${SERVINGCA_CERT} .
cp /var/run/kubernetes/${SERVINGCA_KEY} .
```

This is because the cert and key won't be installed locally.

The [script](https://github.com/kubernetes-incubator/service-catalog/blob/master/contrib/svc-cat-apiserver-aggregation-tls-setup.sh) appears to not rely on Kubernetes infrastructure, but it's unclear to me whether that's a complete replacement for all the other instructions.

**Comment by MHBauer** [comment]
That section is in the 'reuse the existing infra' flow, and is an example of where the certs are on an instance. There is no standard place for them and they would have to be explicitly provided by a cloud provider to be accessible.

**Comment by arschles** [comment]
Got it, I see that the script is mentioned below, which appears to be the preferred way to set up when you are not reusing the infra flow. I'll close this issue
