### ISSUE TITLE
The Helm Install docs in the API Aggregation Setup don't work on a Mac

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#1004]
The `helm install` command in [this section](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/api-aggregation-setup.md#install-the-service-catalog-chart-with-helm) don't work on a mac. They produce the following error output:

```console
admins-MacBook-Pro:service-catalog aaschles$ helm install charts/catalog     --name ${HELM_NAME} --namespace ${SVCCAT_NAMESPACE}     --set apiserver.auth.enabled=true         --set useAggregator=true         --set apiserver.tls.ca=$(base64 --wrap 0 ${SC_SERVING_CA})         --set apiserver.tls.cert=$(base64 --wrap 0 ${SC_SERVING_CERT})         --set apiserver.tls.key=$(base64 --wrap 0 ${SC_SERVING_KEY})
base64: unrecognized option `--wrap'
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
base64: unrecognized option `--wrap'
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
base64: unrecognized option `--wrap'
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
Error: a release named "catalog" already exists.
Please run: helm ls --all "catalog"; helm del --help
```

**Comment by MHBauer** [comment]
gnu base64 (linux) vs bsd base64 (mac). 

We can say, run it on linux, or run it on gnu base64, but since it's a user run thing, we probably have to figure out how to use bsd base64 and tell the user what they might need to run.

**Comment by arschles** [comment]
@MHBauer see how I fixed this in #1005

**Comment by arschles** [comment]
@MHBauer update: I closed #1005 without merge. We can't say that this must be run only on linux.

I can think of a few options:

1. Enable people to run the `helm` command in a container
2. Enable people to run the `base64` command in a container
3. Do the base64 encoding inside the helm chart (I did this in #1005)

**Comment by pmorie** [comment]
Use the stringData field in secret and you won't have to b64 encode anything

**Comment by arschles** [comment]
@pmorie the files have newlines in them - do you know another good way to pass them in on the helm CLI?
