### ISSUE TITLE
Design and implement opaque bearer token support for broker auth

### ISSUE THREAD

**Issue by nilebox** [kubernetes-incubator/service-catalog#1043]
Inspired by the discussion in https://github.com/kubernetes-incubator/service-catalog/issues/990, but solving the problem in a more generic way proposed in https://github.com/kubernetes-incubator/service-catalog/issues/990#issuecomment-315577090

The proposal (considering PR https://github.com/kubernetes-incubator/service-catalog/pull/1037 as prerequisite):
1. Define the "`opaqueBearerToken`" constant for `SecretType` field in `BrokerAuthInfo` object as an identifier for opaque bearer token.
2. Introduce the `OpaqueBearerTokenAuth` implementation of the `AuthInterface` described in https://github.com/kubernetes-incubator/service-catalog/pull/1037 with the following details:
    - Service Catalog examines the `SecretType` field of `BrokerAuthInfo` object, finds the "opaqueBearerToken" values, which maps to the corresponding `OpaqueBearerTokenAuth` implementation of the `AuthInterface` responsible for this type of secret
    - Service Catalog fetches the Secret specified in the Broker spec, and extract the token stored in the "`token`" key of the secret (by convention)
    - Service Catalog adds an `Authorization` header to every broker request as `Authorization: Bearer $TOKEN`
3. The token generation and maintenance is out of scope of Service Catalog. Possible use cases:
    - User manually fetches the token and creates a secret containing it
      - works only for long-lived tokens
    - There is a separate "Token Maintainer" process watching on all brokers and periodically creating/updating the secrets with new tokens to mitigate their expiration (short-lived tokens could be valid only for 10 minutes, for example)
      -  Token Maintainer process maintains secrets only for the brokers with `SecretType` set to "opaqueBearerToken"

**Comment by nilebox** [comment]
@liggitt what do you think about this problem?

> not clear how Token Maintainer process knows which of the brokers use opaque bearer tokens for auth, to generate tokens only for them, if initially there is no secret instance (containing the type field).
>  - possibly duplicate the SecretType constant in the BrokerSpec?

**Comment by liggitt** [comment]
on the consumption side, I see a few options:

* duck type the secret by looking at the data fields... if it has a "token" field, use it as a bearer token (could do the same for "username" and "password" fields for basic auth, etc)
* recognize specific types of secrets (based on type field in the secret object) and determine which fields contain the bearer token. the type field does not have to be a constant in the core/v1 api... you can have a type of `catalog.k8s.io/custom-type`, etc
* configure the broker spec to point to a secret namespace/name, a specific key in the secret, and what to do with that key (e.g. use it as a bearer token).

the last would probably fit best with a generator or maintainer process, would let you point to any type of secret with a bearer token stored in any data key

**Comment by nilebox** [comment]
> recognize specific types of secrets (based on type field in the secret object) and determine which fields contain the bearer token. the type field does not have to be a constant in the core/v1 api... you can have a type of catalog.k8s.io/custom-type, etc

I am fine with this solution for the consuming side (actually it is mentioned in the `1.` item, please check), and I see two options there - just use already predefined generic "token" constant, or define a new one

> configure the broker spec to point to a secret namespace/name, a specific key in the secret, and what to do with that key (e.g. use it as a bearer token).
the last would probably fit best with a generator or maintainer process, would let you point to any type of secret with a bearer token stored in any data key

@liggitt yeah, I am also leaning towards this option, but it means duplication with the approach for consumer mentioned above. Would you suggest to ignore the type field in the secret object completely in this case?

**Comment by nilebox** [comment]
> a specific key in the secret, and what to do with that key (e.g. use it as a bearer token).

I don't like this approach because it limits the number of keys to one. It wouldn't work for basic auth with `username` and `password` (2 keys), for example.

**Comment by liggitt** [comment]
> I don't like this approach because it limits the number of keys to one. It wouldn't work for basic auth with username and password (2 keys), for example.

Obviously if the use was basic auth, you'd need two keys configured

For something like x509, you could have cert and key

**Comment by nilebox** [comment]
@liggitt thanks, updated the proposal, the PR with detailed proposal text is on the way.

**Comment by nilebox** [comment]
Implemented and merged: https://github.com/kubernetes-incubator/service-catalog/pull/1053
