### ISSUE TITLE
Document our secret update policy

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#1046]
I'm not sure we have an issue directly related to this, although we do hint at it in others, but this issue is specifically for our decision yesterday around how to deal with updates to secrets that are used as input into svc-cat process - e.g. parameters.

There are plans in kube 1.8(?) to add support for watching selective secrets so that we will be notified when one of them is updated, and then we can choose whether to take an action or not.  Until then we agreed to add documentation explaining that the svc-cat (as of now) will not monitor secrets for updates and so if a svc-cat resource references a secret and the user wants that resource to be "refreshed" (whatever that means) they will need to take some manual action to "poke" that resource to cause the reconciliation semantics to take effect. For example, one method we might recommend is to create a new secret and update the resource's secret ref to point to the new one (in essence doing a rename on the secret).

PR needed.

**Comment by pmorie** [comment]
I think the takeaway here is we need to have doc saying what happens to the secrets that hold binding credentials - accurate?

**Comment by duglin** [comment]
Yup - "PR needed"  - in particular a doc PR.

**Comment by pmorie** [comment]
I think I misread it - it sounds like this is to document that we will not watch secrets for now and you need to change the spec of a instance to update parameters?

**Comment by duglin** [comment]
yup - the user will need to do some kind of explicit 'poke' on the instance when the values in the secret changes since we won't detect those secret changes as of now.
