### ISSUE TITLE
Checksums for Instance resources

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#1065]
In the design meeting today (7/26/2017), we discussed how to prevent duplicate requests related to an `Instance` when it is changed (the discussion linked to https://github.com/kubernetes-incubator/service-catalog/issues/1062#issuecomment-317619465).

This issue applies specifically to the instance update operation. Since we do not support instance update, we have no need for checksums to determine whether we should execute the update operation, but when we do implement update, we will need to add at least one.

The possible checksums that were discussed are:

- Checksum of the spec (similar to checksums we already have)
- Checksum of the parameters and/or the contents of a parameter secret

Ref #1062
Ref #1058

**Comment by arschles** [comment]
cc/ @pmorie @nilebox

**Comment by MHBauer** [comment]
closed by #1289
