### ISSUE TITLE
Controller unit test bullet-proofing

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1077]
There are several gaps exhibited by different unit tests in the controller that we should work to close to ensure code quality is high before beta.  Based on discussion with @MHBauer I think we need to ensure that all unit tests for the controller do the following:

- Have a written description of what the test proves
- Make assertions about all client actions taken for:
    - OSB client
    - service-catalog client
    - k8s client
- Test that expected events are created
- Test that objects under test (broker, instance, etc) are in correct state at the API server

By my rigorous analysis, there are 54 unit tests currently for the controller:

```
$ grep -cr 'func Test' pkg/controller/controller_*_test.go
pkg/controller/controller_binding_test.go:17
pkg/controller/controller_broker_test.go:10
pkg/controller/controller_instance_test.go:27
```

I suggest that we split up the work of bullet-proofing the tests.  Perhaps a few people can each take a single file to improve.  The `controller_instance_test` file has quite a few tests, so it might make sense to do that one in two PRs that change ~14 tests each.

I'm adding this to the 0.1.0 milestone because I don't feel like it should be controversial, but the sooner we finish this, the better.  I think it goes without saying that future unit tests should have to meet the bar established here.

**Comment by jpeeler** [comment]
If people are comfortable with allowing me a week grace period to start (off next week), I'll take responsibility for getting controller_binding_test.go in shape.

**Comment by jboyd01** [comment]
I'll take a swipe with the broker tests

**Comment by jpeeler** [comment]
This is done now (Ville even got rid of the remaining updateInstanceCondition/updateBindingCondition in the controller in 33cb34575a461887ad270a13a08ed712d3023949).
