### ISSUE TITLE
Finalize naming of resources in servicecatalog API group

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1080]
This issue is to finalize the names of API resources before moving the service-catalog API to beta.

### Requirements:

- We should not have any name collisions with core resources
- When naming resources, we should run the thought experiment of "would we like it if everyone followed our naming patterns?" - we are likely to establish precedent for how other extension APIs name their resources
- We should only do a single rename if at all possible - iterating on names over multiple releases isn't good for users

### Suggested process:

1. Find a consensus within the group
2. Ensure that our names pass API review
3. Make a proposal document for v1beta1 API that we can link users to
4. Communicate proactively about the breaking API changes and give users a specific release date when the changes will be released
5. Make the code change PR

#### Note

We have previously had a number of issues for different objectives or pieces of the rename, and a discussion wherein there was a miscommunication about what we were 
discussing.  I've closed the previous issues we've had for this topic so that we can get a fresh start.  Previous issues were:

- #837
- #1008
- #1031
- #1033
- #1060
- #1054

### Proposed resources

Based on our prior discussions in the group, the set of resources that will be the 'nucleus' of the catalog will be as follows.  Note: names used here are purely to identify the resources and not proposed names:

- Broker
- ServiceClass
- ServicePlan
- Instance
- Binding (we have discussed calling this InstanceCredential, but no one seemed to be especially happy with the name)

Based on our current knowledge, the above should be a complete accounting of the resources in the v1beta1 API, but there may be additional resources pending the outcome of #802.

Note: The binding resource should _only_ represent the OSB facet of binding, see #994.

#### Extension resources

There are a number of different extension resources that we know there is interest in building in the community:

- A resource that manages a PodPreset based on the lifecycle of our binding resource
- A resource that does a `VCAP_SERVICES`-style injection
- A resource that creates Istio rules
- A 'flex'-style binding that provides an easy on-ramp for people to extend the catalog

These should be created initially in (a) **different API group(s)** from the nucleus of the service-catalog.  It might be convenient for some of these resources with wide appeal to be created in this repository, and more appropriate for others to be created outside of this repo.

### Proposed resource names

I propose the following resource names:

- `ServiceBroker`
- `ServiceClass`
- `ServicePlan`
- `ServiceInstance`
- `ServiceInstanceCredential`

#### Previous discussion: naming of binding resource

See #1033

#### Previous discussion: separating service classes and plans

See #454

#### Previous discussion: `ServiceCatalog` prefix

We had previously discussed prefixing every resource with `ServiceCatalog`.  I think there are a number of cons to this:

- Extremely lengthy names to type in a CLI
- No precedent for encoding name of API group in every resource name in that group
- Not a good precedent to establish: if all other extension APIs follow this pattern, the entire ecosystem will be filled with extremely lengthy names
- Yields difficult to understand resource names

Since this is necessarily an issue to resolve and implement before beta, I'm adding it to the 0.1.0 milestone.

**Comment by MHBauer** [comment]
No renames before we get to:
`Ensure that our names pass API review`

We already had consensus previously for the name move to #1054. I'm not making any more decisions on moves without clear core consent that the names we pick are reasonably final ones that are ours permanently. If `Binding` collides for now, so be it.

**Comment by pmorie** [comment]
> No renames before ...

Yeah, I agree, was that not clear from the rest of the issue?

**Comment by vaikas-google** [comment]
Isn't there already a core resource called Binding?
https://kubernetes.io/docs/resources-reference/v1.7/#binding-v1-core

This seems to violate the first Requirement.

**Comment by duglin** [comment]
Just for reference, the proposal in this issue is (I believe) exactly what was originally proposed previously: https://github.com/kubernetes-incubator/service-catalog/issues/1008#issuecomment-314952476  but then during the design review sessions we migrated from "Service..." to "ServiceCatalog...". If my memory is correct, I think the migration happened due to concern about "Service" not being unique enough and the fear of potential future conflicts.

From checking the issues/threads on this, I don't believe there's a technical issues with either name, I think it comes down to more of a stylistic preference and UX (meaning one will ask people to type more chars).

As previously stated during the other design sessions, I'm ok with either.

**Comment by pmorie** [comment]
We have a statement from one of the kubernetes owners (@smarterclayton) [here](https://github.com/kubernetes-incubator/service-catalog/pull/1054#issuecomment-317460675) indicating that we can claim `Service{Broker,Class,Plan,Instance,Binding}`.  I think these names are far more concise and easy to understand.

Additionally, we are establishing precedent for how extensions name their resources.  I think it is hostile to users and detrimental to the ecosystem if we establish a precedent of having lengthy repeated prefixes on API resources.  It's also unnecessary to have these lengthy prefixes, because:

- The API resources as sent to the API server must include the fully qualified name (ie, group, version, and kind)
- The kubectl tooling supports passing fully qualified or partially qualified (group + kind) names when necessary to disambiguate between naming collisions between kinds in different API groups

**Comment by vaikas-google** [comment]
As per discussions offline, assigning to @thockin and @bgrant0607 for getting an OK for the proposed names:
Proposed resource names:
ServiceBroker
ServiceClass
ServicePlan
ServiceInstance
ServiceInstanceCredential

**Comment by thockin** [comment]
I think it's fine.  I don't have plans to use ServiceClass for anything, and this seems OK to me.

**Comment by vaikas-google** [comment]
During today's SIG meeting, the vote was to proceed with Service* instead of ServiceCatalog* names.

**Comment by bgrant0607** [comment]
I agree ServiceCatalog* would be verbose, and likely redundant with the API group name.

Kinds aren't required to be unique across API groups, though it may make some uses less convenient since disambiguation would be required.

While we don't have ServiceClass today, I could imagine adding that in the future, and we may generally be using "Class" in a different sense, such as with StorageClass, ResourceClass, etc. Have we considered a different term other than "Class"?

"Service" is a pretty generic and overloaded term, in general, but I understand why you prefer it. There's a chance we might move away from this term in K8s.

**Comment by bgrant0607** [comment]
ServiceProvider?

**Comment by vaikas-google** [comment]
Just to make sure I understand, using Service* resource names proposed as above are fine. The one concern is ServiceClass? Unless there's a really strong reason to not use that name, I'd like to use that. Given how much time it already has taken to get the consensus, I'd rather not open up the floor for further discussion. So, Is it ok to use ServiceClass or not?

**Comment by duglin** [comment]
that was my assumption - use ServiceClass

**Comment by thockin** [comment]
I don't object

**Comment by bgrant0607** [comment]
The sense in which we plan to use the pattern of FooClass is to register extensions and their options, similar to StorageClass, but with parameter descriptions, types (e.g., integer vs string), constraints (e.g., range or regexp) for validation, and default values.

I guess this isn't that different, so I'm ok with ServiceClass.

**Comment by thockin** [comment]
Also, if we decompose or expand on Service, it will likely not be
ServiceClass, but GatewayClass or something.  We need a different word for
"traffic gets into a Service".  I'm OK with you claiming this one.
