### ISSUE TITLE
Remove TPR storage backend after Custom Resource Definitions are widely supported

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#1089]
Since TPRs are deprecated and will soon disappear, we are implementing a Custom Resource Definition (CRD) storage backend (see #987). At some point after Kubernetes 1.8 is released, we'll need to remove the TPR storage backend. This will likely be necessary when we rebase onto a `k8s.io/client-go` version that no longer has TPR support in its API.

cc/ @nilebox @mengqiy

**Comment by MHBauer** [comment]
TPR storage is gone as of #1322.
