### ISSUE TITLE
reconcileBroker() in controller_broker does not properly check finalizers

### ISSUE THREAD

**Issue by jboyd01** [kubernetes-incubator/service-catalog#1093]
I was doing code review and unit test bullet proofing for https://github.com/kubernetes-incubator/service-catalog/issues/1077 and realized a descrepancy  between the code and comments.  

This code should be checking if the Service Cat finalizer is at the head of the list of finalizers prior to deleting service classes.  It's only checking if Service Cat is one of any of the finalizers.

	if finalizers := sets.NewString(broker.Finalizers...); finalizers.Has(v1alpha1.FinalizerServiceCatalog) {
		glog.V(4).Infof("Finalizing Broker %v", broker.Name)

**Comment by jboyd01** [comment]
maybe this isn't an issue...  Derek's finalizer rework in https://github.com/kubernetes-incubator/service-catalog/pull/894 in part says "Updated the code to use sets for handling finalizers (**ordering is not required**)".

**Comment by pmorie** [comment]
@jboyd01 - we need to ensure that the comment is up to date.  Will you submit a PR to make the comment more accurate?

**Comment by pmorie** [comment]
@jboyd01 there are probably equivalent comments for instances and bindings as well.

**Comment by jboyd01** [comment]
@pmorie yes, will follow up with PR to update comments.

**Comment by pmorie** [comment]
@jboyd01 sounds like this issue can be closed, agree?

**Comment by pmorie** [comment]
@jboyd01 sounds like this issue can be closed, agree?
