### ISSUE TITLE
Make "plan" optional when there is only one plan to choose from

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#1111]
Per the discussion in #1010 and our design meeting on Aug 7th, we agreed that:
- ServiceInstance.Plan should be made optional, and when "plan" is not specified then:
- If there is only one plan for the specified ServiceClass then we'll default to that plan
- If there is more than one plan for the specified ServiceClass then we'll reject the request to create the new ServiceInstance 

Related to this we should:
- change the docs for UPS in the walkthru to remove the use of "plan" just to make a nicer U

Closes #1010

**Comment by pmorie** [comment]
This will need to be implemented as an admission controller.

**Comment by pmorie** [comment]
@duglin @vaikas-google do you have someone in mind to implement this?

**Comment by pmorie** [comment]
@vaikas-google tells me he wants this one.
