### ISSUE TITLE
How to determine the SVC_CAT_API_SERVER_IP is not documented in walkthrough doc.

### ISSUE THREAD

**Issue by lzbj** [kubernetes-incubator/service-catalog#1119]
In the doc https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md, step 5--Setting up a New kubectl Context, how to get the SVC_CAT_API_SERVER_IP is not documented, I think we should increase the kubectrl commands here to help new developers.

**Comment by MHBauer** [comment]
In my experience people tend to blindly copy and paste examples into their terminal. I'm not sure there is anything we can add that would definitively work there. Do you have a specific command to suggest for getting the Node IP?

**Comment by jpeeler** [comment]
Something like `kubectl get services -n catalog -o 'jsonpath={$.items[].spec.clusterIP}'` perhaps? There might be a better way, but I think I used that command in the past.

**Comment by MHBauer** [comment]
Is the clusterIP what we want? Is that pingable externally?

**Comment by xingzhou** [comment]
I think not the clusterIP, I also tried the example locally yesterday, but using 127.0.0.1 to get it work

**Comment by lzbj** [comment]
@xingzhou , that's perhaps we need to add in the doc here.

**Comment by MHBauer** [comment]
@jpeeler The doc says `Regardless of how you do it, do not use the Cluster IP of the Service.`. Do we need to update that?

**Comment by MHBauer** [comment]
We can clear up the `Notes on Getting the IP Address` section, but I can't think of a command that will surely work.

**Comment by jpeeler** [comment]
@MHBauer no, I wasn't thinking in a production context really.

**Comment by jpeeler** [comment]
Our setup of currently utilizing a NodePort means that the API server should be accessible at (any) NodeIP:NodePort combination. Access the ip/port combo by choosing one node IP from "kubectl get nodes" and using the node port as shown in the service output of "kubectl get svc -n catalog -o yaml".

My networking fu is weak, so I'd like to be checked on this. If it's correct though, could be a good document addition.

**Comment by arschles** [comment]
We now only officially support installation on Kubernetes clusters with version 1.7 and above. The [install process](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/install-1.7.md) for this no longer requires you to get `SVC_CAT_API_SERVER_IP`, so I am closing this.
