### ISSUE TITLE
Cannot connect to service-catalog api server (AWS).

### ISSUE THREAD

**Issue by kapekto1** [kubernetes-incubator/service-catalog#1120]
Hello,
I have deployed service catalog on minikube (1.6) and I have it working.
When I tried to deploy it on a kubernetes (AWS) I cannot connect to the catalog API server:

```
> kubectl --context=service-catalog get brokers
Unable to connect to the server: net/http: TLS handshake timeout
```

catalog-catalog-apiserver-3054042905-t5h73 pod resides on node IP:10.200.1.157 and here is my kubeconfig:

```
<CUT>
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.200.1.157:30443
  name: service-catalog
<CUT>

> kc describe svc catalog-catalog-apiserver -n catalog
Name:			catalog-catalog-apiserver
Namespace:		catalog
Labels:			app=catalog-catalog-apiserver
			chart=catalog-0.0.1
			heritage=Tiller
			release=catalog
Annotations:		<none>
Selector:		app=catalog-catalog-apiserver
Type:			NodePort
IP:			10.3.0.60
Port:			secure	443/TCP
NodePort:		secure	30443/TCP
Endpoints:		10.2.104.92:8443
Session Affinity:	None
Events:			<none>

```
I assume that I shoud connect to 10.200.1.157:30433 to the catalog API server - is this correct?
Of course I have vpn tunnel set properly and nmap shows that 10.200.1.157:30433 is open.
Any hints?

**Comment by MHBauer** [comment]
`10.200.1.157:30433` looks right to me from what you have shown.

I am not familiar AWS. Does AWS have a firewall or firewall rules to adjust? Someone wrote up some tips for GCP in #1040. Not sure if AWS does something similar.

**Comment by kapekto1** [comment]
It works when I use LoadBalancer entry in chart files, I have even managed to have it worked with ingress controller. Actually, it solved my problem, however, from my understanding it should also work as I described... Anyway, I'm closing this ticket.
