### ISSUE TITLE
PROPOSAL: Use FieldSelectors to filter ServicePlans

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#1124]
# Use FieldSelectors to filter ServicePlans

## Prerequisite

 - ServicePlan must be a separate object from ServiceClass. See #454 for split proposal. 
 - ServicePlan *MUST* have both `Free` field and a ServicePlan Reference field.

## Abstract

The drive behind #454 is we want to be able to know how many plans are
free or non-free, and then be able to specifically look at only the plans
that are free or non-free.

## Motivation

As a client we have to look at all of the ServicePlans to determine
how many are free. We then have to look at each plan individually. We
want to move this processing to the server and provide a client
interface to select only Free plans or NonFree plans of a specific
serviceclass.

This moves all processing to the server side and results in responses
to queries that are exact. Use existing API Machinery and implement the field selector logic to enable selection on extracted ServicePlan object.

## Proposed Design

Create  ServicePlans as in 454, with Free and ServiceClass Reference fields.

### API Server Changes

Implement field selector `Match` and `PredicateFunc` as noted below.

## Drawbacks
 - Requires #454 split, with Free and ServiceClass Reference fields.
 - Vague understanding of how to implement a field selector.

**Comment by pmorie** [comment]
Nice writeup.  

I agree that it is useful to be able to be able to easily get the plans that are free vs. not-free.  
We have field selectors, which we could use for this without duplicating the information in a label.  The `ServicePlan` type in master already has a `Free` field to match against.

The generic store has a field called `PredicateFunc` that you implement to return a function that determines whether a particular object matches field and label selectors.  Relevant sites in our code:

- [Wiring the `Match` function to `PredicateFunc` for `ServiceClass` registry](https://github.com/kubernetes-incubator/service-catalog/blob/45a11edce0827b1ff69ba7387e6679e0acfeeb3d/pkg/registry/servicecatalog/serviceclass/storage.go#L131)
- [`Match` implementation for `ServiceClass`](https://github.com/kubernetes-incubator/service-catalog/blob/45a11edce0827b1ff69ba7387e6679e0acfeeb3d/pkg/registry/servicecatalog/serviceclass/storage.go#L80-L103)

This allows a client of the API to pass a field selector as an option to list.

We will get most of the wiring for this functionality by virtue of separating `ServicePlan` into a distinct resource - we just need to add the `Free` field to the list of selectable fields.

Thoughts?

**Comment by MHBauer** [comment]
Nice code reference. That's a terrible name that no one would ever connect to any selectors.

Implementing that looks like it takes care of Free. How about selecting the intersection of that with a particular Owning ServiceClass?

**Comment by pmorie** [comment]
@MHBauer 

> Implementing that looks like it takes care of Free. How about selecting the intersection of that with a particular Owning ServiceClass?

Assuming that the reference information between `ServicePlan` and `ServiceClass` is stored on the `ServicePlan`, we could just make the field that held that reference another selectable field.

**Comment by pmorie** [comment]
> Nice code reference. That's a terrible name that no one would ever connect to any selectors.

Yeah - yet another area that the developer guide should address

**Comment by MHBauer** [comment]
Proposal Updated. 

I assume @derekwaynecarr was the derek on the service catalog design meeting of 2017-08-14. There was a suggested implementation in kube core to reference.

**Comment by MHBauer** [comment]
field selectors implemented. closing.

**Comment by MHBauer** [comment]
implemented in https://github.com/kubernetes-incubator/service-catalog/pull/1264
