### ISSUE TITLE
Broker Keeps Reconciling When Using Bearer Auth

### ISSUE THREAD

**Issue by richardfung** [kubernetes-incubator/service-catalog#1132]
The broker will keep reconciling if you use either Bearer of BrokerSpec.AuthInfo.

This happens because the calculation of the checksum uses the string representation of AuthInfo:

```
specString += fmt.Sprintf("AuthInfo: %v\n", spec.AuthInfo)
...
sum := sha256.Sum256([]byte(specString))
```

But AuthInfo is

```
type BrokerAuthInfo struct {
    Basic *BasicAuthConfig `json:"basic,omitempty"`
    Bearer *BearerTokenAuthConfig `json:"bearer,omitempty"`
    BasicAuthSecret *v1.ObjectReference `json:"basicAuthSecret,omitempty"`
}
```

and when Basic or Bearer get printed, it's just the address the pointer references that gets printed. Thus, anytime we create a new Broker object, the checksum will with very high probability be different even if nothing has changed because the object will be allocated in a different memory location.

The reason this was not an issue before is if you use BasicAuthSecret, the object reference actually gets expanded when printing. I don't know Go's fmt well enough to know why this happens but perhaps someone smarter than I am can explain.

Here's an example of what gets printed in my logs:

Basic: `AuthInfo: &{0xc4204e8380 <nil> nil}`
Bearer: `AuthInfo: &{<nil> 0xc4204e8538 nil}`
BasicAuthSecret: `AuthInfo: &{<nil> <nil> &ObjectReference{Kind:,Namespace:default,Name:basic,UID:,APIVersion:,ResourceVersion:,FieldPath:,}}`

EDIT: for some reason it would appear that this is not an issue when using Basic auth, although we still are printing the address of the struct when calculating the checksum. I'm not sure why..

**Comment by MHBauer** [comment]
This would be solved by the switch to `generation`. WDYT @pmorie ?

**Comment by pmorie** [comment]
Should be fixed when we move to generation instead of checksums

**Comment by pmorie** [comment]
i agree @MHBauer - i'm on a janky connection and didn't see your comment in
email

**Comment by MHBauer** [comment]
reraise if still an issue
/close
