### ISSUE TITLE
Proposal: Plan and Parameter updates

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1148]
### Proposal: plan and parameter updates

The user should be able to update the plan and parameters in the `ServiceInstance` resource to cause the instance to be updated in the broker.

#### Secret-parameter-only changes

The `ServiceInstance` object allows users to reference secrets from which parameters are sourced.

There are two ways a user might choose to do this:

1.  Update the instance resource with a new secret name
2.  Update the secret out of band

In the case where a new secret is used, the controller can detect the spec change using the generation field.

In our discussions on this problem so far, we have talked most about an out-of-band change to the secret initially used to supply parameters.

The controller is not allowed to watch secrets.  There must be a way for users to indicate that updates for secret parameters have changed out of band without a spec change in the object.

We can limit unexpected behaviors in this resource by adopting a model out-of-band changes to secrets containing parameters after they are initially used have no effect.  So, I wonder from the group, does anyone actually have a specific use-case that requires out-of-band update without changing the secret name?

We should consider adding support for out of band updates later.

If we have to support them, we could use a field similar to the `RelistRequests` to drive a new generation of the resource from.  If the user needs out of band updates to secrests but doesn't want to change the plan, they can bump the `UpdateRequests` field of the InstanceSpec.

#### API Changes

```go
// InstanceSpec represents the desired state of an Instance.
type InstanceSpec struct {
	// ServiceClassName is the name of the ServiceClass this Instance
	// should be provisioned from.
	//
	// Immutable.
	ServiceClassName string

	// PlanName is the name of the ServicePlan this Instance should be
	// provisioned from.  Mutable.
	PlanName string

	// Parameters is a set of the parameters to be
	// passed to the underlying broker.
	// The inline YAML/JSON payload to be translated into equivalent
	// JSON object.
	// If a top-level parameter name exists in multiples sources among
	// `Parameters` and `ParametersFrom` fields, it is
	// considered to be a user error in the specification.
	// Mutable.
	// +optional
	Parameters *runtime.RawExtension

	// List of sources to populate parameters.
	// If a top-level parameter name exists in multiples sources among
	// `Parameters` and `ParametersFrom` fields, it is
	// considered to be a user error in the specification.
	// Mutable.
	// +optional
	ParametersFrom []ParametersFromSource

	// ExternalID is the identity of this object for use with the OSB API.
	//
	// Immutable.
	ExternalID string
}
```

**Comment by duglin** [comment]
I think you forgot to add the new field.

Seems fine, but like the broker rel-list, I like the idea of having a subresource/route people can PUT to that would bump the (immutable) field for them (e.g. /updateParams).

**Comment by pmorie** [comment]
cc @spadgett
