### ISSUE TITLE
Proposal: Remove bookstore and its client; replace with a single component

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#115]
This is a follow up to some discussion in #110 

I'd like to propose that test-wise, we have too many moving pieces and that one of those pieces comes with some undesirable baggage.

First the case for why there's one moving part too many:

To power e2e tests, it seems the current approach is that a client program (written in Python) drives traffic to the bookstore app (a Node app, as far as I can tell). That bookstore app depends on a service provisioned and bound via use of our APIs and the service catalog controller. So the test program (client) is testing connectivity and usability of the provisioned / bound service _indirectly_. Why so much indirection? The bookstore app is a middleman that can be removed if the client / test program itself is executed _within_ k8s and is itself the direct _consumer_ of the service in question.

To make this suggestion more concrete, imagine that the test program is just a k8s job that we load into a cluster. It connects to a database, does some writes, does some reads, then disconnects. We can watch that job for completion and regardless of success or failure, capture its logs.

Then the case against bookstore baggage... even is it's a very small application, it is essentially a distraction:

1. The bookstore app implements use cases that aren't specifically part of the service catalog problem domain. Service catalog is concerned with provisioning and binding services... building an example that does anything of significance with such a service seems like it should be out of scope (and could be a potential maintenance burden).

    To be fair, I recognize there is a counter-argument to this where using a "real" app as a consumer is a more compelling demo, but I don't think that's a good argument for the source code of said "real app" to necessarily live in this repository. If we wanted to provide a _truly_ compelling demo (entiely separate from the optimized test app I have described above), we could instead create a chart that pairs some existing, popular application like Drupal or Wordpress with a database provisioned and bound through our APIs and the service catalog controller.

1. Node isn't necessarily a competency for developers working in this repo. There's already been some discussion (see #103) about limiting the number of languages a contributor needs to know. Don't get hung up on this tho... this is minor in comparison to the previous point.

**Comment by arschles** [comment]
Is this done already?

**Comment by krancour** [comment]
It isn't done, but it seems the only thing doing anything with it is `contrib/jenkins/deploy.sh`

tbh, I'm not sure I understand why or how we're currently doing anything with Jenkins. It seems we're only gating PRs on Travis CI passing... thus, I'm not sure what value Jenkins anything is currently adding. In turn, I would question whether the whole bookstore app is dead weight we can jettison. If not, then the sentiment of my OP stands-- that a _simpler_ sample consumer would be more practical. That would take the shape of a test client _as_ a consumer. It cuts out the complexity of the bookstore API as an unnecessary middleman between the test client and the provisioned services it's trying to validate.

**Comment by krancour** [comment]
Maybe someone who understand's the dealio with Jenkins wants to weigh in here.

**Comment by pmorie** [comment]
Closing; this is long-gone.
