### ISSUE TITLE
Async processing

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#1150]
Following on to #1147 we need to discuss how, or if, we need to save the current state of the Spec while we're in the middle of processing and OSB API request. This needs to include both sync and async ops.

See https://github.com/kubernetes-incubator/service-catalog/issues/1147#issuecomment-323671982 for a bit of background on this.

Also see: https://github.com/kubernetes-incubator/service-catalog/issues/1149

**Comment by pmorie** [comment]
IIRC, what we eventually converged on in the F2F is that we should have something in the status that represents the current operation in progress.  In conjunction with blocking updates to an instance while there is an operation in progress (see #1149), that should allow us to resume / recover / resend any operation that may have been interrupted by a controller restart.

**Comment by duglin** [comment]
yea, you'd think the controller would be able to know what op to perform by comparing the Spec and the Status but having an explicit field to save time/effort might not be bad.

**Comment by pmorie** [comment]
Seems like we need a specific API proposal here for this now

**Comment by pmorie** [comment]
I think this is a dupe of #1147 now - you okay with closing this @duglin?

**Comment by duglin** [comment]
yup. Since we're not allowing concurrent updates this is no longer an issue.
