### ISSUE TITLE
Ensure that the creator of a ServiceBroker resource has access to get the auth secret

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1167]
Currently there are no checks to ensure that the party that creates the broker resource is allowed to consume the auth secret being registered.  This could potentially allow someone with the ability to create a broker to steal the contents of a secret they were not allowed to view by creating a broker and referencing the service account token they didn't have access to.

We can prevent this by having an admission controller that does a SAR check on the auth secret referenced in a broker resource and ensures that the user that made the request actually has access to that secret.

**Comment by pmorie** [comment]
This is needed to mitigate an escalation vector, so I'm adding it to the 0.1.0 milestone (I will staff it).

**Comment by nilebox** [comment]
> We can prevent this by having an admission controller that does a SAR check on the auth secret referenced in a broker resource

Do we need to handle the case where the permission to the auth secret has been revoked after the broker was created? Admission controller doesn't cover this case I believe.

Also, we probably have the same problem for instance/binding `parametersFrom` referencing secrets?

**Comment by pmorie** [comment]
> Do  we need to handle the case where the permission to the auth secret has  been revoked after the broker was created? Admission controller doesn't cover this case I believe.
>
> Also, we probably have the same problem for instance/binding parametersFrom referencing secrets?

Excellent point.  I think we could do an additional SAR check before the controller gets the secret.  We'll need to store the identity of the user that created or last modified the resource to do that, though.

Interestingly, Kubelet does not perform such checks on the service account a pod runs under to see if it can get the secrets.  Your question has me wondering if it should.

Curious to know what @deads2k and @liggitt think about this matter.

**Comment by liggitt** [comment]
Permission to create objects referencing secrets in a namespace has been sufficient. Subdivision of secret references in a namespace ("you may create pods that reference secret1, but not secret2") has not been a sufficiently important use case yet

Typically, permission to create resources using arbitrary secrets in a namespace is considered more powerful than view access to the secrets

**Comment by pmorie** [comment]
Closed by #1186
