### ISSUE TITLE
Remove Alpha* prefix on all API fields

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1180]
We now have access to the feature gate machinery so that we can disable fields based on flags, so there should be no reason to retain these prefixes.

**Comment by pmorie** [comment]
@jboyd01 can you please take this one?

**Comment by jboyd01** [comment]
Sure @pmorie .  This looks like the full list in types.go:

AlphaParameterSchemas
AlphaRequires 
AlphaServiceInstanceCreateParameterSchema 
AlphaServiceInstanceCredentialCreateParameterSchema 
AlphaServiceInstanceUpdateParameterSchema 
AlphaTags 

Should the package name change also dropping the alpha1 or leave it as is?  pkg/apis/servicecatalog/v1alpha1/types.go

And just remove this portion of the comments?
        // Currently, this field is ALPHA: it may change or disappear at any time
        // and its data will not be migrated.

**Comment by pmorie** [comment]
> Should the package name change also dropping the alpha1 or leave it as is? pkg/apis/servicecatalog/v1alpha1/types.go

No, the package name and API version shouldn't change at this point.  We will change it once we finalize the alpha API (see #1181)

**Comment by pmorie** [comment]
> And just remove this portion of the comments?
// Currently, this field is ALPHA: it may change or disappear at any time
// and its data will not be migrated.

No, I think those comments should stay.  We are just transforming the names of fields.
