### ISSUE TITLE
ERROR: logging before flag.Parse in all log messages

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1187]
Seriously annoying... debugging now.

**Comment by jboyd01** [comment]
I ran across this https://github.com/kubernetes/kubernetes/issues/17162  which has a simple work around but I've also seen that the glog.V(5).Infof() type messages are not displayed making me think something more basic (lack of initialization?) is happening.

**Comment by pmorie** [comment]
I am pretty sure this snuck in with #1112

**Comment by jboyd01** [comment]
FWIW, adding  goflag.CommandLine.Parse([]string{}) at line 49 to controller_manager.go looks to address the logging in the controller.  I also couldn't reproduce any problems with the glog.V(5).Infof() though I swear I was missing this logging last week.
