### ISSUE TITLE
Add support for ResourceQuota over ServiceInstances and ServiceInstanceCredentials

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1197]
We need to be able to use the `ResourceQuota` resource in the core API server to quota the number of `ServiceInstance` and `ServiceInstanceCredential` resources in a namespace.  The plan, as I understand it, for quota for aggregated API is that each aggregated API server that implements quota for its resources should have an admission controller that checks new resources against the core `ResourceQuota` resource.

@derekwaynecarr is that accurate?

**Comment by icereed** [comment]
+1

**Comment by icereed** [comment]
Quota handling is essential for large organizations. Otherwise you are not able to scale the billing with your managed service.

**Comment by pmorie** [comment]
I put help wanted on this issue, but this is best suited for someone with previous kube dev experience

**Comment by MHBauer** [comment]
Is this adapting something that upstream provides?

**Comment by nikhita** [comment]
I'm just starting to contribute to service catalog and I would like to help out on this! :)

However, I just created a PR to support object count quota for resources created via aggregated apiservers (and CRDs) upstream - https://github.com/kubernetes/kubernetes/pull/64201. So I wanted to double check if it made sense to create a quota controller for this now?

> We need to be able to use the ResourceQuota resource in the core API server to quota the number of ServiceInstance and ServiceInstanceCredential resources in a namespace

From the above, I understand that quota is needed only to restrict the number of resources - this is possible by the upstream feature. But if more functionality is required, then a separate quota controller will be needed.

/cc @carolynvs

**Comment by MHBauer** [comment]
from meeting 2017-07-30, needs requirements and more details
