### ISSUE TITLE
What should happen when you update a ServiceBinding for a deleted ServiceInstance

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1198]
Follow-up to #1159; what happens when you try to update a ServiceInstanceCredential when the ServiceInstance is deleted?  Obviously the OSB spec currently lacks update for bindings, but update also encompasses labeling and annotating objects.  It seems like you shouldn't be prevented from labeling or annotating a `ServiceInstanceCredential` when the instance has been deleted.

**Comment by pmorie** [comment]
I think this is a non-issue for 0.1.0; moving to 0.2.0

**Comment by MHBauer** [comment]
ServiceInstanceCredential -> ServiceBinding

**Comment by MHBauer** [comment]
Not sure I understand the followup needed. Is there still anything to do

We prevent people from deleting the service instance if it has bindings.
https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.21/pkg/controller/controller_instance.go#L598-L601
/cc @jboyd01 @pmorie 
/close
