### ISSUE TITLE
Fix older kubernetes-service-catalog images

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-incubator/service-catalog#1212]
Older than `v0.0.19` version of following images are not proper and creates problem while using them, so we need to delete those images or we need to fix them with proper binaries into it.

```
https://quay.io/repository/kubernetes-service-catalog/apiserver-ppc64le
https://quay.io/repository/kubernetes-service-catalog/controller-manager-ppc64le
```

Following are the version needs to be fixed - `v0.0.17, v0.0.16, v0.0.15`

**Comment by duglin** [comment]
I assume you mean just the non-amd64 versions, correct?

**Comment by MHBauer** [comment]
Not going to happen. The tags are the tags. Not branches to be updated.

**Comment by duglin** [comment]
we can delete 'em if they're bad

**Comment by MHBauer** [comment]
Not sure it's worth creating the precedent that we'll backport changes. Especially for an alpha release.

**Comment by mkumatag** [comment]
I vote for deleting them!

**Comment by MHBauer** [comment]
I see now. Miscommunication. Sorry.

Good idea to delete bad images. I do not have quay access.

**Comment by duglin** [comment]
gone.  But it seems like I should delete all non-amd64 v15/16/17 tags, right?

**Comment by mkumatag** [comment]
right!
> gone. But it seems like I should delete all non-amd64 v15/16/17 tags, right?

**Comment by duglin** [comment]
Fixed - closing the issue.  Thanks!

**Comment by mkumatag** [comment]
Thanks a lot @duglin
