### ISSUE TITLE
Rebase on top of 1.8 k8s

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-incubator/service-catalog#1225]
Rebase on top of 1.8 k8s to make service catalog api depend on `k8s.io/api` e.g. use `k8s.io/api/v1` instead of `k8s.io/client-go/pkg/api/v1`.

This issue blocks https://github.com/kubernetes-incubator/service-catalog/pull/1208 due to the reason mentioned in https://github.com/kubernetes-incubator/service-catalog/pull/1208#issue-256142352.

**Comment by mengqiy** [comment]
Closing in favor of #1334.
I will rebase #1208 soon :)

**Comment by nilebox** [comment]
@mengqiy Oops sorry missed this issue :)
