### ISSUE TITLE
We should consider publishing a single image with apiserver and controller-manager

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1239]
Currently, we're publishing separate images for these components.  I don't think there's a strong use-case for doing so, and it would help to avoid skew between apiserver and controller manager to publish only a single image.  Let's discuss in a group meeting.

**Comment by duglin** [comment]
seems reasonable to me - similar to what hyperkube has done.

**Comment by staebler** [comment]
I am working on this.

**Comment by arschles** [comment]
I don't think there's a reason to do this. We publish images from CI, and there's never been skew.

**Comment by pmorie** [comment]
I've had plenty of users report problems with skew.
