### ISSUE TITLE
Service Catalog API server auth not tested on Jenkins

### ISSUE THREAD

**Issue by kibbles-n-bytes** [kubernetes-incubator/service-catalog#1246]
Currently auth is disabled on the API server for the e2e tests run on Jenkins. API aggregation is not yet functional on GKE, and I was unsuccessful in my preliminary attempts at getting auth to work with an un-aggregated API server.

I'm currently reaching out to GKE engineers to learn the timeline for GKE API aggregation, and from there we can decide priorities.

**Comment by MHBauer** [comment]
How about now? I just finished getting API Aggregation support enabled on IKS.

I think this is probably best solved by moving to prow.

**Comment by kibbles-n-bytes** [comment]
This was fixed long ago.
