### ISSUE TITLE
Broker's preferred plan ordering is lost

### ISSUE THREAD

**Issue by spadgett** [kubernetes-incubator/service-catalog#1247]
Brokers return plans for a service as an array. Now that plans have been split out into a separate resource with a reference back to the service class, the order is lost. Clients can no longer display the plans in the broker's preferred order.

**Comment by duglin** [comment]
I'm not sure the list is ordered from the broker - at least per the spec.

**Comment by pmorie** [comment]
Upon further consideration, I think ServiceClass should have an array of human-readable plan names, possibly with references to the ServicePlans.

**Comment by spadgett** [comment]
@duglin I could be misreading the spec, but I assume since it's defined as an array here it's ordered?

https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-objects

**Comment by duglin** [comment]
yup - its an array, but it doesn't say its ordered or that the order has any meaning like "preferred" first.

**Comment by MHBauer** [comment]
An array because that's what javascript supported, not because the order is important.
