### ISSUE TITLE
TPR ServicePlans do not seem happy

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/service-catalog#1256]
While trying to add a missing test for ServicePlan in clientset_test.go it failed for TPRs.
Works fine with etcd suggesting something might be amiss for TPRs only.

**Comment by nilebox** [comment]
@vaikas-google what's the error?

**Comment by vaikas-google** [comment]
Hard panic, something like this:

https://travis-ci.org/kubernetes-incubator/service-catalog/builds/278398204?utm_source=github_status&utm_medium=notification

E0921 21:08:20.049241    3722 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:367
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:939
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:894
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:872
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:874
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:893
/go/src/github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr/list_resources.go:46
/go/src/github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr/storage_interface.go:473
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:272
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:243
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:363
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1014
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:104
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/emicklei/go-restful/container.go:277
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/emicklei/go-restful/container.go:199
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/handler.go:153
<autogenerated>:1
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:50
/usr/local/go/src/net/http/server.go:1918
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:47
/usr/local/go/src/net/http/server.go:1918
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:73
/usr/local/go/src/net/http/server.go:1918
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110
/usr/local/go/src/net/http/server.go:1918
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41
/usr/local/go/src/net/http/server.go:1918
/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91
/usr/local/go/src/runtime/asm_amd64.s:2337
E0921 21:08:20.050412    3722 wrap.go:34] APIServer panic'd on GET /apis/servicecatalog.k8s.io/v1alpha1/serviceplans: runtime error: invalid memory address or nil pointer dereference
goroutine 1346 [running]:
runtime/debug.Stack(0x3d37220, 0xc422156380, 0x2b08dea)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xb5
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1.1(0x285eae0, 0x3eb8c10)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:34 +0xa5
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc42275df18, 0x1, 0x1)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:54 +0x112
panic(0x285eae0, 0x3eb8c10)
	/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest.(*Request).transformResponse(0xc421af6d80, 0xc421e41560, 0xc421416900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:939 +0x217
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest.(*Request).Do.func1(0xc421416900, 0xc421e41560)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:894 +0x7a
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest.(*Request).request.func2(0xc421e41560, 0xc42275bed0, 0xa, 0xc421af6d80, 0xc42275bfe8, 0xc421416900, 0xc422145500, 0x5a, 0x0)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:872 +0xfd
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest.(*Request).request(0xc421af6d80, 0xc42275bfe8, 0x0, 0x0)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:874 +0x6c3
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest.(*Request).Do(0xc421af6d80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:893 +0x10d
github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr.listResource(0x3d47280, 0xc42142f980, 0x2ac4742, 0x12, 0x2abc37f, 0xb, 0x3d1dd60, 0xc421c22300, 0x3d31020, 0xc421be6fc0, ...)
	/go/src/github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr/list_resources.go:46 +0x1fe
github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr.(*store).List(0xc420f9fe60, 0x7f8f601bda48, 0xc422a8b0b0, 0x2ac4742, 0x12, 0x0, 0x0, 0x3d44b20, 0xc422149880, 0x3d46140, ...)
	/go/src/github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr/storage_interface.go:473 +0x315
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).ListPredicate(0xc421be9560, 0x7f8f601be488, 0xc422a8b0b0, 0x3d44b20, 0xc422149880, 0x3d46140, 0xc4221498a0, 0x0, 0x2b46fd8, 0x0, ...)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:272 +0x286
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).List(0xc421be9560, 0x7f8f601be488, 0xc422a8b0b0, 0xc421c222a0, 0x2ab3fa4, 0x2, 0x3d1f6a0, 0xc421c222a0)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:243 +0x228
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ListResource.func1(0x3d371a0, 0xc42100b618, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:363 +0xd5c
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints.restfulListResource.func1(0xc422a8af30, 0xc421c22240)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1014 +0x1ac
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc422a8af30, 0xc421c22240)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:104 +0x2a0
github.com/kubernetes-incubator/service-catalog/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4215bf560, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/emicklei/go-restful/container.go:277 +0xffa
github.com/kubernetes-incubator/service-catalog/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc4215bf560, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/emicklei/go-restful/container.go:199 +0x65
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x2acccdb, 0x19, 0xc4215bf560, 0xc420e9e230, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x6fc
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc421be6140, 0x3d37220, 0xc422156380, 0xc42134cd00)
	<autogenerated>:1 +0xa2
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:50 +0x399
net/http.HandlerFunc.ServeHTTP(0xc421cc1580, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/usr/local/go/src/net/http/server.go:1918 +0x52
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:47 +0x27cf
net/http.HandlerFunc.ServeHTTP(0xc421cc1600, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/usr/local/go/src/net/http/server.go:1918 +0x52
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:73 +0x37e
net/http.HandlerFunc.ServeHTTP(0xc420b31e00, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/usr/local/go/src/net/http/server.go:1918 +0x52
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0x117
net/http.HandlerFunc.ServeHTTP(0xc421be6160, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/usr/local/go/src/net/http/server.go:1918 +0x52
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x17c
net/http.HandlerFunc.ServeHTTP(0xc421be61e0, 0x7f8f60177c58, 0xc42100b558, 0xc42134cd00)
	/usr/local/go/src/net/http/server.go:1918 +0x52
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc421be6220, 0x3d423a0, 0xc42100b558, 0xc42134cd00, 0xc4221454a0)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91 +0xac
created by github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:90 +0x221
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18bf1f7]
goroutine 1346 [running]:
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc42275df18, 0x1, 0x1)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x16f
panic(0x285eae0, 0x3eb8c10)
	/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest.(*Request).transformResponse(0xc421af6d80, 0xc421e41560, 0xc421416900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:939 +0x217
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest.(*Request).Do.func1(0xc421416900, 0xc421e41560)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:894 +0x7a
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest.(*Request).request.func2(0xc421e41560, 0xc42275bed0, 0xa, 0xc421af6d80, 0xc42275bfe8, 0xc421416900, 0xc422145500, 0x5a, 0x0)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:872 +0xfd
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest.(*Request).request(0xc421af6d80, 0xc42275bfe8, 0x0, 0x0)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:874 +0x6c3
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest.(*Request).Do(0xc421af6d80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/client-go/rest/request.go:893 +0x10d
github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr.listResource(0x3d47280, 0xc42142f980, 0x2ac4742, 0x12, 0x2abc37f, 0xb, 0x3d1dd60, 0xc421c22300, 0x3d31020, 0xc421be6fc0, ...)
	/go/src/github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr/list_resources.go:46 +0x1fe
github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr.(*store).List(0xc420f9fe60, 0x7f8f601bda48, 0xc422a8b0b0, 0x2ac4742, 0x12, 0x0, 0x0, 0x3d44b20, 0xc422149880, 0x3d46140, ...)
	/go/src/github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr/storage_interface.go:473 +0x315
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).ListPredicate(0xc421be9560, 0x7f8f601be488, 0xc422a8b0b0, 0x3d44b20, 0xc422149880, 0x3d46140, 0xc4221498a0, 0x0, 0x2b46fd8, 0x0, ...)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:272 +0x286
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).List(0xc421be9560, 0x7f8f601be488, 0xc422a8b0b0, 0xc421c222a0, 0x2ab3fa4, 0x2, 0x3d1f6a0, 0xc421c222a0)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:243 +0x228
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ListResource.func1(0x3d371a0, 0xc42100b618, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:363 +0xd5c
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints.restfulListResource.func1(0xc422a8af30, 0xc421c22240)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1014 +0x1ac
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc422a8af30, 0xc421c22240)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:104 +0x2a0
github.com/kubernetes-incubator/service-catalog/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4215bf560, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/emicklei/go-restful/container.go:277 +0xffa
github.com/kubernetes-incubator/service-catalog/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc4215bf560, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/emicklei/go-restful/container.go:199 +0x65
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x2acccdb, 0x19, 0xc4215bf560, 0xc420e9e230, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x6fc
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc421be6140, 0x3d37220, 0xc422156380, 0xc42134cd00)
	<autogenerated>:1 +0xa2
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:50 +0x399
net/http.HandlerFunc.ServeHTTP(0xc421cc1580, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/usr/local/go/src/net/http/server.go:1918 +0x52
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:47 +0x27cf
net/http.HandlerFunc.ServeHTTP(0xc421cc1600, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/usr/local/go/src/net/http/server.go:1918 +0x52
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:73 +0x37e
net/http.HandlerFunc.ServeHTTP(0xc420b31e00, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/usr/local/go/src/net/http/server.go:1918 +0x52
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0x117
net/http.HandlerFunc.ServeHTTP(0xc421be6160, 0x3d37220, 0xc422156380, 0xc42134cd00)
	/usr/local/go/src/net/http/server.go:1918 +0x52
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x3d37220, 0xc422156380, 0xc42134cd00)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x17c
net/http.HandlerFunc.ServeHTTP(0xc421be61e0, 0x7f8f60177c58, 0xc42100b558, 0xc42134cd00)
	/usr/local/go/src/net/http/server.go:1918 +0x52
github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc421be6220, 0x3d423a0, 0xc42100b558, 0xc42134cd00, 0xc4221454a0)
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91 +0xac
created by github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:90 +0x221
!!! [0921 21:08:20] Call tree:
!!! [0921 21:08:20]  1: test/integration.sh:35 runTests(...)
!!! Error in test/integration.sh:29
  Error in test/integration.sh:29. '((i<3-1))' exited with status 2
Call stack:
  1: test/integration.sh:29 runTests(...)
  2: test/integration.sh:35 main(...)
Exiting with status 1
make: *** [test-integration] Error 1
The command "make verify build test images" exited with 2.
cache.2
store build cache
0.01s

**Comment by pmorie** [comment]
Closed because we removed TPR support :)
