### ISSUE TITLE
Missing omitempty tag

### ISSUE THREAD

**Issue by ash2k** [kubernetes-incubator/service-catalog#1259]
`UserInfo` field in `ServiceInstanceSpec` should have `omitempty` JSON tag. Because it is missing  `ServiceInstance` is not round tripped properly from and to json (and unstructured `map[string]interface{}` representation too) because `userInfo` field with `null` is added to the encoding result.
See https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required

I've just tried to update to new Service Catalog types and some of my tests blew up.

**Comment by pmorie** [comment]
@ash2k - do you think there's a problem that our roundtrip tests should have caught but didn't? (In addition to the missing omitempty tag, I mean)

**Comment by ash2k** [comment]
I'm not sure I understand the question, sorry.
I think a test like [this one](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/unstructured_test.go#L117) would be useful - where each type is converted to and from the "unstructured" representation (`map[string]interface{}`).

**Comment by pmorie** [comment]
Closed by #1263
