### ISSUE TITLE
Clean up storage code

### ISSUE THREAD

**Issue by bmelville** [kubernetes-incubator/service-catalog#126]
Includes 

- [ ] Move to storage package
- [ ] Refactor common storage methods into util for use across the different storage impls
- [ ] Align naming with concepts
    - [ ] Simplify class names
    - [ ] Rename *Services() functions to *ServiceInstances()
    - [ ] Rename *Inventory() to *Catalog() or *ServiceClasses()

**Comment by arschles** [comment]
@bmelville are you thinking we should move to a `./controller/storage` package?

**Comment by bmelville** [comment]
Yes PR coming momentarily for this.
