### ISSUE TITLE
ServiceClass removed from a Broker's catalog are retained in API Server

### ISSUE THREAD

**Issue by staebler** [kubernetes-incubator/service-catalog#1265]
If a ServiceClass is removed from a Broker's catalog, the controller manager does not make any attempt to delete the ServiceClass from the API Server when the new catalog is fetched from the Broker. The ServiceClass also retains the name of the Broker, giving the impression that the ServiceClass is still part of the Broker's catalog.

**Comment by pmorie** [comment]
We should mark these as RemovedFromCatalog for now; likely there are other behaviors supporting this that we will add after 0.1.0

**Comment by vaikas-google** [comment]
@pmorie This is for milestone 0.1.0, should we open more targeted bugs for follow-ups?

**Comment by vaikas-google** [comment]
marked as RemovedFromCatalog, move this out of 0.1.0 for followup.

**Comment by pmorie** [comment]
This is fixed by #1444 and #1450
