### ISSUE TITLE
Migrate to agreed-upon object model

### ISSUE THREAD

**Issue by bmelville** [kubernetes-incubator/service-catalog#127]
Currently we are using the prototype object model in `model/service_controller`. We should migrate to the object model defined our API.

**Comment by pmorie** [comment]
Agree with this issue.  One pattern that @bgrant0607 has mentioned in the past is when using TPR,  to put spec and status into two different resources.  At this moment, I cannot think of what that buys us, but since Brian mentioned it, it probably warrants some investigation.

**Comment by arschles** [comment]
Along with this, I propose the following changes:

- We change the `(./pkg/controller/catalog/storage).Storage` interface and related interfaces to look like what the generated Go client lib will look like
- Make all `Storage` implementations implement the new interface
  - To get ready for the incoming Go client lib's interfaces
  - When the Go client lib comes into the picture, we should be able to get rid of the `Storage` interface with no compilation errors
