### ISSUE TITLE
Update logs about ServiceClass / ServicePlan to include GUID & ExternalName

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/service-catalog#1279]
After using GUIDs for the names for k8s resources for serviceplans and serviceclasses, we should log both the k8s resource name as well as external name in our log messages.

**Comment by pmorie** [comment]
I would like all log messages to have the form:

```
<Kind> "<namespace>/<name>": message
```

**Comment by n3wscott** [comment]
I can help!

**Comment by MHBauer** [comment]
I think completed by the pretty context-builder handles this.

https://github.com/kubernetes-incubator/service-catalog/tree/v0.1.23/pkg/pretty
