### ISSUE TITLE
Allow users to choose service and plan for Instances using Kubernetes names

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1285]
Follow-up from #1249; users should be able to directly specify the kubernetes names of service class and plan.  We should add discrete fields for these that are distinct from the reference fields:

```go
type ServiceInstanceSpec struct
  // other fields omitted
  ServiceClassName string
  ServicePlanName string
}
```

The user should only be able to set one group of these fields at a time (k8s names, external names, external IDs)

**Comment by duglin** [comment]
How is this different from what we agreed to before? I didn't think the user was allowed to set the Ref fields directly and they had to choose these Name fields (or externalIDs as you mentioned in the other issue).

**Comment by pmorie** [comment]
@duglin I have users that have a strong preference to set based on the k8s names.  We will also potentially have future naming schemes that do not use the ID.

**Comment by pmorie** [comment]
This might be a good 0.1.1 candidate, depending on time

**Comment by vaikas-google** [comment]
Starting on this, should these now be ClusterServiceClassName / ClusterServicePlanName then? in contrast with the External[CSCN |CSPN]****

**Comment by pmorie** [comment]
Yep, it should be ClusterService(Class|Plan)Name
