### ISSUE TITLE
Users should be able to choose service and plan for instances using external IDs

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1286]
Follow-up from #1249; users should be able to specify the OSB IDs of service class and plan.  We should add discrete fields for these that are distinct from the reference fields:

```go
type ServiceInstanceSpec struct
  // other fields omitted
  ExternalServiceClassID string
  ExternalServicePlanID string
}
```

sibling to #1285.

**Comment by pmorie** [comment]
Might be a good 0.1.1 candidate

**Comment by carolynvs** [comment]
I'd like to work on this if it isn't already taken.
