### ISSUE TITLE
Rename cluster-level resources to Cluster*

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1288]
Today (Sept 28 2017), we talked to SIG architecture about how we should differentiate the names of the current `ServiceBroker`, `ServiceClass`, and `ServicePlan` resources since we have the possibility of adding namespaced variants of these resources in the future.  The guidance we received was that we should rename the existing resources to `Cluster*`.

**Comment by pmorie** [comment]
@vaikas-google loves doing stuff like this, so assigning him.

**Comment by vaikas-google** [comment]
Ok, so:
ServiceBroker => ClusterServiceBroker
ServiceClass => ClusterServiceClass
ServicePlan => ClusterServicePlan

**Comment by pmorie** [comment]
Correct

**Comment by arschles** [comment]
@pmorie is going to talk with sig-architecture to determine whether we need to maintain Golang API compatibility across beta releases

**Comment by pmorie** [comment]
Resolved by numerous PRs from @vaikas-google
