### ISSUE TITLE
using an unsupported field selector should return an error

### ISSUE THREAD

**Issue by liggitt** [kubernetes-incubator/service-catalog#1291]
the current field selector registration accepts any field selector keys, even unsupported ones:

https://github.com/kubernetes-incubator/service-catalog/blob/d9d0ea84029e4b9f18ba3a8a0c1baee72bbd714f/pkg/apis/servicecatalog/v1alpha1/conversion.go#L24-L34

that should return an error for any unsupported field selector key

**Comment by liggitt** [comment]
cc @spadgett

**Comment by pmorie** [comment]
This is a candidate for 0.1.1
