### ISSUE TITLE
Two serviceclasses with the same external name should not be allowed

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1299]
While testing a fix to https://github.com/kubernetes-incubator/service-catalog/issues/1292, I found that it's possible for two service classes to be created from different brokers using the same externalName, which is a bug.

Fix coming shortly.

**Comment by vaikas-google** [comment]
this has already been fixed.
https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_broker.go#L549

We could list the existing service classes first and not make any changes, but even that would be prone to race conditions if brokers are being added simultaneously.
