### ISSUE TITLE
Add ability to map broker response into specific keys of k8s secret

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1311]
I have heard from several users (and actively desired personally) to be able to map pieces of the broker response into different fields.  For example, if I have an application template that depends on `$DB_URL`, it would be great to map `db.url` into `DB_URL` in the k8s secret created by the catalog, or map `DATABASE_URL` into that field.  We do not want to create templating with this feature, but it should be possible to do simple remapping of keys in the `credentials` portion of the response into secret keys.

Related: https://github.com/openservicebrokerapi/servicebroker/issues/116

**Comment by pmorie** [comment]
cc @luksa

**Comment by pmorie** [comment]
I binned this as 0.2.0 so it was clear that it is not for 0.1.0

**Comment by carolynvs** [comment]
#dibbs 

> We do not want to create templating with this feature

Since I am working on templating (outside of svc-cat), I'd like to work on this. 😀

**Comment by pmorie** [comment]
@luksa has already started working on this, so you two should sync @carolynvs

**Comment by carolynvs** [comment]
@luksa @pmorie  Can this be closed now that #1868 is in, or is there more left to do?

**Comment by carolynvs** [comment]
Closed by #1868
