### ISSUE TITLE
Add more meaningful examples in contrib/apiserver

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1313]
The resources currently in this folder have not been maintained and do not illustrate a lot of API features.  It would be great to get some more detailed (and annotated) examples in this folder.

**Comment by pmorie** [comment]
0.1.1 candidate

**Comment by n3wscott** [comment]
I would be interested in working on this when the logging changes have been done. #dibs?

**Comment by MHBauer** [comment]
Is this in reference to the contents of https://github.com/kubernetes-incubator/service-catalog/tree/2da1e43e9901cb271e0514af4a8bf95762baf395/contrib/examples/apiserver ? 

The greatest in repo use is for the integration round trip test with kubectl. The readme in that folder has a pretty good disclaimer for why they look how they do.
