### ISSUE TITLE
Remove dependency on Kubernetes main repo

### ISSUE THREAD

**Issue by nilebox** [kubernetes-incubator/service-catalog#1323]
Looks like the only packages we actually need from the main repo are:
- https://github.com/kubernetes/kubernetes/tree/master/pkg/util/configz
- https://github.com/kubernetes/kubernetes/tree/master/pkg/util/interrupt

Other imports from kubernetes main repo seem to be accidental or historical, since there are equivalent packages in client-go.

So instead of depending on this giant repo we could just copy the needed files to our repo. Also AFAIK there is a plan to split all `util/*` to its own separate repo.

**Comment by nilebox** [comment]
I plan to look at this issue after updating our dependencies to k8s 1.8.

**Comment by ash2k** [comment]
> Also AFAIK there is a plan to split all util/* to its own separate repo.

https://github.com/kubernetes/common and https://github.com/kubernetes/utils

**Comment by nilebox** [comment]
PR is ready https://github.com/kubernetes-incubator/service-catalog/pull/1355

**Comment by nilebox** [comment]
Libraries issue: https://github.com/kubernetes/kubernetes/issues/50475
Util issue: https://github.com/kubernetes/kubernetes/issues/48209
