### ISSUE TITLE
BrokerClient implements Open Service Broker API

### ISSUE THREAD

**Issue by bmelville** [kubernetes-incubator/service-catalog#133]
The BrokerClient does not implement the complete service broker API spec. It needs to be flushed out to align with the full spec.

**Comment by mkibbe1993** [comment]
Currently my top priority. Am simultaneously working on a fake broker server as a part of testing. Am currently working on provisioning, and will push PRs as I get functional pieces.

**Comment by pmorie** [comment]
This is too broad to be useful (and generally complete); closing - we'll create more specific issues as we find things that need to change.
