### ISSUE TITLE
Fuzzers for API should not import pkg/controller

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1358]
🚫

**Comment by MHBauer** [comment]
@pmorie this looks like a reminder specific to you. Is there more context and some action to take? I looked back into the agenda for this time period and I couldn't find mention of fuzz.

**Comment by MHBauer** [comment]
I looked for where the gofuzz was imported:
```
pkg/controller/serializer_test.go
pkg/apis/servicecatalog/unstructured_test.go
pkg/apis/servicecatalog/serialization_test.go
pkg/apis/servicecatalog/testing/fuzzer.go
```
The first is in the controller directory itself, and is used to test serializing of secrets. 

The following three don't have any direct dependencies on `pkg/controller`. As far as I can tell there are know indirect dependencies as well.
/close
