### ISSUE TITLE
Serve OpenAPI and provide useful columns in kubectl

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1361]
Unfortunately, the generic columnizer was removed from kubectl due to unpredictable behavior.  We should finish the work to serve OpenAPI from the API server and allow useful columns to be shown in kubectl.

**Comment by luksa** [comment]
#dibs

**Comment by luksa** [comment]
Note that the openapi part is ready (see PR https://github.com/kubernetes-incubator/service-catalog/pull/1208). I'm taking care of the columns.
