### ISSUE TITLE
v0.1.0-RC1 wasn't deployed to quay.io

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#1364]
This happens because the deploy script's [logic](https://github.com/kubernetes-incubator/service-catalog/blob/master/contrib/travis/deploy.sh#L25) for determining whether it's a tag fails on the `-RC1` part.

see https://travis-ci.org/kubernetes-incubator/service-catalog/builds/285930705

**Comment by pmorie** [comment]
I am not going to be able to address this today - can someone take this and
get it resolved today?

**Comment by duglin** [comment]
I'll take a stab at it
