### ISSUE TITLE
InProgressProperties cleared when starting orphan mitigation, fails API server validation

### ISSUE THREAD

**Issue by kibbles-n-bytes** [kubernetes-incubator/service-catalog#1366]
We currently clear the `InProgressProperties` on an instance/binding when it enters orphan mitigation. However, the API server requires `InProgressProperties` to exist if there is an operation ongoing, so it rejects the update request.

**Comment by kibbles-n-bytes** [comment]
Simplest thing to do here would be to just not clear the `InProgressProperties`. There's no real information gained from doing this, and the resource having `OrphanMitigationInProgress` set is clear enough that the request has actually failed.

**Comment by pmorie** [comment]
I am fine with the approach michael suggests here

**Comment by kibbles-n-bytes** [comment]
Similarly, it seems the API server blocks updates that have a `CurrentOperation` but not an `OperationStartTime`. Orphan Mitigation restarts the clock so that amount of time allowed for deprovision is not limited by how long the failed provision takes, so I think this should be removed. The `OperationStartTime` is set during the first reconciliation for deprovision, just like with provision.

**Comment by kibbles-n-bytes** [comment]
OR, the better approach would probably be to make this check conditional on whether `OrphanMitigationInProgress` is set or not, as that will ensure the API server wouldn't accept any invalid states.
