### ISSUE TITLE
Controller-manager will crash loop if API server is not immediately available on startup

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1376]
The controller-manager will crash (without retrying) if the the API server is not available when it starts.  This means, for example, that the controller-manager pod routinely crashloops after the helm chart is installed.
A number of people have reported this to me; users find it confusing and it can be a red herring.

We should retry with backoff when this happens.

**Comment by jboyd01** [comment]
I see this all the time when running with Kube's hack/local-cluster-up.sh.  if you monitor the pod status after the helm install, you may see something like this:
$ kubectl get pods --all-namespaces -w
NAMESPACE     NAME                                                  READY     STATUS              RESTARTS   AGE
catalog     catalog-catalog-apiserver-754868d78-9kkwr             0/2       ContainerCreating   0          0s
catalog     catalog-catalog-controller-manager-54fccb9df5-g9mcs   0/1       ContainerCreating   0          0s
default     prometheus-79c4b6dff7-xqtlp                           1/1       Running             0          1h
kube-system   kube-dns-b76db4f7f-mxhhj                              3/3       Running             0          1h
kube-system   kubernetes-dashboard-76c679977c-sz6nn                 1/1       Running             0          1h
kube-system   tiller-deploy-84b97f465c-ht85k                        1/1       Running             0          1h
catalog   catalog-catalog-controller-manager-54fccb9df5-g9mcs   0/1       Running   0         2s
catalog   catalog-catalog-controller-manager-54fccb9df5-g9mcs   0/1       Error     0         3s
catalog   catalog-catalog-apiserver-754868d78-9kkwr   0/2       Running   0         3s
catalog   catalog-catalog-controller-manager-54fccb9df5-g9mcs   0/1       Running   1         4s
catalog   catalog-catalog-controller-manager-54fccb9df5-g9mcs   0/1       Error     1         6s
catalog   catalog-catalog-controller-manager-54fccb9df5-g9mcs   0/1       CrashLoopBackOff   1         10s
catalog   catalog-catalog-apiserver-754868d78-9kkwr   1/2       Running   0         20s
catalog   catalog-catalog-apiserver-754868d78-9kkwr   2/2       Running   0         25s
catalog   catalog-catalog-controller-manager-54fccb9df5-g9mcs   0/1       Running   2         26s
catalog   catalog-catalog-controller-manager-54fccb9df5-g9mcs   0/1       Error     2         28s
catalog   catalog-catalog-controller-manager-54fccb9df5-g9mcs   0/1       CrashLoopBackOff   2         30s
catalog   catalog-catalog-controller-manager-54fccb9df5-g9mcs   0/1       Running   3         56s
catalog   catalog-catalog-controller-manager-54fccb9df5-g9mcs   1/1       Running   3         1m

and if you look at the logs from the failed startup the last log entry is 
F1122 16:53:55.252075       1 controller_manager.go:198] error running controllers: failed to get supported resources from server: unable to retrieve the complete list of server APIs: servicecatalog.k8s.io/v1beta1: the server could not find the requested resource

**Comment by jhiemer** [comment]
Same here on a bigger K8S cluster.
