### ISSUE TITLE
Wrap the logging functions for easier readability.

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/service-catalog#1390]
We currently have bunch of repetitions in our logging, we could wrap the glog functions with localized loggers that tag the consistently formatted Structures. Unless somebody else has a better idea, I think we should do something like this (function names, capitalization, etc. is not important here btw).

I1013 10:54:13.532338    1959 log.go:35] ServiceInstance "instnamespace:instname": FIRST SECOND THIRD
W1013 10:54:13.532394    1959 log.go:35] ServiceInstance "instnamespace:instname": FIRST SECOND THIRD
I1013 10:54:13.532408    1959 log.go:35] ServiceInstance "instnamespace:instname": FIRST SECOND THIRD
W1013 10:54:13.532416    1959 log.go:35] ServiceInstance "instnamespace:instname": FIRST SECOND THIRD

package main

import (
	"github.com/golang/glog"
)

type Instance struct {
	Name      string
	Namespace string
}

type logfunc func(format string, args ...interface{})

func main() {
	instance := Instance{"instname", "instnamespace"}
	mylog(glog.Infof, instance, "%s %s %s\n", "FIRST", "SECOND", "THIRD")
	mylog(glog.Warningf, instance, "%s %s %s\n", "FIRST", "SECOND", "THIRD")
	INFO(instance, "%s %s %s\n", "FIRST", "SECOND", "THIRD")
	WARN(instance, "%s %s %s\n", "FIRST", "SECOND", "THIRD")
}

func INFO(instance Instance, format string, args ...interface{}) {
	mylog(glog.Infof, instance, format, args...)
}

func WARN(instance Instance, format string, args ...interface{}) {
	mylog(glog.Warningf, instance, format, args...)
}

// THERE WOULD BE ONE OF THESE per controller_* or per type. I think reflection 
// is possibly too much work for not much gain...
func mylog(logfunc logfunc, instance Instance, format string, args ...interface{}) {
	var internalArgs []interface{}
	internalArgs = append(internalArgs, instance.Namespace)
	internalArgs = append(internalArgs, instance.Name)
	internalArgs = append(internalArgs, args...)
	logfunc("ServiceInstance \"%v:%v\": "+format, internalArgs...)
}

**Comment by n3wscott** [comment]
Yeah I have been thinking about how to do this. 

I don't know go that well yet, but is there any reflection we could use to pull out some of the info magicly?

**Comment by n3wscott** [comment]
Also, the glog knows the line that logged the statement and sticks that in the log. So wrapping will remove the calling location as far as I understand it.

**Comment by pmorie** [comment]
I think adding functions to the types is probably the better way to go here
for the reason scott pointed out.

**Comment by arschles** [comment]
like @pmorie said. if we add `String() string` methods onto our types (`ServiceInstance`, `ServiceBinding`, etc...), we'll get this for free. See https://godoc.org/fmt#Stringer for why

**Comment by vaikas-google** [comment]
Yeah, that's fine too. FYI, you can get around to losing the line number by removing one from the log stack (Output method), but readable String names are probably better anyways. I'll open an issue to track that.
