### ISSUE TITLE
Move catalog deployment Helm chart under examples

### ISSUE THREAD

**Issue by martinmaly** [kubernetes-incubator/service-catalog#140]
Currently it is in [`./deploy/catalog`](../tree/master/deploy/catalog)

**Comment by bmelville** [comment]
Sorry wrong button...

Does this imply that we are deprecating it as our deployment strategy? Do we have a new deployment strategy? It seems necessary to have something explicit.

**Comment by martinmaly** [comment]
I agree with having something 'blessed' - the right way to deploy the system.
Based on the conversation in #119 I figured it is worth gathering some feedback on where the chart lives. It is not _quite_ an example as it is the official way to spin up the catalog, but it also references the example brokers which could fuel the argument toward moving this somewhere under examples.

Personally, I prefer a more prominent placement of the official deployment Helm chart and keep it up-to-date with whatever the most modern way of deploying catalog with its dependencies is.

**Comment by bmelville** [comment]
Makes sense, I was also thinking along the broker/catalog line. It may be that since the brokers are not "core", we could separate the deployment into catalog chart in the blessed location and contrib/brokers/deploy/ or similar houses chart for deploying the brokers.

**Comment by pmorie** [comment]
Closing for now; we can opena  new issue later if we feel there's a need to change something.
