### ISSUE TITLE
Fail to create ClusterServiceBroker

### ISSUE THREAD

**Issue by leonwanghui** [kubernetes-incubator/service-catalog#1402]
## What version of environ?
- Kubernetes (v1.6.0, one-node)
- Service Catalog (v0.1.0-rc1)
- OS (Ubuntu 17.04)
## What happened?
I  developed a new service broker called [opensds-broker](https://github.com/leonwanghui/opensds-broker), which can transfer request to opensds. When I installed it using helm, everything went well as followed:
```
NAME                                             READY     STATUS    RESTARTS   AGE
opensds-broker-opensds-broker-2617526377-gj873   1/1       Running   0          12m
ups-broker-ups-broker-3390838748-nxsc7           1/1       Running   0          5m
```
But after I created the servicebroker resource in Service Catalog, some errors occured:
```
  status:
    conditions:
    - lastTransitionTime: 2017-10-16T08:19:32Z
      message: 'Error fetching catalog. ClusterServiceBroker "opensds-broker": Error
        getting broker catalog: Get http://opensds-broker-opensds-broker.opensds-broker.svc.cluster.local/v2/catalog:
        dial tcp: lookup opensds-broker-opensds-broker.opensds-broker.svc.cluster.local:
        no such host'
      reason: ErrorFetchingCatalog
      status: "False"
      type: Ready
    operationStartTime: 2017-10-16T08:19:32Z
    reconciledGeneration: 0
```
At first I thought there is something wrong with installation, so I tried to install ups-broker as guided, but same error occured:
```
  status:
    conditions:
    - lastTransitionTime: 2017-10-16T08:29:59Z
      message: 'Error fetching catalog. ClusterServiceBroker "ups-broker": Error getting
        broker catalog: Get http://ups-broker-ups-broker.ups-broker.svc.cluster.local/v2/catalog:
        dial tcp: lookup ups-broker-ups-broker.ups-broker.svc.cluster.local: no such
        host'
      reason: ErrorFetchingCatalog
      status: "False"
      type: Ready
    operationStartTime: 2017-10-16T08:29:59Z
    reconciledGeneration: 0
```

Since I'm not so familiar with this project, so I would be appreciated if someone offers help.

**Comment by pmorie** [comment]
Do you have cluster DNS installed / running correctly?  The error indicates a DNS failure.

**Comment by abhaysingh1722** [comment]
Hey,
Even I am encountering the same error, even though my DNS is installed and running correctly. It'll be a real help if you could provide more insight.

**Comment by jboyd01** [comment]
Catalog controller is trying to contact the broker using the DNS name of your broker's service.  It creates the DNS name by concatinating the <service-name>.<namespace>.svc.cluster.local.   Make sure the service is running.  Take a look at `kubectl get services --all-namespaces` and verify you see your services and that they have an IP address and are running.  You can also try `kubectl describe service ups-broker-ups-broker -n ups-broker`.

**Comment by abhaysingh1722** [comment]
Hi @jboyd01 
Thanks for the reply.

As u mentioned, I ran both the commands describing the status of the broker's service. It was indeed in a running state without any discrepancies. Therefore,  I tried replacing the url in the contrib/examples/walkthrough/ups-broker.yaml from url: http://ups-broker-ups-broker.ups-broker.svc.cluster.local to url: http://[ip-address-on-which-service-is-running]

Now, I encounter a different error as shown below:-
svcat describe broker ups-broker
  Name:     ups-broker                                                                                                                      
  URL:      http://[ip-address-on-which-service-is-running]                                                                                                            
  Status:   ErrorFetchingCatalog - Error fetching catalog. Error getting broker catalog: Get http://[ip-address-on-which-service-is-running]/v2/catalog: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 

However, when I "curl http://[ip-address-on-which-service-is-running]/v2/catalog".
It runs without any problems.

Please let me know how do I proceed further or if anything more needs to be done.

**Comment by jboyd01** [comment]
as mentioned in https://github.com/kubernetes-incubator/service-catalog/issues/1402#issuecomment-336881170 it sounds like DNS or some other critical infrastructure is not working.  You shouldn't need to change the ip address.   What kind of kube cluster are running?  (ie minikube, local-up-cluster, etc)

I just re-read your description - are you on the same versions as the original person reported (v0.1.0rc1 & kube 1.6)?  That is a pretty old version of Service Catalog, and officially Kube 1.6 wasn't supported (https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.0-rc1/docs/install-1.6.md)

I'd recommend picking up a new version of Service Catalog.  We're on v0.1.14 and to the best of my knowledge its pretty stable.  A lot has changed (for the better) over the last 6 months.  Note that you'll still need at least Kubernetes 1.7 or greater.

**Comment by abhaysingh1722** [comment]
Hi @jboyd01
Thanks for replying.

The issue which I mentioned in my comment has been encountered on a system with the following environment:-
Kubernetes version (use kubectl version): 1.9.6
Service Catalog version:- 0.1.14

Type of kube-cluster:- Local-up

OS (e.g. from /etc/os-release): Ubuntu 16.04

Kernel (e.g. uname -a): s390x

Install tools: Docker(Version:18.03.0-ce)

Also, all the pods are up and running as shown below:-

kubectl get pods --all-namespaces

NAMESPACE NAME READY STATUS RESTARTS AGE

catalog catalog-catalog-apiserver 2/2 Running 0 17m

catalog catalog-catalog-controller-manager 1/1 Running 0 17m

kube-system etcd 1/1 Running 0 1d

kube-system kube-apiserver 1/1 Running 0 1d

kube-system kube-controller-manager 1/1 Running 0 1d

kube-system kube-dns 3/3 Running 0 1d

kube-system kube-flannel-ds 2/2 Running 0 1d

kube-system kube-proxy 1/1 Running 0 1d

kube-system kube-scheduler 1/1 Running 0 1d

kube-system tiller-deploy 1/1 Running 0 1d

ups-broker ups-broker-ups-broker 1/1 Running 0 13m
 
cat /etc/resolv.conf

nameserver 127.0.0.1 8.8.8.8 8.8.4.4

search default.svc.cluster.local svc.cluster.local cluster.local

However, I am still facing the issue as mentioned.

Please let me know how do I proceed further or if anything more needs to be done.

**Comment by n3wscott** [comment]
Sounds like an interesting setup and please report back when you solve the issue so we can add some notes to the documentation to support future users, thanks for trailblazing @abhaysingh1722 !

**Comment by abhaysingh1722** [comment]
Hi @jboyd01 
The walkthrough example mentioned in https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.14/docs/walkthrough.md is not working as expected for "kubectl get clusterservicebrokers ups-broker -o yaml"  as I am getting the status as:-
ErrorFetchingCatalog - Error fetching catalog. Error getting broker catalog


**Is there any other way to check if my service catalog build is working correctly or not?**

**Comment by jboyd01** [comment]
@abhaysingh1722 Good to hear you are using a recent build and Kube 1.9.  I don't have experience with s390 nor am I aware of any issues around it.  I routinely run with local-cluster-up.sh.  An alternative you could try is minikube.  Based on the details we've discussed so far, it still sounds like a Kubernetes infrastructure problem.  

If you do `kubectl describe clusterservicebroker ups-broker`  what is the Status and Events listed?

If you look at the Catalog controller log you will see additional details on why the catalog is failing to communicate with the broker, but I imagine the describe command above will highlight the problem.  To view the log you can use the command `kubectl logs -l app=catalog-catalog-controller-manager -n catalog | less`

Are you still overriding the default host name for the broker service (ups-broker-ups-broker.ups-broker.svc.cluster.local) as described in https://github.com/kubernetes-incubator/service-catalog/issues/1402#issuecomment-381649466 ?   What's the describe look like for the service? ie `kubectl describe service ups-broker-ups-broker -n ups-broker`

If you were not aware, you can deploy a pod for investigating the environment and running tools like nslookup or curl within the pod.  This should help resolve or at least determine if DNS is the issue.  For example:
```console
$ kubectl run busybox --image=radial/busyboxplus:curl -i --tty --rm
If you don't see a command prompt, try pressing enter.
[ root@curl-jboyd-fd66dccbf-7s5ws:/ ]$ nslookup ups-broker-ups-broker.ups-broker.svc.cluster.local
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      ups-broker-ups-broker.ups-broker.svc.cluster.local
Address 1: 10.0.0.189 ups-broker-ups-broker.ups-broker.svc.cluster.local

[ root@curl-jboyd-fd66dccbf-7s5ws:/ ]$ curl http://ups-broker-ups-broker.ups-broker.svc.cluster.local/v2/catalog
{"services":[{"name":"user-provided-service","id":"4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468","description":"A user provided service","bindable":true,"dashboard_client":null,"plan_updateable":true,"plans":[{"name":"default","id":"86064792-7ea2-467b-af93-ac9694d96d52","description":"Sample plan description","free":true},{"name":"premium","id":"cc0d7529-18e8-416d-8946-6f7456acd589","description":"Premium plan"}]},{"name":"user-provided-service-single-plan","id":"5f6e6cf6-ffdd-425f-a2c7-3c9258ad2468","description":"A user provided service","bindable":true,"dashboard_client":null,"plan_updateable":true,"plans":[{"name":"default","id":"96064792-7ea2-467b-af93-ac9694d96d52","description":"Sample plan description","free":true}]},{"name":"user-provided-service-with-schemas","id":"8a6229d4-239e-4790-ba1f-8367004d0473","description":"A user provided service","bindable":true,"dashboard_client":null,"plan_updateable":true,"plans":[{"name":"default","id":"4dbcd97c-c9d2-4c6b-9503-4401a789b558","description":"Plan with parameter and response schemas","free":true,"schemas":{"service_instance":{"create":{"parameters":{"$schema":"http://json-schema.org/draft-04/schema#","properties":{"param-1":{"description":"First input parameter","type":"string"},"param-2":{"description":"Second input parameter","type":"string"}},"type":"object"}},"update":{"parameters":{"$schema":"http://json-schema.org/draft-04/schema#","properties":{"param-1":{"description":"First input parameter","type":"string"},"param-2":{"description":"Second input parameter","type":"string"}},"type":"object"}}},"service_binding":{"create":{"parameters":{"$schema":"http://json-schema.org/draft-04/schema#","properties":{"param-1":{"description":"First input parameter","type":"string"},"param-2":{"description":"Second input parameter","type":"string"}},"type":"object"},"response":{"$schema":"http://json-schema.org/draft-04/schema#","properties":{"credentials":{"properties":{"
```

**Comment by abhaysingh1722** [comment]
Hi @jboyd01
Thanks for replying. I'll have a look, with those commands.

Is there any other **example** to check if my service catalog build is working correctly or not?

**Comment by jboyd01** [comment]
@abhaysingh1722 the ups broker is a simple broker many Catalog developers use every day for simple test and verification.  This should work and I think its the most straight forward configuration.   I don't think its an issue with the build - everything is pointing to an error with the Catalog Controller pod being able to communicate with the broker pod.  I'd pursue reviewing the events & status from `kubectl describe service ups-broker-ups-broker -n ups-broker`
