### ISSUE TITLE
Improve test constructs for events

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1409]
Currently we have a ton of tests that concatenate strings; a more fluent API would be helpful for this.

@n3wscott this has your name all over it

**Comment by n3wscott** [comment]
#dibs

**Comment by MHBauer** [comment]
@n3wscott @pmorie Is this fully cleaned up enough to your satisfaction to close?

**Comment by n3wscott** [comment]
I think so.
