### ISSUE TITLE
servicebinding reconciliation errors prevent binding from being deleted

### ISSUE THREAD

**Issue by jboyd01** [kubernetes-incubator/service-catalog#1423]
If the ServiceBinding is in an error state, it can block deletion of the binding.
I've seen several examples of this:
1) Go through the walkthrough without starting the service broker.  
A.  kubectl create -f contrib/examples/walkthrough/ups-broker.yaml
B.  kubectl create namespace test-ns
C.  kubectl create -f contrib/examples/walkthrough/ups-instance.yaml
D.  kubectl create -f contrib/examples/walkthrough/ups-binding.yaml
E.  At this point you can't get rid of the binding.  Try kubectl delete -n test-ns servicebindings ups-binding
F.  The instance can't be deleted either because of the associated binding.

2.  I used a Service Broker that had a non-bindable ClusterServiceClass.  I created a binding, but then the controller just kept logging an error like " 'Warning' reason: 'ErrorNonbindableServiceClass' References a non-bindable ClusterServiceClass (K8S: "ab24ffd54da0aefdea5277e0edce8425" ExternalName: "dh-hastebin-apb") and Plan ("default") combination" and I couldn't delete the binding.

I'm kind of lite on the details in #2 but I can reproduce if necessary (OpenShift with the Ansible Service Broker and hastebin service).

I believe another variation of example 1 can be achieved by modifying contrib/examples/walkthrough/ups-instance.yaml to point to a bogus class name.

**Comment by pmorie** [comment]
I am not sure that I understand the first point here.  At point (E), what state are the ServiceInstance and ServiceBinding in?  That would be helpful to put into this issue for posterity.

**Comment by n3wscott** [comment]
From what I understand, the service instance exists but does not revolve to a service instance class.  

The Service Instance is in a ready false state, but because we don't do any checking on accepting the binding, the binding instance gets created and then gets stuck in reconciliation and at this point you can't delete the bad SI nor the bad Binding because the binding is waiting for a class to be resolved, and will never happen.

The root of the issue is we need more admission filtering: #1521, but a side effect of not filtering is we can make bindings on not-ready service instance states.

**Comment by jboyd01** [comment]
serviceinstance after step C (doesn't change with any of the following steps)
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  creationTimestamp: 2017-11-02T20:54:45Z
  finalizers:
  - kubernetes-incubator/service-catalog
  generation: 1
  name: ups-instance
  namespace: test-ns
  resourceVersion: "6"
  selfLink: /apis/servicecatalog.k8s.io/v1beta1/namespaces/test-ns/serviceinstances/ups-instance
  uid: 0e8390a8-c010-11e7-bc33-0242ac110006
spec:
  clusterServiceClassExternalName: user-provided-service
  clusterServicePlanExternalName: default
  externalID: 37be5ef6-507d-4b9d-b040-efc508ff3b6a
  parameters:
    credentials:
      param-1: value-1
      param-2: value-2
  updateRequests: 0
status:
  asyncOpInProgress: false
  conditions:
  - lastTransitionTime: 2017-11-02T20:54:45Z
    message: 'The instance references a ClusterServiceClass that does not exist. References
      a non-existent ClusterServiceClass (ExternalName: "user-provided-service") or
      there is more than one (found: 0)'
    reason: ReferencesNonexistentServiceClass
    status: "False"
    type: Ready
  deprovisionStatus: NotRequired
  orphanMitigationInProgress: false
  reconciledGeneration: 0
```

servicebinding after step d:
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  creationTimestamp: 2017-11-02T20:55:37Z
  finalizers:
  - kubernetes-incubator/service-catalog
  generation: 1
  name: ups-binding
  namespace: test-ns
  resourceVersion: "7"
  selfLink: /apis/servicecatalog.k8s.io/v1beta1/namespaces/test-ns/servicebindings/ups-binding
  uid: 2d7db517-c010-11e7-bc33-0242ac110006
spec:
  externalID: ace90acc-c199-4721-9631-e14a08281881
  instanceRef:
    name: ups-instance
  secretName: ups-binding
status:
  conditions: []
  orphanMitigationInProgress: false
  reconciledGeneration: 0
```

perhaps we should block creating the binding if the instance is in a ready=false state?

**Comment by kibbles-n-bytes** [comment]
I think it's fine having the binding in a retry loop while the instance is getting its references resolved. What we should do is just allow for quick-n-easy deletions of bindings that haven't hit the broker yet.

**Comment by pmorie** [comment]
We cannot block the creation of any API resource due to the status of another resource.  Users will put multiple resources into a single yaml and call it with kubectl create -f.  So, we have to converge on the right state.

So, for the record, in this case the binding is _not_ ready, so it's not clear to my what specifically blocks the deletion of the binding.  Does that make sense?

**Comment by jboyd01** [comment]
Thanks Paul, that makes sense.

From the controller logs, it appears controller_binding must reconcile the binding before it will allow a deletion.  And that always results in an error:
```
I1102 23:54:02.220632       1 controller.go:232] Error syncing ServiceBinding test-ns/ups-binding: ClusterServiceClass or ClusterServicePlan references for Instance have not been resolved yet
I1102 23:54:04.780854       1 controller_binding.go:165] ServiceBinding "test-ns/ups-binding": beginning to process resourceVersion: 49
I1102 23:54:04.780882       1 controller_binding.go:190] ServiceBinding "test-ns/ups-binding": Processing
I1102 23:54:04.780893       1 controller.go:232] Error syncing ServiceBinding test-ns/ups-binding: ClusterServiceClass or ClusterServicePlan references for Instance have not been resolved yet
I1102 23:54:08.865379       1 controller_manager.go:363] Health-checking connection with service-catalog API server
I1102 23:54:08.866680       1 controller_manager.go:259] Created client for API discovery
I1102 23:54:08.933092       1 controller_binding.go:81] ServiceBinding test-ns/ups-binding: received ADD/UPDATE event for: resourceVersion: 51
I1102 23:54:08.933224       1 controller_binding.go:165] ServiceBinding "test-ns/ups-binding": beginning to process resourceVersion: 51
I1102 23:54:08.933293       1 controller_binding.go:190] ServiceBinding "test-ns/ups-binding": Processing
I1102 23:54:08.933326       1 controller.go:232] Error syncing ServiceBinding test-ns/ups-binding: ClusterServiceClass or ClusterServicePlan references for Instance have not been resolved yet
I1102 23:54:09.929602       1 controller_binding.go:165] ServiceBinding "test-ns/ups-binding": beginning to process resourceVersion: 51
I1102 23:54:09.929638       1 controller_binding.go:190] ServiceBinding "test-ns/ups-binding": Processing
I1102 23:54:09.929650       1 controller.go:232] Error syncing ServiceBinding test-ns/ups-binding: ClusterServiceClass or ClusterServicePlan references for Instance have not been resolved yet
I1102 23:54:10.456455       1 controller_manager.go:363] Health-checking connection with service-catalog API server
```
Looking one last time at the servicebinding, I do see the deletion timestamp on there after issuing the delete:
```
[jaboyd@jboyd service-catalog (last-reconciled)]$ kubectl get servicebinding ups-binding -n test-ns -o yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  creationTimestamp: 2017-11-02T20:55:37Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2017-11-02T23:54:08Z
  finalizers:
  - kubernetes-incubator/service-catalog
  generation: 2
  name: ups-binding
  namespace: test-ns
  resourceVersion: "51"
  selfLink: /apis/servicecatalog.k8s.io/v1beta1/namespaces/test-ns/servicebindings/ups-binding
  uid: 2d7db517-c010-11e7-bc33-0242ac110006
spec:
  externalID: ace90acc-c199-4721-9631-e14a08281881
  instanceRef:
    name: ups-instance
  secretName: ups-binding
status:
  conditions: []
  orphanMitigationInProgress: false
  reconciledGeneration: 0
```

**Comment by kibbles-n-bytes** [comment]
The addition of `UnbindStatus` now lets us delete bindings that never communicated with the broker. I believe this solves this issue.
