### ISSUE TITLE
ServiceInstance updates are sending an empty body

### ISSUE THREAD

**Issue by eriknelson** [kubernetes-incubator/service-catalog#1426]
Testing out ServiceInstance updates and it looks like I'm seeing PATCH requests with an empty body on updates; the request dump from our broker logs:

```
[2017-10-18T20:32:20.868Z] [INFO] Request: "PATCH /ansible-service-broker/v2/service_instances/08331836-fe2e-44c5-9618-7d79b3f0115d?accepts_incomplete=true HTTP/1.1\r\nHost: asb.ansible-service-broker.svc:1338\r\n
Accept-Encoding: gzip\r\nContent-Length: 2\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\nX-Broker-Api-Originating-Identity: kubernetes eyJncm91cHMiOlsic3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgiL
CJzeXN0ZW06YXV0aGVudGljYXRlZCJdLCJzY29wZXMuYXV0aG9yaXphdGlvbi5vcGVuc2hpZnQuaW8iOlsidXNlcjpmdWxsIl0sInVpZCI6IiIsInVzZXJuYW1lIjoiYWRtaW4ifQ==\r\nX-Broker-Api-Version: 2.12\r\n\r\n{}"
```

I can reproduce this by editing the secret referenced by the instance's parameters and incrementing `updateRequests`.

**Comment by pmorie** [comment]
So in this case, you changed the secret parameters and they weren't sent?

**Comment by eriknelson** [comment]
@pmorie yep, I made the change via and `oc edit` on the cli and saw the new value correctly viewing the secret in the UI.

**Comment by pmorie** [comment]
I think this needs to be fixed for 0.1.0 if at all possible

**Comment by staebler** [comment]
I verified that there was an issue in rc1. It has been fixed in rc2.

**Comment by vaikas-google** [comment]
Can this be closed then?
