### ISSUE TITLE
RBAC settings

### ISSUE THREAD

**Issue by cloudnautique** [kubernetes-incubator/service-catalog#1428]
I have a v1.8.1 cluster deployed by kubespray with RBAC on. I followed the 1.7 install guide, and made it through. Things look like they are up and running. When I go through the walkthrough 1.7 guide, I deploy the helm chart, but when I run:

`kubectl get clusterservicebrokers,clusterserviceclasses,serviceinstances,servicebindings`

I get:
```
Error from server (Forbidden): clusterservicebrokers.servicecatalog.k8s.io is forbidden: User "kube-apiserver" cannot list clusterservicebrokers.servicecatalog.k8s.io at the cluster scope
Error from server (Forbidden): clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "kube-apiserver" cannot list clusterserviceclasses.servicecatalog.k8s.io at the cluster scope
Error from server (Forbidden): serviceinstances.servicecatalog.k8s.io is forbidden: User "kube-apiserver" cannot list serviceinstances.servicecatalog.k8s.io in the namespace "default"
Error from server (Forbidden): servicebindings.servicecatalog.k8s.io is forbidden: User "kube-apiserver" cannot list servicebindings.servicecatalog.k8s.io in the namespace "default"
```

I am new to RBAC here, and am not sure where the kube-apiserver is, or which Roles to bind. Any pointers?

**Comment by dasher** [comment]
Experiencing a similar issue:
~~~~
Error from server (Forbidden): clusterservicebrokers.servicecatalog.k8s.io is forbidden: User "system:anonymous" cannot list clusterservicebrokers.servicecatalog.k8s.io at the cluster scope
Error from server (Forbidden): clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "system:anonymous" cannot list clusterserviceclasses.servicecatalog.k8s.io at the cluster scope
Error from server (Forbidden): serviceinstances.servicecatalog.k8s.io is forbidden: User "system:anonymous" cannot list serviceinstances.servicecatalog.k8s.io in the namespace "default"
Error from server (Forbidden): servicebindings.servicecatalog.k8s.io is forbidden: User "system:anonymous" cannot list servicebindings.servicecatalog.k8s.io in the namespace "default"
~~~~

I noticed also that the controller-manager was pounding the apiserver - with the apiserver having many forbidden messages in the logs.
I used the --disable-auth flag on the api server to get around the issue for now and to reduce the issues with the deployments so I could continue testing

**Comment by astraverkhau** [comment]
Same here

**Comment by loeh** [comment]
I had the same issue with k8s 1.8.3. Turned out that the kubernetes apiserver had not turned on the --requestheader-client-ca-file flag. So the service catalog api server can't find the configmap which contains the client ca to check the authentication. So the solution in my case was to pass this line:
--requestheader-client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt 
to the arguments of the service catalog api server. I did this simply by editing the deployment configuration of the service catalog apiserver.

**Comment by pravarsh** [comment]
I tried what @loeh suggested but it ```did not``` work for me.

**Comment by freegroup** [comment]
You need the name flag
`--requestheader-client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`

in the deployment of the SC API server of the given Kubernetes API server didn't have set this.
You must create trust the the API extention can communicate the the kubernetes api server.

**Comment by MHBauer** [comment]
1.9 as minimum for aggregation at this point. reopen or make a new issue if it's still a problem
/close
