### ISSUE TITLE
There should be an etcd storage path test

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1434]
Similar to https://github.com/kubernetes/kubernetes/blob/master/test/integration/etcd/etcd_storage_path_test.go, that ensures that the types in our API server are stored in the right locations within etcd.

**Comment by pmorie** [comment]
Setting milestone to 0.1.1, but I would strongly prefer to have this in for 0.1.0

**Comment by jberkhahn** [comment]
closing this. With CRDs on the way I don't think this is worth the effort.
