### ISSUE TITLE
unable to retrieve the complete list of server API

### ISSUE THREAD

**Issue by dasher** [kubernetes-incubator/service-catalog#1445]
Morning,

Having an issue attempting to deploy the chart to kubernetes with the service-catalog-catalog-controller-manager - which is in a crashLoop.

The logs from the pod indicate:

~~~~
F1020 08:50:12.478986       1 controller_manager.go:198] error running controllers: failed to get supported resources from server: unable to retrieve the complete list of server APIs: 
servicecatalog.k8s.io/v1beta1: an error on the server 
("Error: 'x509: certificate is valid for catalog-catalog-apiserver.catalog, catalog-catalog-apiserver.catalog.svc, not service-catalog-catalog-apiserver.mgmt.svc'\n
Trying to reach: 'https://service-catalog-catalog-apiserver:443/apis/servicecatalog.k8s.io/v1beta1'") has prevented the request from succeeding
~~~~

Certs were generated using the svc-cat-apiserver-aggregation-tls-setup.sh helper script.
The chart was deployed with the extra flag --set apiserver.tls.requestHeaderCA=$(base64 --wrap 0 ${SC_SERVING_CA}) to deal with an issue where the APIServer was borking when connecting to the cluster.

RBAC is deployed and enabled and the tiller role binding for cluster admin was added as per the doc (the tiller pod was also restarted).

I am a little confused on how to proceed - any pointers?

**Comment by dasher** [comment]
Finally got around to exploring the issue - and I tweaked the TLS cert generation to compose the ALT name to include missing name, "service-catalog-catalog-apiserver.mgmt.svc"

**Comment by jeffchanjunwei** [comment]
hi @dasher , where is the  svc-cat-apiserver-aggregation-tls-setup.sh file you mentioned. I also have the same problem with the error error 
"_**running controllers: failed to get supported resources from server: unable to retrieve the complete list of server APIs: servicecatalog.k8s.io/v1beta1: an error on the server ("Error: 'x509: certificate has expired or is not yet valid'\nTrying to reach: 'https://10.233.46.245:443/apis/servicecatalog.k8s.io/v1beta1'") has prevented the request from succeeding**_"
If controller invokes with svc ip of apiserver, how can I tweak the tls?
