### ISSUE TITLE
Instances that fail provision are never deprovisioned

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1461]
Currently, if an instance fails provision, when that instance is deleted, we skip the deprovision call.  This is due to an assumption that we made during development that the broker is responsible for cleaning up after failed provisions.  However, this assumption was wrong; in fact, the spec has a total gap in the area of what the broker should do when provision fails.

CF's behavior in this situation is to report to the user that the instance failed provision.  The user still has to indicate that the instance should be deprovisioned in order for CF to send a deprovision request.

The bug here is that since we make the assumption that the broker has cleaned up and do not send a deprovision request that we will leak resources when this happens.  I think we should match the behavior of CF in this regard and send a deprovision request even if an instance has failed.  If the broker has already cleaned up after the failed provision request, it can just return 'GONE' which is counted as a success response to the deprovision call.

**Comment by vaikas-google** [comment]
If a resource fails to create, there should be nothing to delete? I think the spec says what to do in error cases, but if a resource fails to get created, there should be nothing to clean up because the resource doesn't exist. Would be good to get more clarity from the spec side, but I think this is the correct behaviour.

**Comment by pmorie** [comment]
That might be the case, but I think parity with CF wins the day here.  If
we do not change this behavior, it means that existing brokers don't work
correctly with kube.

I'm all for clarifying the spec or correcting it if it's not correct, but
this is a blocker for me for the moment.

**Comment by kibbles-n-bytes** [comment]
Per the OSB working group discussion today, we decided that platforms should send a deprovision request for every resource that has been attempted to be provisioned, failed or not.

**Comment by staebler** [comment]
I missed a bit of the latter end of the call. Did we decide that the deprovision should be sent *when* the provision fails? Or should we wait until the the resource is deleted to send the deprovision?

**Comment by pmorie** [comment]
> Did we decide that the deprovision should be sent when the provision fails? Or should we wait until the resource is deleted to send the deprovision?

@vaikas-google @kibbles-n-bytes @jpeeler where did we come down on this in the call?

**Comment by vaikas-google** [comment]
That's really up to us. At the call we agreed that the deprovision will be sent, it's up to us to decide when to do it.

**Comment by staebler** [comment]
OK. Unless I hear other objections, I will opt for the latter option, where the deprovision request is sent when the service-catalog resource is deleted.

**Comment by pmorie** [comment]
>  I will opt for the latter option, where the deprovision request is sent when the service-catalog resource is deleted.

I am +1 on doing that, go for it.

**Comment by kibbles-n-bytes** [comment]
Yeah, I am +1 on that option as well.
