### ISSUE TITLE
v0.1.0-rc2 images are missing from quay

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#1463]
```
$ docker pull quay.io/kubernetes-service-catalog/service-catalog:v0.1.0-rc2
Error response from daemon: manifest for quay.io/kubernetes-service-catalog/service-catalog:v0.1.0-rc2 not found
```

**Comment by kibbles-n-bytes** [comment]
The controller and apiserver images were combined into the single `service-catalog` image after the release of v0.1.0-rc2. To use that release, you have to use the separate controller-manager and apiserver images.

**Comment by krancour** [comment]
> The controller and apiserver images were combined into the single service-catalog image after the release of v0.1.0-rc2.

I didn't realize that change happened post `v0.1.0-rc2`. That being said...

The charts in master reference the image `quay.io/kubernetes-service-catalog/service-catalog:v0.1.0-rc2`, which according to what you have said do not exist-- that's still a problem.

**Comment by pmorie** [comment]
This should be resolved now, at least for the amd64 images - @krancour can you confirm that the images are pushed?

**Comment by krancour** [comment]
`quay.io/kubernetes-service-catalog/service-catalog:v0.1.0-rc2` is still unavailable, but I suppose that's moot because `quay.io/kubernetes-service-catalog/service-catalog:v0.1.0` is.

Closing.
