### ISSUE TITLE
deploymentWatcher might be racey

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#149]
in reviewing the tests for the watcher it raised a question for me.  In the deploymentWatcher() https://github.com/kubernetes-incubator/service-catalog/blob/master/controller/watch/watcher.go#L255  it first gets the list of resources, calls the callback on each, and then goes into its watch loop.

I think that's racey since events could happen between getting the List() and doing the Watch(). I know that eventually the sync logic will catch the missing event, but I was wondering if its more correct to start the Watch() loop in a go routine and then do the List() processing ?

Per confirmation from @arschles, it is racey - we should start the watch and the do the list.

**Comment by pmorie** [comment]
Fixed by #154
