### ISSUE TITLE
Output for oc get clusterserviceclasses is no longer user friendly

### ISSUE THREAD

**Issue by zherman0** [kubernetes-incubator/service-catalog#1530]
The output for 'oc get clusterservicesclasses' is just a list of hashes that does not tell me anything useful.
The output of the prior 'oc get serviceclasses' was well formatted and very helpful.  Is this a known issue or a planned changed?  Please see attached photos:
OC version 3.7.0.alpha
![old-serviceclasses](https://user-images.githubusercontent.com/18728857/32388723-365f5348-c08e-11e7-84a5-d3ebc03108d7.png)
Current OC version v3.7.0-rc.0+782e4ab-102-dirty
![new clusterserviceclasses](https://user-images.githubusercontent.com/18728857/32388775-5d168fd8-c08e-11e7-81c9-c35118dcb2e9.png)

**Comment by MHBauer** [comment]
or use svcat as kubectl plugin or library to oc command.
see:
https://github.com/kubernetes-incubator/service-catalog/tree/v0.1.21/cmd/svcat
https://github.com/kubernetes-incubator/service-catalog/tree/v0.1.21/pkg/svcat

**Comment by jboyd01** [comment]
I think that https://github.com/kubernetes-incubator/service-catalog/pull/2091  (not yet merged) actually addresses the problem and brings back friendly names in the output of Kubernetes commands.
