### ISSUE TITLE
HELP: RestAPIs of service catalog

### ISSUE THREAD

**Issue by Ethan19881224** [kubernetes-incubator/service-catalog#1567]
Im trying to deploy and use service catalog. But I found all the instance operations(like provision/binding/update etc.) are all in cli commands. Is there any RestAPI to call for the same purpose? It's easier to use when brought to production environment.

**Comment by duglin** [comment]
All of the svc-cat operations can be done via the normal Kube REST APIs, but you need to direct the requests to the svc-cat API server (or make sure your normal Kube APIServer is using API aggregation to pull in the svc-cat APIserver behind the scenes).  See: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go for the description of the various types/resources that are defined. Also, see this doc for help on how to use the resources: https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md
