### ISSUE TITLE
Extract Open Service Broker Client into its own package

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#157]
Currently, the Open Service Broker Client is under controller/util.  It should be extracted into its own package; I propose `pkg/brokerapi/openservicebroker` as a path.

**Comment by arschles** [comment]
that package sgtm

**Comment by krancour** [comment]
sgtm

**Comment by pmorie** [comment]
Depends on #161

**Comment by bmelville** [comment]
Not sure if you were going to tackle this Paul, but I can grab it if not.

**Comment by pmorie** [comment]
Go for it @bmelville
