### ISSUE TITLE
Missing RBAC permissions

### ISSUE THREAD

**Issue by ash2k** [kubernetes-incubator/service-catalog#1575]
`update` verb for `secrets` resource is missing. Not sure which role should have it. The code is here:
https://github.com/kubernetes-incubator/service-catalog/blob/c6e446e504b5f2a96cd50d0d3e0373d173145906/pkg/controller/controller_binding.go#L974

Another thing: in Kubernetes 1.8 a new admission controller called [`OwnerReferencesPermissionEnforcement`](https://kubernetes.io/docs/admin/admission-controllers/#ownerreferencespermissionenforcement) was added. Probably some additional permissions are needed for Service Catalog if it is enabled so might be a good idea to put them into the Helm chart. I haven't tried enabling it yet, but I expect there will be issues.

**Comment by MHBauer** [comment]
I'm gonna guess we need to add `"update"` to https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/rbac.yaml#L83

**Comment by MHBauer** [comment]
root cause is we need an e2e test in an RBAC enabled cluster with a test that updates a secret.
