### ISSUE TITLE
e2e walkthrough is failing due to default serviceplan admission controller

### ISSUE THREAD

**Issue by jpeeler** [kubernetes-incubator/service-catalog#1582]
The admission controller ensures that when multiple plans exist, the plan reference either specifies the plan id or external plan name. The problem is that now the ups-broker has an additional plan, there's no way to test that a default is assigned when only one exists.

I'm thinking that rather than simply adding the missing fields in the e2e, that a parameter should be added to specify how many plans to include in the user-broker.

**Comment by pmorie** [comment]
How about adding a service with a single plan and using that?

**Comment by jpeeler** [comment]
Even better, will work on that.

**Comment by pmorie** [comment]
Is this the e2e binary?  I recall now that we disabled that in this repo's CI.

**Comment by jpeeler** [comment]
Yes, the e2e.test binary doesn't look like it's running here.
