### ISSUE TITLE
Support Accept-Encoding for listing catalogs

### ISSUE THREAD

**Issue by bmelville** [kubernetes-incubator/service-catalog#1606]
HTTP supports the ability for clients to ask for encoding if available from the HTTP server, using the `Accept-Encoding` header. The `/v2/catalog` endpoint can have rather large and easily compressible response payloads, and would benefit from supporting encoding where available.

I have already filed an [issue with the OSB API spec](https://github.com/openservicebrokerapi/servicebroker/issues/382) for the possibility of adding guidance as part of the spec, but because this is already available as part of HTTP in general, would it be advantageous to support the most common encoding in the service catalog regardless?

We have found that many HTTP service frameworks support `gzip` and maybe other encodings as well by default, so adding the `Accept-Encoding` header for one or more of those encodings would yield much reduced payloads from listing catalogs.

Here is the list of [official supported encodings](http://www.iana.org/assignments/http-parameters/http-parameters.xhtml#content-coding) for HTTP.

Here is a [good example of negotiation](https://en.wikipedia.org/wiki/HTTP_compression#Compression_scheme_negotiation).

**Comment by pmorie** [comment]
Seems like this is really a property of the OSB client?

**Comment by bmelville** [comment]
According to https://golang.org/pkg/net/http/#Transport, as long as we are not disabling encoding nor setting any custom encoding ourselves, the default HTTP transport will ask gzip and automatically decode responses. I think this satisfies the request from my end.
