### ISSUE TITLE
Rebase on k8s 1.9.1 dependencies

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1610]
One major motivator for this is that we will be able to use explicit versions of these dependenceies that are human-readable and consistent (`kubernetes-1.8`) instead of a random collection of shas.

**Comment by nilebox** [comment]
What's the plan for upgrading to `kubernetes-1.9`?

Looks like it's going to be released today:
> Wed Dec 13: v1.9.0
Thu Dec 14: v1.10.0-alpha.1

https://github.com/kubernetes/features/blob/master/release-1.9/release-1.9.md

**Comment by MHBauer** [comment]
I'd rather go to 1.9 if it's out.

**Comment by pmorie** [comment]
If someone is willing to do the work I would be fine if they went directy
to 1.9.

**Comment by nilebox** [comment]
1.9 is not out yet, but should be released sometime soon.
We can wait until it's out, and check if the release branches were correctly cut in `apimachinery`, `apiserver` and other repos we depend on.

**Comment by pmorie** [comment]
1.9 was released yesterday and has versions of the apimachinery, client,
etc tagged with kubernetes-1.9.0, example:
https://github.com/kubernetes/apimachinery/tree/kubernetes-1.9.0

**Comment by MHBauer** [comment]
Yea baby!
