### ISSUE TITLE
The server doesn't have resource kind "ClusterServiceBroker"

### ISSUE THREAD

**Issue by witlessbird** [kubernetes-incubator/service-catalog#1632]
When following the walkthrough example, I'm getting "error: unable to recognize "contrib/examples/walkthrough/ups-broker.yaml": no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker" when trying to create ups broker via `kubectl create -f contrib/examples/walkthrough/ups-broker.yaml`. 

I tried using broker images versions v0.1.3 and canary with the same result.

**Comment by nivedhan-murugavel** [comment]
@witlessbird I am facing the same issue. how did you resolve it?
