### ISSUE TITLE
Improve kubectl get for the service-catalog resources

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1634]
As probably most people are aware, the current experience using `kubectl get` is not great for our resources:

- Resources lack columns by default
- Adding columns is possible but requires ugly CLI flags

This issue is intertwined with a couple of other issues; I am making this issue to break out what we want to do specifically for `kubectl get` in the next milestone.

**Comment by nilebox** [comment]
@pmorie have the features required to support in Service Catalog been implemented in `apimachinery` and `kubectl` already (default columns)?

**Comment by pmorie** [comment]
@nilebox I believe there are several in-progress PRs.

@luksa can you link the remaining open PRs in other projects here?

**Comment by pmorie** [comment]
Here are the dependent PRs (not including PRs to our repo):

- https://github.com/kubernetes/kube-openapi/pull/25
- https://github.com/kubernetes/kubernetes/pull/56434
- https://github.com/kubernetes/kube-openapi/pull/22
- https://github.com/kubernetes/kube-openapi/pull/24

**Comment by jboyd01** [comment]
Of the PRs listed by Paul in https://github.com/kubernetes-incubator/service-catalog/issues/1634#issuecomment-355176788 only  56434 is still open, the others have been merged.  Also https://github.com/kubernetes-incubator/service-catalog/pull/2091

@luksa

**Comment by jberkhahn** [comment]
It seems this happened?
