### ISSUE TITLE
Use `set -e` in our bash scripts

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#164]
I know I'm probably in the minority here, but it kind of bothers me that we don't tend to check exit codes on commands - which is why in another PR I mentioned using "set -e".  I know there will be times when we just don't care about the exit codes but I've seen way too many projects not notice errors that really should be looked at because of ignoring exit codes.   So, I'd prefer if we defaulted to `set -e` and then used `set +x` in selective spots.

This issue is here to capture the discussion.

**Comment by pmorie** [comment]
+1000 to `set -e`
