### ISSUE TITLE
Travis runs for documentation-only changes

### ISSUE THREAD

**Issue by cgmcintyr** [kubernetes-incubator/service-catalog#1673]
I noticed Travis was running the full `make verify build build-e2e test images` when I made a change to the `docs/walkthrough.md` on a forked version of the service-catalog.

Facebook's react repository had this issue https://github.com/facebook/react/issues/1768, which was fixed by the following PR https://github.com/facebook/react/pull/2000.

The `before_install` bash script from that PR could be adapted to fit service-catalog by excluding the `examples/` pattern from the grep. See:

https://github.com/cgmcintyr/service-catalog/blob/78dd0d927ceefbc2bcaffeb197d9aef234f5bc48/.travis.yml#L13

If the bash script is too dense, I can write up what each line is doing.

**Comment by arschles** [comment]
I'm good with running a stripped down version for docs-only changes

**Comment by MHBauer** [comment]
Gotta run @duglin's href-checker.

**Comment by cgmcintyr** [comment]
See PR #1693 for proposed fix.
