### ISSUE TITLE
Investigate whether integration test rebuild will reuse cache with `-i`

### ISSUE THREAD

**Issue by kibbles-n-bytes** [kubernetes-incubator/service-catalog#1675]
As discussed [here](https://github.com/kubernetes-incubator/service-catalog/pull/1666#discussion_r161266152).

**Comment by jpeeler** [comment]
My only concern is that if you're using a distro provided copy of go, root is required for a -i operation. Perhaps following what was done here would make it fine: https://github.com/kubernetes-incubator/service-catalog/pull/1566. I know it's an edge case, but still.

**Comment by jpeeler** [comment]
It installs to $GOROOT/pkg, which might be in /usr/lib/golang owned by root.

**Comment by MHBauer** [comment]
/remove-lifecycle rotten

This shouldn't matter any more for native build, golang caches build output now. The only investigation could be done on making sure to mount the cache when doing a docker based build.
