### ISSUE TITLE
svcat fails when used with Google Cloud cluster: No Auth Provider for name "gcp"

### ISSUE THREAD

**Issue by kibbles-n-bytes** [kubernetes-incubator/service-catalog#1676]
Looks like the auth plugins for the Go K8S client aren't initialized, so it doesn't know how to communicate with a GKE cluster. For the e2e binary, I remember having to add `import _ "k8s.io/client-go/plugin/pkg/client/auth"`, and that fixed things. However, it looks like Service Catalog doesn't "import _" anything similar; does anyone know how it successfully sets up the auth?

**Comment by carolynvs** [comment]
I think we need to add this? `_ "k8s.io/client-go/plugin/pkg/client/auth"` or maybe gcp explicitly `_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"`

https://github.com/kubernetes/client-go/issues/242#issuecomment-314642965

**Comment by carolynvs** [comment]
To clarify is this a problem with just the cli (svcat), or an issue with the api server?

**Comment by kibbles-n-bytes** [comment]
@carolynvs Yeah, adding that should fix things, though I'm curious how Service Catalog core gets around it, as I couldn't find a similar import statement.

This is just an issue with the svcat CLI.

**Comment by pmorie** [comment]
The catalog itself uses an in-cluster config to talk to other k8s
components - i suspect that is why this is limited to the CLI.
