### ISSUE TITLE
Determine where to host Service Catalog documentation

### ISSUE THREAD

**Issue by jboyd01** [kubernetes-incubator/service-catalog#1677]
From November Service Catalog F2F, we discussed documentation (fixing existing doc and authoring a slew of new doc).  Ville took an action item to determine where we would host this.

f2f meeting minutes: 
 https://docs.google.com/document/d/1j6dTOC4avpNCYSbF2MnDHWvFIuN0DIicf1F4vRC1CiM

**Comment by carolynvs** [comment]
Our docs are hosted at https://svc-cat.io
