### ISSUE TITLE
Update developer doc around code health

### ISSUE THREAD

**Issue by jboyd01** [kubernetes-incubator/service-catalog#1680]
Update CONTRIBUTING.md, DESIGN.md, code-standards.md as seen fit to address code health

This item came from the November Service Catalog F2F meeting minutes:
https://docs.google.com/document/d/1j6dTOC4avpNCYSbF2MnDHWvFIuN0DIicf1F4vRC1CiM

**Comment by n3wscott** [comment]
I feel like we are ok now. Re-open if we all think this is an issue still.
