### ISSUE TITLE
we should choose one uuid library and stick to it

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#1686]
available are 

github.com/pborman/uuid
github.com/satori/go.uuid
k8s.io/apimachinery/pkg/util/uuid

**Comment by carolynvs** [comment]
Looks like k8s.io/apimachinery/pkg/util/uuid wraps github.com/pborman/uuid and adds protection against generated duplicate uuids when requesting them quickly. So maybe that's the one to go with.

**Comment by n3wscott** [comment]
#dips
