### ISSUE TITLE
Can not start svc-cat service with helm

### ISSUE THREAD

**Issue by leonwanghui** [kubernetes-incubator/service-catalog#1717]
When I install service-catalog following the [installation](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/install.md), some errors occurred as follows after I run ```helm install svc-cat/catalog \
    --name catalog --namespace catalog```:
```
Error: parse error in "catalog/templates/apiregistration.yaml": template: catalog/templates/apiregistration.yaml:1: function "genCA" not defined
```

Here is my environment:
**os version**: Ubuntu 16.04.2 LTS
**go version**: go1.9.2 linux/amd64
**k8s version**: v1.9.0 (make from source code)

Thanks!

**Comment by jpeeler** [comment]
Perhaps running helm install with --debug will help show where the issue is.

**Comment by leonwanghui** [comment]
Thanks, but I don't think it would help a lot.
```
root@test:~# helm install svc-cat/catalog     --name catalog --namespace catalog --debug
[debug] Created tunnel using local port: '39872'

[debug] SERVER: "localhost:39872"

[debug] Original chart version: ""
[debug] Fetched svc-cat/catalog to /root/.helm/cache/archive/catalog-0.1.5.tgz

[debug] CHART PATH: /root/.helm/cache/archive/catalog-0.1.5.tgz

Error: parse error in "catalog/templates/apiregistration.yaml": template: catalog/templates/apiregistration.yaml:1: function "genCA" not defined
```

**Comment by krancour** [comment]
You need to be using Helm 2.7.0 or higher. The genCA template function does not exist prior to that. iirc, installation documentation does make note if the 2.7.0+ requirement.

**Comment by leonwanghui** [comment]
@krancour Thanks! It turns out that my helm version is v2.6.2, and everything works fine after I upgrade it to v2.8.0
