### ISSUE TITLE
Prune vendor directory?

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#1722]
When I migrated us to dep, I didn't turn on pruning because of a gap in dep, and how it treats the code-generator repo that caused dep to no properly vendor the non-go code in that repo. Once https://github.com/golang/dep/pull/1545 is merged however, we can turn pruning on if we like.

Do we want to?

**Comment by MHBauer** [comment]
Is pruning 'do not include packages we never call'? If so, why not?

**Comment by carolynvs** [comment]
There are three pruning options available:
* Unused packages - Remove packages that aren't imported
* Non-go code - Removes files not used by go
* Go tests - Removes *_test.go files

I'll submit a PR that demonstrates this, and my workaround for not having that dep PR merged yet. Should be able to remove quite a bit of cruft.
