### ISSUE TITLE
Differentiate svcat commands that are likely to require admin privileges

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1724]
Some of the commands in svcat are likely to require cluster-level privileges for some of the API resources

For example, the `svcat describe class` command will show the provisioned instances of a service class.  In a cluster that uses RBAC, it is likely that this would only work correctly for a user that had cluster-level `get` on the `serviceinstance` type.

We should make an attempt to draw lines for users to show which commands are intended for administrators and which are for ordinary users that don't have cluster-level access.  Maybe a `svcat admin` subcommand to group the admin-only stuff?

**Comment by pmorie** [comment]
Related #1723

**Comment by carolynvs** [comment]
@pmorie Are you okay with closing this in favor of https://github.com/kubernetes-incubator/service-catalog/issues/1726?

**Comment by MHBauer** [comment]
I think the error message in #1726 is required. 

The differentiating as a separate subcommand is too much.

Commentary in documentation is about all I would expect, beyond some error message.

This is pretty much exactly the problem with RBAC & watch, we can't know what we can and cannot see without trying or asking explicitly.

**Comment by MHBauer** [comment]
/assign @jberkhahn 
svcat stuff
