### ISSUE TITLE
Pin to a release version of go-open-service-broker-client

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#1737]
We're currently just using shas directly; I released 0.0.1 this weekend until we finalize versioning scheme - we should pin to a released version instead.

**Comment by MHBauer** [comment]
Nice to have a version to work against.

For whoever tackles this, I'd like voice a request to write down the steps as developer documentation and if possible make a screen recording of the steps in action, however boring they may be.

**Comment by carolynvs** [comment]
I can do this today. I'll write up the steps for working with dep, and how I added the new constraint.
