### ISSUE TITLE
Support listing across all namespaces in svcat

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#1766]
Just like kubectl, we should make it easier to list instances and bindings across namespaces. Right now you can do this with `svcat get instances -n=""`.  The kubectl way would be `svcat get instances --all-namespaces`.

**Comment by cgmcintyr** [comment]
I'd like to work on this issue if no one else is :)

**Comment by carolynvs** [comment]
@cgmcintyr That would be great! 💖 Let me know if you have any questions.
