### ISSUE TITLE
Errors installing service-catalog in an azure hybrid acs cluster

### ISSUE THREAD

**Issue by esheris** [kubernetes-incubator/service-catalog#1769]
Hello,
I am trying to install service-catalog (so i can install OSBA). I have a hybrid (win/linux) test cluster running in azure. I am following the instructions here (https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/install.md) 
After running the helm install, I am seeing 2 errors. the first is on the catalog controller manager:
```
Failed to pull image "quay.io/kubernetes-service-catalog/service-catalog:v0.1.8": rpc error: code = Unknown desc = failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\docker\windowsfilter\df5e10c7e9ee05920cd4256860dba3a3a3627a93cea9204254ab58055659151b: The system cannot find the path specified.
```
The second is on catalog-apiserver. this just ses Error: errImagePull, but also shows this error in the events:
```
Error creating load balancer (will retry): error getting LB for service infrastructure/catalog-catalog-apiserver: Service(infrastructure/catalog-catalog-apiserver) - Loadbalancer not found 
```

My current assumption is that these require linux and for some reason k8s is putting them on windows. I didnt see any way to pass a nodeSelector into the helm installation when I looked at the advanced installation options (https://github.com/kubernetes-incubator/service-catalog/tree/master/charts/catalog)

I manually added the node selector and the pods got reassigned to my linux node, but i'm still having issues with the apiserver going into CrashLoopBackOff. Logs show "Error: cluster doesn't provide requestheader-client-ca-file" and the controller-manager failing readiness probes.

**Comment by sam-cogan** [comment]
Any plans to add a node selector param? At the moment to resolve this I need to taint my windows nodes to make sure the catalog doesn't end up on here.

**Comment by jeremyrickard** [comment]
I'll take a look at this and see if we get this in.

**Comment by carolynvs** [comment]
Yes, we would like to fix this for hybrid clusters. 👍 If you would like to submit a PR to fix the chart, we would be happy to take it!

**Comment by jeremyrickard** [comment]
@esheris could you share what podSelector you ended up using for your ACS cluster is?
