### ISSUE TITLE
Empty service list treated as an error

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kubernetes-incubator/service-catalog#1772]
We are implementing a service broker, which offers a dynamic list of services. It means the list of services is changing and depends on 
other resources. New service broker, just after installation, offers empty list of services, which is treated as an error (issue #924), but in our case it is ok.
The OSB API describes services field: "MAY be empty."

**Comment by jboyd01** [comment]
@pmorie and I just discussed this issue this week and Paul reiterated catalog is right, the spec is wrong but I had it as a follow up to get details and open an issue with the spec.  @pmorie can you elaborate?

**Comment by piotrmiskiewicz** [comment]
So what is the right way to design a system with a service-broker which offers empty list of services? This is a business requirement, that broker will offer the first service after some time (enabling triggered by other application)

**Comment by jboyd01** [comment]
I reviewed with @pmorie and  he agreed we should relax the constraint and allow an empty list of services.  I'll submit a PR to address this.
