### ISSUE TITLE
Unbind should print the deleted bindings

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#1783]
When we delete bindings during `svcat unbind`, the name of the deleted binding should be printed. This acts as both a confirmation of actions performed and to make it clear that unbind removed multiple bindings when performed against an instance.

```console
$ svcat unbind --name BINDING_NAME
deleted BINDING_NAME

$ svcat unbind INSTANCE_NAME
deleted BINDING_NAME_1
deleted BINDING_NAME_2
```

**Comment by jeremyrickard** [comment]
#dibs
