### ISSUE TITLE
svcat sync broker message is misleading

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#1786]
When I sync/relist a broker using svcat, what is really happening under the hood is bumping the relist request field. However the message printed by svcat says "Successfully fetched catalog entries from the NAME broker" which implies that the sync has already occurred.

It would better set expectations if the message where something like "Synchronization requested for broker:  NAME". ~Perhaps a --wait flag could be added that would wait until sync occurs and succeeds or fails?~

* `--wait` is out of scope of this issue, I'll split that out into a new one.

**Comment by pmorie** [comment]
Sounds like a good idea.

**Comment by teaguecole** [comment]
I will work on this.

**Comment by teaguecole** [comment]
I believe this has already been completed.  svcat/broker/sync_cmd.go on the master branch has an updated message at the end of the file on line 62.

**Comment by carolynvs** [comment]
The current message is "Successfully fetched catalog entries from the %s broker" which is incorrect. The message should be "Synchronization requested for broker: %s".

**Comment by teaguecole** [comment]
Ah, sorry, I just caught msyelf.

**Comment by teaguecole** [comment]
Done, I want to go through the walk through/run the code and see the pretty new message.  Obviously this will work, and its not a major change, but I will treat this as if it is since its my first PR for Kubernetes.  Expect pull request this evening.

**Comment by teaguecole** [comment]
How do I mark this as closed as the PR has been approved, merged and closed?

**Comment by duglin** [comment]
I assume you mean this PR: https://github.com/kubernetes-incubator/service-catalog/pull/1979  right?

Put:
```
Closes #1979
```
in the first comment of the PR next time and github will auto-magically close the issue when the PR is merged.

**Comment by duglin** [comment]
Closing - fixed in https://github.com/kubernetes-incubator/service-catalog/pull/1979
