### ISSUE TITLE
Docs: Update walkthrough to better document creating and deleting resources

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes-incubator/service-catalog#1794]
Part of #1678 

Update the walkthrough to better document creating and removing resources. This could include how to use parameters for creating instances and bindings (this is on a separate page, maybe just link to it).  

Should examples only be with Kubectl? Or should we also include svcat?

**Comment by carolynvs** [comment]
Related #1784

**Comment by arschles** [comment]
I think we should include svcat as the primary tool where possible

**Comment by carolynvs** [comment]
Here's an issue to track documenting the schema: https://github.com/kubernetes-incubator/service-catalog/issues/1825

**Comment by jberkhahn** [comment]
I feel like this is satisfied by the walkthrough on the doc site, so closing this one.
