### ISSUE TITLE
Improve status message when async operation in progress

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#1816]
```console
$ svcat get bindings
                   NAME                     NAMESPACE                   INSTANCE                              STATUS
+-----------------------------------------+-----------+------------------------------------------+-------------------------------+
  braided-warthog-wordpress-mysql-binding   default     braided-warthog-wordpress-mysql-instance   ErrorAsyncOperationInProgress

$ svcat describe binding braided-warthog-wordpress-mysql-binding
  Name:        braided-warthog-wordpress-mysql-binding
  Namespace:   default
  Status:      ErrorAsyncOperationInProgress - Another operation for this service instance is in progress.  @ 2018-01-03 08:11:23 -0600 CST
  Instance:    braided-warthog-wordpress-mysql-instance
```

The condition `ErrorAsyncOperationInProgress` is misleading, as the binding is _not_ in an error state. It's just waiting for the instance to be provisioned.

Perhaps we could change it to `AsyncOperationInProgress`?

___
This issue was migrated from the original svcat repo: https://github.com/Azure/service-catalog-cli/issues/93

**Comment by jboyd01** [comment]
I believe this is associated with https://github.com/kubernetes-incubator/service-catalog/issues/1639.  @luksa is addressing the root issue here with a couple of PRs, one of which is https://github.com/kubernetes-incubator/service-catalog/pull/1779.   Basically Service Catalog is erroneously sending multiple requests to the backend broker for an operation and the broker is replying back with an error indicating the operation is already in progress.

I agree today it is confusing and we've had numerous complaints.   While we could special case the error message and change it so it doesn't read as an error, I don't believe you will continue to see these specific errors once these fixes are merged.

**Comment by carolynvs** [comment]
Oh that's great news! 🎉  I didn't realize that arose from a bug. I'll close this out.
