### ISSUE TITLE
Support extended set of config options in kubectl plugin mode

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#1820]
@jberkhahn Added support for a larger set of config values in https://github.com/kubernetes/kubectl. We should make use of that in the svcat plugin.

**Comment by jberkhahn** [comment]
pending (PR in kubernetes/kubectl)[https://github.com/kubernetes/kubectl/pull/348]

**Comment by jboyd01** [comment]
above pr 348 was merged.  What's next for this PR?

**Comment by jberkhahn** [comment]
This actually already happened. Going to close the issue.
