### ISSUE TITLE
Let's re-evaluate if SharedService* names are working for us.

### ISSUE THREAD

**Issue by n3wscott** [kubernetes-incubator/service-catalog#1837]
*Shared*ServiceClass/Plan name seems weird to me because the object is not intended to be shared. It is more like common code, core to the objects. 

Should we rename these internal objects to something like *Common*ServiceClass/Plan?

**Comment by jboyd01** [comment]
Other name suggestions from the slack discussion included "Internal", "Core" and "Anon" and union.

**Comment by MHBauer** [comment]
Where is this? Only SharedX I can find in the codebase is sharedinformers.

**Comment by pmorie** [comment]
We could say ‘SharedXSpecFields’ or something
