### ISSUE TITLE
Controller shouldn't call updateServiceInstanceStatus to remove the finalizer

### ISSUE THREAD

**Issue by luksa** [kubernetes-incubator/service-catalog#1842]
The controller is calling `updateServiceInstanceStatus()` after removing the finalizer. See: https://github.com/kubernetes-incubator/service-catalog/blob/5d7041b0dde6748659bc78e164338d4bac40fe7b/pkg/controller/controller_instance.go#L1472-L1476

Since finalizers are part of the `Metadata`, not the `Status`, they should be updated through something like `updateServiceInstance()`. Oddly, the API server doesn't complain and actually modifies the whole object, instead of just the status. I consider that a bug as well. Or am I missing something?

**Comment by pmorie** [comment]
That’s the correct and expected behavior of a status subresource.

**Comment by luksa** [comment]
Are you sure? https://github.com/kubernetes/kubernetes/issues/45539 seems to imply otherwise. From what I gather from the discussions in related issues/PRs, mutating labels shouldn't be allowed, whereas annotations should be. But there's no mention of finalizers. 

I uncovered this when adding logic to the controller, which checks if we've actually mutated the status before we post it to the API server. This change broke the removal of the finalizer, since the logic only checks if the status has changed, not the whole object.

**Comment by luksa** [comment]
I'm closing this for now, since the function's documentation now states that the function does more than just update the status: https://github.com/kubernetes-incubator/service-catalog/blob/addf226294bfa3b2cd4f28685c8a05d7babbbc8e/pkg/controller/controller_instance.go#L1222-L1226
