### ISSUE TITLE
[svcat] Bind command should accept a JSON string as parameters

### ISSUE THREAD

**Issue by maqiuyujoyce** [kubernetes-incubator/service-catalog#1871]
Users should be able to specify a flag that receives a JSON string containing the binding parameters. Not all the parameters can be represented as KEY=VALUE pairs, so providing this new option will be very useful.

**Comment by carolynvs** [comment]
Oops! Thank you for bringing this up! 👍 

I see now that we only added the new `--params-json` flag to `svcat provision` and not also `svcat bind`. Essentially we need to do the same work from https://github.com/kubernetes-incubator/service-catalog/pull/1785 but for the bind command.
