### ISSUE TITLE
Proposal: Default Service Plans

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#1873]
Full details are in a google doc: https://docs.google.com/document/d/1HJ7KC9uSoUiAyFwShwgk2FMIQD36FVoGKzyhiDfYNWE/edit?usp=sharing

Here's a tldr:

# Abstract
Let’s wholesale rip off how default storage classes for volumes work and apply it to Service Catalog! 😎 This allows us to specify a dependency on a type of service without requiring upfront knowledge of the underlying broker.

> “My application requires a mysql database.”
>
>“I just want to try out this application using the recommended defaults.”
>
>“I need to encourage everyone to use the cheapest plans possible in our integration environment by making a small database the default.”

# Summary
1. Add default provisioning and binding parameters to Service Classes.
1. Add a “Service Type” field to classes and plans, e.g. mysql or redis.
1. Add a default annotation to Service Plans to flag it as the default plan for a particular service type.
1. Service Instances and Bindings fall back to the defaults set on the class when parameters are not provided.
1. Services can be provisioned using only the Service Type, e.g. mysql, and the default plan and parameters are used.

# Goals and Non-Goals
* Enable using the same manifest across cloud providers and brokers.
* Reduce the burden of using Service Catalog by having the brokers and cluster operators to define defaults.
* Non-invasively add optional fields to existing resources to support this feature. This should not interfere with existing functionality.
* Avoid making changes to Service Catalog that aren’t strictly required to support this feature. For example, we aren’t going to rename Service Bindings to Service Claims.
* Dynamic provisioning concepts is out of scope. Concepts such as binding to existing unbound instances, reclaiming instances, instance capacity, binding resources will be considered in a follow-on proposal.

**Comment by MHBauer** [comment]
Probably want a different name so that thought processes aren't confused with https://github.com/kubernetes-incubator/service-catalog/issues/1111
My first thought went to "don't we already have that?" cause of the name of the [code here](https://github.com/kubernetes-incubator/service-catalog/tree/master/plugin/pkg/admission/serviceplan/defaultserviceplan)

**Comment by n3wscott** [comment]
> Probably want a different name so that thought processes aren't confused with #1111

Thanks @MHBauer I did not know that was a feature!

**Comment by MHBauer** [comment]
@n3wscott Unfortunately, that's what I keep hearing.
