### ISSUE TITLE
 servicecatalog-api-server stuck at Installing API group servicecatalog.k8s.io and can' go on run

### ISSUE THREAD

**Issue by kyhwsk** [kubernetes-incubator/service-catalog#1877]
I'm installing service catalog to my cluster, but servicecatalog-api-server can't run correct.

the last lines of servicecatalog-api-server log:

I0327 09:04:43.653054       1 storage_factory.go:278] storing {servicecatalog.k8s.io serviceinstances} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebackend.Config{Type:"", Prefix:"/registry", ServerList:[]string{"http://10.26.0.10:2379"}, KeyFile:"", CertFile:"", CAFile:"", Quorum:true, Paging:true, DeserializationCacheSize:0, Codec:runtime.Codec(nil), Transformer:value.Transformer(nil), CompactionInterval:300000000000}
I0327 09:04:43.653080       1 storage_factory.go:278] storing {servicecatalog.k8s.io servicebindings} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebackend.Config{Type:"", Prefix:"/registry", ServerList:[]string{"http://10.26.0.10:2379"}, KeyFile:"", CertFile:"", CAFile:"", Quorum:true, Paging:true, DeserializationCacheSize:0, Codec:runtime.Codec(nil), Transformer:value.Transformer(nil), CompactionInterval:300000000000}
I0327 09:04:45.582778       1 compact.go:54] compactor already exists for endpoints [http://10.26.0.10:2379]
I0327 09:04:56.686531       1 compact.go:54] compactor already exists for endpoints [http://10.26.0.10:2379]
I0327 09:05:15.979366       1 compact.go:54] compactor already exists for endpoints [http://10.26.0.10:2379]
I0327 09:05:35.679370       1 compact.go:54] compactor already exists for endpoints [http://10.26.0.10:2379]
I0327 09:05:43.566414       1 etcd_config.go:113] Installing API group servicecatalog.k8s.io

it  stuck at   Installing API group servicecatalog.k8s.io and can' go on run.

what's the reason ?

**Comment by MHBauer** [comment]
What version and how did you install?

My logs look the same as yours up to that point.

```
I0327 14:40:15.921009       1 etcd_config.go:100] Installing API groups
I0327 14:40:15.921034       1 storage_factory.go:278] storing {servicecatalog.k8s.io clusterservicebrokers} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebacken$
I0327 14:40:15.921081       1 storage_factory.go:278] storing {servicecatalog.k8s.io clusterserviceclasses} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebacken$
I0327 14:40:15.921108       1 storage_factory.go:278] storing {servicecatalog.k8s.io clusterserviceplans} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebackend.$
I0327 14:40:15.921131       1 storage_factory.go:278] storing {servicecatalog.k8s.io serviceinstances} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebackend.Con$
I0327 14:40:15.921152       1 storage_factory.go:278] storing {servicecatalog.k8s.io servicebindings} in servicecatalog.k8s.io/v1beta1, reading as servicecatalog.k8s.io/__internal from storagebackend.Conf$
I0327 14:40:15.921548       1 compact.go:54] compactor already exists for endpoints [http://localhost:2379]
I0327 14:40:15.922067       1 compact.go:54] compactor already exists for endpoints [http://localhost:2379]
I0327 14:40:15.922218       1 compact.go:54] compactor already exists for endpoints [http://localhost:2379]
I0327 14:40:15.922338       1 compact.go:54] compactor already exists for endpoints [http://localhost:2379]
I0327 14:40:15.922384       1 etcd_config.go:113] Installing API group servicecatalog.k8s.io
I0327 14:40:16.113532       1 storage_factory.go:278] storing {settings.servicecatalog.k8s.io podpresets} in settings.servicecatalog.k8s.io/v1alpha1, reading as settings.servicecatalog.k8s.io/__internal f$
I0327 14:40:16.113562       1 etcd_config.go:113] Installing API group settings.servicecatalog.k8s.io
W0327 14:40:16.113568       1 genericapiserver.go:342] Skipping API settings.servicecatalog.k8s.io/v1alpha1 because it has no resources.
I0327 14:40:16.113607       1 etcd_config.go:132] Finished installing API groups
I0327 14:40:16.113616       1 run_server.go:119] Running the API server
```

**Comment by kyhwsk** [comment]
I tried the v0.1.8 and v0.1.11 both, its get the same results.

but at last I found  it continue running after tens mins. 
it finally logs 

```
     1 storage_factory.go:278] storing {settings.servicecatalog.k8s.io podpresets} in 
```

I think maybe  the time is spent in communication between api-server and etcd

**Comment by kyhwsk** [comment]
I found it was because the resource request of `apiserver-deployment.yml` and `controller-manager-deployment` too small.

after I change the request ,the problem never  recurrent.
