### ISSUE TITLE
We should have a message to warning people not to use --param[s-json] for secret information.

### ISSUE THREAD

**Issue by n3wscott** [kubernetes-incubator/service-catalog#1897]
See https://github.com/kubernetes-incubator/service-catalog/pull/1889#discussion_r178322872

**Comment by carolynvs** [comment]
Here's some more info:

The help text displayed when you run `svcat bind --help` and `svcat provision --help` should append a warning for the `--params-json` flag that `Sensitive information should be placed in a secret and specified with `--secret`.

Here are the two commands that need to be changed:

https://github.com/kubernetes-incubator/service-catalog/blob/e196fc6e1bfff9d74b90a87d71dc364e508acdc7/cmd/svcat/binding/bind_cmd.go#L92-L93

https://github.com/kubernetes-incubator/service-catalog/blob/e196fc6e1bfff9d74b90a87d71dc364e508acdc7/cmd/svcat/instance/provision_cmd.go#L84-L85

There is an existing test for the help text. It should fail after making this change and you can update the test by running the following command `go test ./cmd/svcat/... -update`. See http://svc-cat.io/docs/devguide/#golden-files for an explanation of how our "golden files" work.

**Comment by popaulina** [comment]
#dibs
