### ISSUE TITLE
Error: No  matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker

### ISSUE THREAD

**Issue by etsangsplk** [kubernetes-incubator/service-catalog#1900]
Trying the walkthough
kubectl create -f contrib/examples/walkthrough/ups-broker.yaml
error: unable to recognize "contrib/examples/walkthrough/ups-broker.yaml": no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker

Getting
error: unable to recognize "contrib/examples/walkthrough/ups-broker.yaml": no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker

-----------------------
Version:
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:50:44Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by n3wscott** [comment]
Did you install and then do [Step 1](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md#step-1---installing-the-ups-broker-server)?

**Comment by MHBauer** [comment]
over a month with no response
/close
