### ISSUE TITLE
Svcat unbind and svcat deprovision should use similar syntax

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-incubator/service-catalog#1959]
Why does `svcat unprovision $instancename` work but unbind is `svcat unbind --name=$bindingname`?

@carolynvs

**Comment by carolynvs** [comment]
The thought was that the more common case was to mostly operate against the instance, so the default user experience would be this

```
svcat provision mydb --class mysql --plan free
svcat bind mydb
svcat unbind mydb # unbinds all instances from mydb
svcat deprovision mydb
```
