### ISSUE TITLE
unknown flag: --enable-admission-plugins

### ISSUE THREAD

**Issue by smirzai** [kubernetes-incubator/service-catalog#1967]
I am trying to install sc. I followed the[ Installation guide](https://github.com/kubernetes-incubator/service-catalog/tree/master/charts/ups-broker).

Kubernetes version: 1.10.0
helm version: v2.9.0-rc4

helm install svc-cat/catalog     --name catalog --namespace catalog

k logs catalog-catalog-apiserver-55fdfcd87c-5sgx4 apiserver -n catalog
Error: unknown flag: --enable-admission-plugins

I tried to run the helm from the source fodder, with the same error:
 helm install charts/catalog/     --name catalog --namespace catalog

It seems the change is very recent:

> git blame charts/catalog/templates/apiserver-deployment.yaml
> 2c22fc17 (Nail Islamov     2018-04-20 02:50:09 +1000  42)         - --enable-admission-plugins
> 

I tried to build docker from source but got this error:

> docker run --security-opt label:disable --rm -v :/go/src/github.com/kubernetes-incubator/service-catalog -v /.pkg:/go/pkg --env AZURE_STORAGE_CONNECTION_STRING scbuildimage go build -o bin/defaulter-gen github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/code-generator/cmd/defaulter-gen
> docker: Error response from daemon: invalid volume spec ":/go/src/github.com/kubernetes-incubator/service-catalog": invalid volume specification: ':/go/src/github.com/kubernetes-incubator/service-catalog'.

Maybe it is because I don't know how and where to set AZURE_STORAGE_CONNECTION_STRING

Is the docker image not available in the repository

**Comment by jeremyrickard** [comment]
@smirzai there is currently an issue with the service catalog chart. See #1962

**Comment by MHBauer** [comment]
dup of #1962
