### ISSUE TITLE
Proposal: Some fundamental re-organization may be in order

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#197]
Having recently put a good deal of effort into #176, I've gotten much more familiar with the codebase, but in the process also found that some things to be a bit confusing. I'd like to remediate some of these myself, but I don't want to unilaterally decide that this is what's right... so let's discuss.

First, the word "controller" seems to be overloaded. It seems to refer _both_ to a component (process) of the service catalog that implements control loops (i.e. the non-apiserver component) _and_ it seems also to refer to a constituent part of that component that implements the logic for creating brokers, instances, and bindings via Open Service Broker API and all the k8s book-keeping that accompanies that. This bit of overloading isn't ideal because when someone says "controller," their intended meaning is ambiguous. I'd propose that "controller" be used to refer to the process only and that some refactoring can eliminate the overloaded use of the word "controller" for what is essentially better described as a "handler." (More on that in a bit.)

Second, the word "server" is overloaded and could equally refer to the "apiserver" or the aforementioned controller process. I'd propose that we can strike "server" from our shared vocabulary and instead prefer the more precise terms "controller" and "apiserver." Package names, function names, etc. should be renamed as necessary to bring the code into parity with that shared vocabulary.

There are other components such as "handler" and "watcher" whose roles are not what you might infer from their names. A careful reading of the code indicates that a "handler" uses a "watcher" and a "controller" (to disambiguate, I refer now to a particular chunk of logic) to reify on the basis of the event stream. I would humbly propose that the roles of "controller" and "handler" seem reversed from what one might reasonably expect. To me, at least, it makes more sense that the "controller" (again, a better name is needed) is the coordinator and the "handler" contains the imperative logic that implements specific actions. The notion of "controller" and "watcher" can probably be combined into what I usually refer to simply as "control loops."

Another oddity that I see is that when the controller's "server" is created, it automatically starts watchers (control loops), but a `Start()` function needs to be called on that server to start up its embedded HTTP server (which only serves a health check). Essentially this means that after being instantiated, a controller's "server" is in a _half-started_ state, though one would reasonably expect it to either a. be _completely_ started or b. (my preference) not started _at all_ until `Start()` has been called. (Again, I don't like the unqualified use of the word "server" here anyway.)

From experience working on Steward, I think there's an opportunity to refactor some of this code such that it remains highly testable (more so than now even), but is organized into a more _intuitive_ and _readily comprehensible_ structure that lowers the barrier to contribution and enables us all to speak about constituent parts of the service catalog system without any ambiguity. As I said, I'd like to take a crack at this, but not without some agreement from others that there are some strange smells here that we'd like to fix.

**Comment by arschles** [comment]
![make it so](http://www.quickmeme.com/img/62/628b747f8ccdfb757062f36a27eedecfc2295f515c0586e05fbfb0620c0571a2.jpg)

**Comment by krancour** [comment]
@arschles I'd like to see #176 get in first... rebasing one sizable refactor on top of another isn't fun.

**Comment by duglin** [comment]
Kent,
  I suspect what you’re aiming is probably correct, but given my newbiness to k8s it would help if I could graphically see what you’re suggesting - just w.r.t. the various component first.  Does this come close?

-Doug

**Comment by krancour** [comment]
@duglin I don't know how k8s-specific what I am aiming for actually is.

To the great credit of everyone who worked hard on the code up to this point, what's there now works and I'd say it's mostly "right." I just want to rename and shuffle some things around to pay down some of the overloaded vocab terms and get the code organized in a way that's more intuitive to understand. (Admittedly, this is in reaction to some of the difficulty I felt personally in getting a lay of the land within the repo.)

I want the _controller_ to land somewhere that looks like this\*. (The API surface is regarded as a separate component [separate process] and is out of scope here.)

![197](https://cloud.githubusercontent.com/assets/1821014/21436795/507e55be-c84e-11e6-9c39-3e83cef10527.png)

\* Please excuse my poor drawing skills.

**Comment by pmorie** [comment]
I agree with the picture, generally.  One nit, in my head, the box called 'storage' is the golang API client for the service catalog API.

With that said...

If I'm reading this correctly, I think these concerns are a function of the factoring of the code that came in with the initial drop.  Since we are factoring toward the k8s infrastructure, it's probably useful to take a look at that architecture and see whether that addresses your concerns.  Controllers in k8s are:

1.  Unit tested and unit testable
2.  Integration tested (some of them) and integration testable
3.  E2E tested

**Comment by pmorie** [comment]
Also, let me say for the record, that as someone who has broken his brain many times on writing state-reconciler controllers, that I also appreciate the amount of work that went into what's in the repo today.

**Comment by krancour** [comment]
> Controllers in k8s are...

@pmorie let's make sure we're working from the same definition of a "controller." The overloading of that very term in our current code base (the whole program vs. something that is more of a handler) was part of the impetus for me opening this.

Let's make sure that what I think a controller is (or should be)... is really what a controller is according to k8s...

To me, the controller is the entire program/process that watches the event stream and interacts with the service brokers to reconcile the state of catalog resources with the state of the real world. This definition specifically excludes the apiserver that is also contained in this repo, as that is a _separate_ program/process...

Are you and I working from a unified definition of "controller?" Or do you need to school me?

**Comment by pmorie** [comment]
> To me, the controller is the entire program/process that watches the event stream and interacts with the service brokers to reconcile the state of catalog resources with the state of the real world. This definition specifically excludes the apiserver that is also contained in this repo, as that is a separate program/process...

That is my definition too.

**Comment by krancour** [comment]
@pmorie awesome!

So, popping that frame off the stack... you had said:

> it's probably useful to take a look at that architecture and see whether that addresses your concerns

Can you elaborate at all on if or how that differs either from what we have now or from what I have in mind?

**Comment by pmorie** [comment]
Single controller is fine for now. If we split the controller into multiple ones (likely), we should introduce our own controller-manager.

**Comment by krancour** [comment]
@pmorie are you suggesting one controller each for:

- `ServiceBroker`
- `ServiceInstance`
- `ServiceBinding`

I could easily account for that in the refactoring and we'd end up looking even more like k8s.

**Comment by pmorie** [comment]
@krancour it's FAR easier to start with a single one, probably

**Comment by pmorie** [comment]
Cool. Originally we had multiple controllers for PVs and PVCs and we wound
up refactoring to a single controller to make the system more robust (very
long story here, I'll happily tell all later but more than I want to type
in with my thumbs). TLDR: there were races, livelock on particular
PVs/PVCs, not to mention the whole thing was very complex to analyze,
understand, debug, and maintain.  It took an incredible amount of work to
do that refactor: think like 4-5 people, multi-month effort to do all the
discovery, hash out pseudocode (which had to be done in person),
implementation, testing, etc. It will be a lot easier to iterate on a
single controller and understand where the natural separation of concerns
fall than to force things into particular buckets now.

**Comment by krancour** [comment]
sgtm @pmorie. thanks

**Comment by duglin** [comment]
I think this shows just about the same thing I had in mind - just different boxes - which is fine.

btw - what does “control loop x 3” refer to?  I’m guessing it means there are 3 of them - why 3? Is this related to the discussion you and paul were having about 1 vs multiple controllers?  If so, and if possible, I’d prefer to have one controller that could watch multiple resource types - that would then kick off the appropriate handler as needed.

-Doug

**Comment by krancour** [comment]
"control loop x 3" is three watches-- one each for `ServiceBroker`, `ServiceInstance`, and `ServiceBinding` resources... yes-- with each kicking off the appropriate handler(s) (e.g. add now, and in the future, update, and delete).

**Comment by krancour** [comment]
This was closed by #210
