### ISSUE TITLE
Support decoding secret data directly in svcat

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#1970]
#1961 displays the secret name and keys for a binding, but leaves it as an exercise for the reader to figure out how to see the secret data values.

@n3wscott had the awesome suggestion to add a flag to optionally decode and print the secret data in the output.

```console
$ svcat describe binding ups-binding -n test-ns --show-secrets
  Name:        ups-binding
  Namespace:   test-ns
  Status:      Ready - Injected bind result @ 2018-04-19 22:16:00 +0000 UTC
  Secret:      ups-binding
  Instance:    ups-instance

Secret Data:
  special-key-1:  iloveponies
  special-key-2:   andkittiestoo
```

The help text for `--show-secrets` should make it clear that the secret data will be decoded and included in the output.

**Comment by pmorie** [comment]
I would make it more clear that this is displaying secret data so people
don't accidentally log it, not realizing that they've tainted their logs
with secret values.

**Comment by carolynvs** [comment]
Would putting that in the help text suffice? Or do you mean that the flag name should be like --display-top-secret-data-do-not-log?

**Comment by pmorie** [comment]
Something like `--show-secrets`

On Mon, Apr 23, 2018 at 1:46 PM, Carolyn Van Slyck <notifications@github.com

**Comment by carolynvs** [comment]
Sounds good to me. I've updated the OP with those changes.
