### ISSUE TITLE
Make in-memory storage more robust

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#200]
During his review of #176, @duglin has proposed that in-memory storage should be a bit more robust. I believe it's only to be used for testing anyway, but he has raised an excellent point that if it behaves too differently from other storage implementations, it might provide a false sense of how things work...

For instance, in-memory storage currently tracks pointers to objects. This means the pointer returned in a get operation references the _exact_ object that was stored during an add. The implications of that are that a user could _update_ that object without ever explicitly invoking the storage interface's update function. Since that's _not_ how a "real" implementation (based on 3prs or etcd) behaves, the in-memory impl shouldn't function that way either (even if it's only used for testing).

Another improvement that has been suggested is that the in-memory storage implementations become threadsafe. I think this is also wise, just to cover our bases and avoid the specter of future test flakiness.

**Comment by krancour** [comment]
I'm happy to take on these improvements myself, so unless anyone wants to fight me for it, I am assigning this to myself.

**Comment by duglin** [comment]
thanks!!

**Comment by pmorie** [comment]
My one point of caution would be to keep in mind that the in-memory storage isn't going to be necessary once we move to the API server.  I would avoid spending a lot of energy on code that's going away.

**Comment by krancour** [comment]
> in-memory storage isn't going to be necessary once we move to the API server

I don't quite understand why. My (imperfect) understanding from @arschles is that whatever the apiserver does in terms of storage still needs to be connected up with our own storage back-ends. irl, that may be 3pr backed (also probably going away) or etcd-backed (not implemented yet), but wouldn't the in-memory implementation stick around as, essentially, a fake impl of storage that can be used to facilitate unit tests of controller components?

**Comment by pmorie** [comment]
@krancour in a unit test we should inject a fake client. Example: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status_test.go#L1100

What the API server does for storage doesn't really affect code outside the API server.  The golang API client is the interface from the controller, and is what should be faked. Make sense?

**Comment by krancour** [comment]
We might be talking about two different things. Let's chat on Tuesday.
