### ISSUE TITLE
dead link on docs front page

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#2000]
first link on `svc-cat.io` 404's, goes here http://svc-cat.io/concepts/service-catalog

![screenshot from 2018-04-27 08-14-29](https://user-images.githubusercontent.com/13337345/39370178-2272ef18-49f3-11e8-82ed-5c54470bb655.png)

**Comment by carolynvs** [comment]
Thanks for the issue! I'll submit a PR in a minute to point that to the new introduction that was just merged.
