### ISSUE TITLE
API type names are not up to date

### ISSUE THREAD

**Issue by ash2k** [kubernetes-incubator/service-catalog#2008]
https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/v1/api.md

**Comment by ash2k** [comment]
Page is missing `ClusterServiceClass`, `ClusterServiceBroker`, `ClusterServicePlan`.

**Comment by MHBauer** [comment]
Other than an interesting historic point-in-time reference. I think that whole folder should go away.

**Comment by MHBauer** [comment]
@jberkhahn @jboyd01 can I delete this folder?
