### ISSUE TITLE
Determine long-term what generated code should be checked in and why

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#203]
Checking in generated code has been a subject of considerable disagreement in the last week.  Here's a brief description of the current state:

1.  Kubernetes checks in a lot of generated code
2.  There is planned work to avoid having to check in **all** of that code - though that plan probably lives in certain individual's heads and not in a public place
3.  For now, we've arrived on a stable equilibrium of not checking in bits like deep copies, deep equals, etc

So, this issue is to catalog (ha!) the numerous bits of generated code, why it is or is not checked in in k8s, and decide whether we should check it in in service-catalog or not.

Forked this issue from discussion on #189

**Comment by MHBauer** [comment]
kubernetes/kubernetes#8830 is the upstream tracking issue.

Recent mailing list discussion https://groups.google.com/forum/#!msg/kubernetes-dev/k5ilr4k50BE/ZJtX7LdiAgAJ indicates unhappiness with ugorji, which is codec-gen and types.generated.go

**Comment by arschles** [comment]
@pmorie @MHBauer I believe we check in all generated code in our repo now, no?

**Comment by MHBauer** [comment]
Yes.
