### ISSUE TITLE
Don't show empty parameters

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#2051]
When an instance's parameters are empty, but not nil, svcat is currently printing it out with `{}`. It would be better if we could detect that it's empty and not display the parameters.

**Current Output**
```
$ svcat describe inst redis1
  Name:        redis1
  Namespace:   default
  Status:      Ready - The instance was provisioned successfully @ 2018-05-18 01:22:15 +0000 UTC
  Class:       redis
  Plan:        4-0-9

Parameters:
  {}

Bindings:
No bindings defined
```

**Desired Output**
```
$ svcat describe inst redis1
  Name:        redis1
  Namespace:   default
  Status:      Ready - The instance was provisioned successfully @ 2018-05-18 01:22:15 +0000 UTC
  Class:       redis
  Plan:        4-0-9

Bindings:
No bindings defined
```

The code responsible for writing the parameters is found here:

https://github.com/kubernetes-incubator/service-catalog/blob/30be2f447d5abaa1f24891b2ff226d270bd330ca/cmd/svcat/output/yaml.go#L48-L62

There isn't an existing test for that function, so as part of a pull request, adding a new test file, yaml_test.go, and 2-3 test cases around that function would be required.

**Comment by carolynvs** [comment]
@artmello It's all yours! 👍 

Let me know if you have any questions.

**Comment by n3wscott** [comment]
I would rather see this in the output:
```
$ svcat describe inst redis1
  Name:        redis1
  Namespace:   default
  Status:      Ready - The instance was provisioned successfully @ 2018-05-18 01:22:15 +0000 UTC
  Class:       redis
  Plan:        4-0-9

Parameters:
  No parameters defined

Bindings: 
  No bindings defined
```

**Comment by n3wscott** [comment]
In the JSON output, I would expect the parameters to continue to be `{}`, what is the plan there?

**Comment by artmello** [comment]
@n3wscott as I implemented on the PR, in the JSON output, empty is not displaying anything for Parameters. Also, when no data is available for Parameters, it is not displaying anything, instead of the "No parameters defined" as suggested. I can update the PR with any new decision.

**Comment by n3wscott** [comment]
@artmello I think you implemented the issue as written, I am not questioning your work, I am questioning the original issue. looks at @carolynvs 👀

**Comment by artmello** [comment]
@n3wscott Yep, I understood that :). Just wanted to say that I am fine to updating the PR with any desired approach

**Comment by carolynvs** [comment]
I like @n3wscott 's suggestion, let's go with that! 👍
