### ISSUE TITLE
Add a "deploying" section to dev docs

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#209]
https://github.com/kubernetes-incubator/service-catalog/pull/208#discussion_r93940602

right now build and deploy are kind of merged together - we should split them

**Comment by pmorie** [comment]
I'm changing this to mvp-2 because all of this stuff is going to coalesce around the api server and informer-based controller.  I have some work in-progress for this which is not pushed yet.

**Comment by arschles** [comment]
@pmorie @duglin what is the status of this issue, now that the dev docs and the walkthrough have been split?

**Comment by pmorie** [comment]
Our walkthrough has a section now on deploying the catalog, which refers you to the chart.  Closing
