### ISSUE TITLE
Service Catalog doens't handle upgrades correctly

### ISSUE THREAD

**Issue by arapulido** [kubernetes-incubator/service-catalog#2104]
Steps to reproduce:
* Install version 0.1.19 of the helm chart
* The API server and controller start correctly
* Upgrade to version 0.1.20 of the helm chart

Expected results:
* The API server and controller are upgraded correctly

Actual results:
* The API server starts correctly, but the controller pod doesn't start correctly. Logs:

```
 F0611 08:32:48.900160       1 controller_manager.go:232] error running controllers: failed to get api versions from server: failed to get supported resources from server: unable to retrieve the complete list of server APIs: servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
```

**Comment by carolynvs** [comment]
Working on getting a new release of our helm chart pushed out (for v0.1.21) which may fix what you are seeing (it has a fix for missing ca certs which are causing healthz checks to fail on the controller manager).

I'll ping back when it's ready to try.

**Comment by arapulido** [comment]
@carolynvs thanks! I would love to get a link to the PR fixing the certs issue, as it might be related to an issue I am seeing with the GCP broker

**Comment by carolynvs** [comment]
@arapulido The 0.1.21 chart with the fix for the CA certs is out, you can run the following commands to get it

```
$ helm repo up
$ helm search svc-cat/catalog
NAME           	CHART VERSION	APP VERSION	DESCRIPTION
svc-cat/catalog	0.1.21       	           	service-catalog API server and controller-manag...
```

Here are the relevant PRs for the cert issue:

https://github.com/kubernetes-incubator/service-catalog/pull/2003
https://github.com/kubernetes-incubator/service-catalog/pull/2071

**Comment by carolynvs** [comment]
There is another issue where we are seeing the controller manager in a crash loop backoff. https://github.com/kubernetes-incubator/service-catalog/issues/2100#issuecomment-396591381 I'd be interested in knowing if you are having a similar problem!

**Comment by MHBauer** [comment]
Two newer releases and no follow-up.
