### ISSUE TITLE
Add scope column to svcat get for classes

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#2113]
**This change relies on #2116 being merged first**

Output a NAMESPACE column in svcat get for classes that indicates if the resources is "cluster" or "namespace" scoped. For namespace scoped classes, it should print its namespace, cluster-scoped classes it should be empty.

```
$ svcat get classes
NAME           	NAMESPACE       DESCRIPTION
+-------------+-----------+---------------------+
azure-redis       testns      Azure Redis
mini-mysql    	              Minibroker install of mysql
```

Here's the code responsible for printing the results of `svcat get classes`
https://github.com/kubernetes-incubator/service-catalog/blob/f5f3e7b6bcd4aff8e5771d7c893de8dba05c8cb6/cmd/svcat/output/class.go#L34-L43

The tests use [golden files](https://svc-cat.io/docs/devguide/#golden-files), so after making the change run `make test-update-goldenfiles` and verify that the modified output files are as expected.

**Comment by carolynvs** [comment]
Removing help wanted until we have `get classes` working for namespace scoped resources.

/remove-help

**Comment by luksa** [comment]
Do we really need this? Isn't a simple `NAMESPACE` column enough (we simply leave it empty for cluster-scoped classes)?

**Comment by carolynvs** [comment]
@luksa Originally there were plans to put more information into the column than just namespace but that plan has since been abandoned. Just Namespace makes more sense now. 😊 

I'll update the OP with the desired change.

**Comment by carolynvs** [comment]
Nevermind, today is not my day. 😝 Closing as it will be handled by the other work for namespace scoped support now.
