### ISSUE TITLE
Change default relist and add a config flag

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#2119]
I might not be looking at the right spot, but from looking at the code it appears that we will automatically re-list the broker's catalog every 15 minutes and there is no way to set this default timeout to something else (unless you do it on a per-broker basis as you register them).

While I know there are some brokers that change their catalogs very often (and in those cases I suspect they'll set this re-list timeout to a much lower value for their brokers), it seems like 15 minutes is actually really low/quick - in our experience brokers don't change their catalogs that often.

So, there are two asks:
1 - can we change the default from 15 minutes to something longer, like a few hours?
2 - regardless of number 1, can we get a config option so we can set if for all brokers as they are registered rather than having to set it on each broker's yaml?

ping @MHBauer

**Comment by MHBauer** [comment]
@duglin dup of https://github.com/kubernetes-incubator/service-catalog/issues/1086

**Comment by MHBauer** [comment]
going to leave a comment over there, because it's broken now.

**Comment by MHBauer** [comment]
To answer the question asked, we have a flag
https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/values.yaml#L101-L105
it defaults to true and 24 hrs.

We don't honor the flag, as it's set and never read
https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller.go#L99

**Comment by MHBauer** [comment]
I suppose we can keep it open to have a bug to point at.
/reopen
