### ISSUE TITLE
make build fails

### ISSUE THREAD

**Issue by kargakis** [kubernetes-incubator/service-catalog#2157]
```
$ make build
sed "s/GO_VERSION/1.9/g" < build/build-image/Dockerfile | \
  docker build -t scbuildimage -f - .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/kargakis/kube/src/github.com/kubernetes-incubator/service-catalog/-: no such file or directory
make: *** [.scBuildImage] Error 1
```

On Centos 7

**Comment by MHBauer** [comment]
/assign @duglin 
as he has seen this. I can't remember the workaround quick resolution. I think it has something to do with docker versions and the `-f` flag that's passing in the Dockerfile and also being given a context.

**Comment by jichenjc** [comment]
I had same issue, by doing this , I can start build now

--- a/Makefile
+++ b/Makefile
@@ -197,7 +197,7 @@ $(BINDIR):

 .scBuildImage: build/build-image/Dockerfile
        sed "s/GO_VERSION/$(GO_VERSION)/g" < build/build-image/Dockerfile | \
-         docker build -t scbuildimage -f - .
+         docker build -t scbuildimage -f build/build-image/Dockerfile .

**Comment by carolynvs** [comment]
This is caused by having a really old docker client version.

**Comment by jichenjc** [comment]
I believe we need document this restriction because as you can see, my docker version is 1.13.1 

root@ubuntu1:~/go/src/github.com/kubernetes-incubator/service-catalog# docker --version
Docker version 1.13.1, build 092cba3

if we think it's because older version docker, we should at least document in development guide..

**Comment by carolynvs** [comment]
I'll update the docs. That command requires docker 17.05 and up.

See https://github.com/moby/moby/issues/19197#issuecomment-329974121 for context.
