### ISSUE TITLE
Add Scope and Namespace fields to svcat describe plan

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#2216]
~~🚨  Don't start on this issue yet.~~ **Merged, Ready to Go!**  It relies on new code being added in an active pull request: https://github.com/kubernetes-incubator/service-catalog/pull/2116 🚨

This is the same as https://github.com/kubernetes-incubator/service-catalog/issues/2215 but for plans instead of classes. I recommend waiting for that one to be complete and merged, then use it as a starting point for doing the same thing but for plans.

**Comment by artmello** [comment]
#dibs
