### ISSUE TITLE
gengo dependency needs care in updating

### ISSUE THREAD

**Issue by jpeeler** [kubernetes-incubator/service-catalog#223]
Currently master in gengo will break things (specifically cause code generation for defaults to not be generated) and in #215 will actually break the build. I didn't try analyzing gengo to see what the problem is (the SHA used below is the last working version), but here's a diff showing the change of behavior:

```
diff --git a/glide.lock b/glide.lock
index 45f4986..4226762 100644
--- a/glide.lock
+++ b/glide.lock
@@ -329,7 +329,7 @@ imports:
   - 1.5/tools/metrics
   - 1.5/transport
 - name: k8s.io/gengo
-  version: 8dd9c9e5e82c3cca687497c3cd7ac90e702c7c21
+  version: 7ca94dd123f0f4965aac2e59ef249d8eaef14bcc
   subpackages:
   - args
   - examples/deepcopy-gen/generators
diff --git a/pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go b/pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
index daf7681..3099a76 100644
--- a/pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
+++ b/pkg/apis/servicecatalog/v1alpha1/zz_generated.deepcopy.go
@@ -21,8 +21,8 @@ limitations under the License.
 package v1alpha1
 
 import (
-       api "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api"
-       v1 "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/apis/meta/v1"
+       api "k8s.io/kubernetes/pkg/api"
+       v1 "k8s.io/kubernetes/pkg/apis/meta/v1"
        conversion "k8s.io/kubernetes/pkg/conversion"
        runtime "k8s.io/kubernetes/pkg/runtime"
        reflect "reflect"
@@ -58,8 +58,10 @@ func DeepCopy_v1alpha1_Binding(in interface{}, out interface{}, c *conversion.Cl
                in := in.(*Binding)
                out := out.(*Binding)
                *out = *in
-               if err := api.DeepCopy_api_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, c); err != nil {
+               if newVal, err := c.DeepCopy(&in.ObjectMeta); err != nil {
                        return err
+               } else {
+                       out.ObjectMeta = *newVal.(*api.ObjectMeta)
                }
                if err := DeepCopy_v1alpha1_BindingSpec(&in.Spec, &out.Spec, c); err != nil {
                        return err
@@ -85,8 +87,10 @@ func DeepCopy_v1alpha1_BindingSpec(in interface{}, out interface{}, c *conversio
                in := in.(*BindingSpec)
                out := out.(*BindingSpec)
                *out = *in
```

**Comment by jpeeler** [comment]
For clarity, this is the error when the imports have vendor in the string:

internal error: duplicate loads of github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/apis/meta/v1
internal error: duplicate loads of github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api

https://travis-ci.org/kubernetes-incubator/service-catalog/builds/188983404#L796

**Comment by ncdc** [comment]
@jpeeler open an issue in the gengo repo please

**Comment by thockin** [comment]
This is not a bug in gengo, I think.  Having it generate paths with `vendor` in them seems wrong.  The resulting change looks like you should need to add `k8s.io/kubernetes` to `--bounding-dirs` on deepcopy

**Comment by jpeeler** [comment]
@thockin adding that path to the bounding-dirs doesn't appear to have any effect (while using the latest gengo). Any further advice about what else could be wrong would be appreciated.

**Comment by thockin** [comment]
can you run the generator with --v=5 and send me the log?

**Comment by jpeeler** [comment]
Since the log was 8k lines long, I just emailed it with subject: debug log for kubernetes-incubator/service-catalog/issues/223.

**Comment by jpeeler** [comment]
This should no longer be an issue - https://github.com/kubernetes/gengo/issues/30
