### ISSUE TITLE
Orphan mitigation could break the migration case

### ISSUE THREAD

**Issue by nilebox** [kubernetes-incubator/service-catalog#2242]
We have a migration use case, when we have existing provisioned OSB instances that we migrate to Service Catalog.
We've found a potential problem with orphan mitigation:
1. User creates a ServiceInstance with manually set `spec.externalID` pointing to an existing instance.
2. Service Catalog sends a provision request to the broker, and gets `500 Internal Server Error` back, or even request just times out.
3. Service Catalog initiates an orphan mitigation, and deprovisions a healthy OSB instance as a result.

We need a way to disable orphan mitigation for certain scope, options are:
- Per instance: `OrphanMitigationDisabled` flag in ServiceInstance spec
- Per broker: flag in ClusterServiceBroker spec
- Globally: flag in Service Catalog controller-manager

Feel free to suggest alternative options.

**Comment by nilebox** [comment]
Given that we need to disable orphan mitigation for **migrated instances only**, it should probably be a flag in the ServiceInstanceSpec.

**Comment by ash2k** [comment]
> OTOH, some brokers may not need orphan mitigation at all, so it also makes sense to have this flag in ClusterServiceBroker.

A better option is to let the broker return this information as part of `/catalog` response (per class?).

**Comment by nilebox** [comment]
> A better option is to let the broker return this information as part of /catalog response (per class?).

Possibly, but it will take more time and effort (so it would be nice to support setting the flag explicitly until a new OSB version is released with this new field).

Also, even if the broker does need orphan mitigation, there is still a migration use case when orphan mitigation is unwanted.

**Comment by duglin** [comment]
Can’t you use a UPS instead?

**Comment by nilebox** [comment]
@duglin No, we want instances to be managed via Service Catalog and actual brokers the same way as the ones provisioned via Service Catalog, i.e. it's a one-time migration from our internal system to Service Catalog. After migration we will allow updating parameters, deprovisioning, creating new bindings etc.

**Comment by duglin** [comment]
I believe MSFT has a similar use case and are working on a UPS that does all of the normal management stuff, but skips the provision step.  @jeremyrickard do I have that right?

**Comment by nilebox** [comment]
@duglin I'm not sure how broker can fix the problem. Even if provisioning is a no-op on the broker side, it could still fail with some temporary 5xx error, or request timeout. In that case, Service Catalog will start an orphan mitigation, which on the broker side looks like a normal deprovisioning request.

So I believe this issue can only explicitly be solved by Service Catalog, not by the broker.

@jeremyrickard I'm curious to learn more about MSFT use case though.

**Comment by duglin** [comment]
Yeah, that's true - if I'm understanding the flow properly. One thing some of us have been advocating is that UPS not be implemented as an add-on Broker. Rather, they be something that is well-known to the controller - that would avoid this 5xx situation. And it seems to me that if we went down that path then we could support your case as well as the normal UPS case more easily with a lot less overhead.

**Comment by nilebox** [comment]
@duglin I've created a separate issue to discuss proper support for migration in Service Catalog #2250

**Comment by duglin** [comment]
Does that mean we can close this one?

**Comment by nilebox** [comment]
Probably yes, it is a subset of #2250.
