### ISSUE TITLE
Support namespace scoped plans in svcat

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#2243]
Currently `svcat get plans` is written to work only with cluster-scoped service plans. Now that we support namespace-scoped broker resources, this command should be extended to understand both types `ClusterServicePlan` and `ServicePlan`. See #2152 as a reference, where we implemented this for `svcat get classes`.

```
$ svcat get classes [--scope cluster|namespace|all] [--namespace NS] [--all-namespaces true|false]
```

* `--scope` is a boolean flag that needs to be added to this command following the Scoped command interface.
* `svcat get plans --cluster` should retrieve a ClusterServicePlans 
* `svcat get plans --namespace|--all-namespaces` should retrieve a ServiceClass in the appropriate namespace. You should be able to modify the call to `c.App.RetrievePlans` to accept a scope filter with the cluster and namespace flags set. The CLI should not be doing the logic of figuring out how to split out those calls itself, and should delegate that to the svcat package.
* The ClusterServicePlan and ServicePlan structs in the pkg/apis/servicecatalog/v1beta1 package will need to be updated to implement a new interface (that you will create) called `Plan`. See the `Class` interface as an example.

**Comment by artmello** [comment]
I would like to give a try on this, if not already taken by someone
