### ISSUE TITLE
Remove alpha-feature flag for Namespaced Brokers

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-incubator/service-catalog#2244]
Is this ready all the way through? Can the feature flag be removed?

@eriknelson thoughts?

**Comment by eriknelson** [comment]
@jberkhahn I'd consider it feature complete, and we've had a few people experimenting with success. I don't have any concrete reason to keep it behind the gate, except that it simply hasn't had a ton of usage in the wild yet.

**Comment by MHBauer** [comment]
an alternative is to change the default to enabled for a few releases. 

not sure what happens if you try and flag a a flag that doesn't exist. might cause problems for those not using the helm charts.

**Comment by jboyd01** [comment]
>not sure what happens if you try and flag a a flag that doesn't exist. might cause problems for those not using the helm charts.

I'm pretty certain the server will bomb out with unrecognized flag error.   I think we just toggle it to default to true for now.  This was done with Originating Identity:  https://github.com/kubernetes-incubator/service-catalog/blob/f6f0e41fae6c4f1bdc5c507942ee7f1719555a19/pkg/features/features.go#L83-L90

**Comment by eriknelson** [comment]
Sounds reasonable to me.
