### ISSUE TITLE
RelistDuration is incorrectly defaulted in the broker's controller

### ISSUE THREAD

**Issue by eriknelson** [kubernetes-incubator/service-catalog#2251]
# Bug Report 

**What happened**:
It was brought to my attention that the `relistDuration` field is missing from a `kubectl edit` command if it hasn't been explicitly set, which surprised me as I expected that to be handled by the defaults. In fact, we're using an internal default value in the controller if the `RelistDuration` field is nil: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_clusterservicebroker.go#L127

This is an issue with both cluster and ns brokers.

**What you expected to happen**:
`RelistDuration` should always be present if `RelistBehavior` is set to `ServiceBrokerRelistBehaviorDuration` and set to a default value in the defaults. Additionally, it should be validated, and the tests need to be updated to confirm it.

**How to reproduce it (as minimally and precisely as possible)**:
Create a broker without the `relistDuration` field explicitly set. `kubectl edit clusterservicebroker <broker>`, relistDuration is missing.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- service-catalog version: master

**Comment by MHBauer** [comment]
> RelistDuration should always be present if RelistBehavior is set to ServiceBrokerRelistBehaviorDuration and set to a default value in the defaults. 

Per the [original description of the feature](https://github.com/kubernetes-incubator/service-catalog/issues/1086), duration is optional and defaults.

Working as designed.
/close
