### ISSUE TITLE
Add a dashboardURL row to svcat describe instances

### ISSUE THREAD

**Issue by robertscherbarth** [kubernetes-incubator/service-catalog#2257]
Hi, 

i want to offer the user of a service broker the possibility to get a monitoring url via svcat. Something like this:

```
  Name:            example-starter-pack-service
  Namespace:       test-ns
  Status:          ready
  DashboardURL:    grafana.example.com
  Class:           example-starter-pack-service
  Plan:            default

Parameters:
  param-1: value-1
  param-2: value-2

Bindings:
No bindings defined 
```

I have already codet it in a feature branch (https://github.com/robertscherbarth/service-catalog/tree/add-dashboard-url-svcat). I am not sure. Can i open an pull request without a issue?

**Comment by MHBauer** [comment]
Didn't look at the code.

A PR could be the way to go.

We've got the [devguide](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/devguide.md) for some details on contributing.

The biggest thing is probably the CLA if you haven't signed it.

/assign @carolynvs @jber
