### ISSUE TITLE
@mhbauer items needing new owner

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#2267]
Would be nice to find an owner of these things before end of August 2018. (I'm not going to go poof and turn back into a pumpkin, but let's not drag it out.)

 - [x] weekly release - @jberkhahn 
 - [x] CI/CD push forward, move last bit of tests and release to prow ( ? @jeremyrickard ? has shown interest) kubernetes/test-infra/issues/8291
    - should be someone with membership in k/k and [add as OWNER](https://github.com/kubernetes/test-infra/pull/8718/files#diff-a3659c31e170bf6052f013bbe678b8de) 
    - run e2e tests in prow
    - push charts 
    - push images
    - push svcat binaries
 - [ ] record sig meetings - @carolynvs to discover and document
   - [x] zoom account with record permissions - @pmorie to share with lastpass
   - [ ] youtube upload to sig-service-catalog playlist - @pmorie to enable youtube account
 - [ ] APIServer/rest/storage questions
 - [ ] build/CI/makefile questions

**Comment by jeremyrickard** [comment]
#dibs on CI/CD stuff

**Comment by MHBauer** [comment]
meeting scheduled for Mon 08/13/2018 10:00AM Pacific to discuss

**Comment by MHBauer** [comment]
Aug 20 Meeting opened by @carolynvs 👍

**Comment by MHBauer** [comment]
I think we're done here. Let me know if there is need for uploading anything to youtube.
/close
