### ISSUE TITLE
Add command to svcat to abandon instances

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#2268]
Sometimes a service instance can become "stuck", and we want to just give up on it and make it go away in Kubernetes so that we don't see it anymore.

There are a couple ways this could happen, and I'm happy to go into more detail if whoever picks up this issue needs it. The short answer is that it can happen due to bugs, misbehaved brokers, messed up developer environments, or cases where you want to disconnect k8s from a service provisioned by the broker, even though it's still being used elsewhere (so the broker isn't letting you delete it).

This feature is to add the `--abandon` boolean flag to the [svcat unbind](https://github.com/kubernetes-incubator/service-catalog/blob/master/cmd/svcat/binding/unbind_cmd.go) and [svcat deprovision](https://github.com/kubernetes-incubator/service-catalog/blob/master/cmd/svcat/instance/deprovision_cmd.go) commands. When that flag is present, before deleting the instance, the cli will first confirm the action and then remove ALL finalizers from the service instance so that it is deleted immediately, without giving service catalog a chance to try to delete it with the broker.

It also adds an optional `-y` flag that skips the interactive prompt/confirmation.

```
$ svcat unbind --abandon INSTANCE_NAME
This action is not reversible and may cause you to be charged for the broker resources that are abandoned.
Are you sure? [y|N]

deleted BINDING_NAME(S)
deleted INSTANCE_NAME

$ svcat deprovision --abandon INSTANCE_NAME
This action is not reversible and may cause you to be charged for the broker resources that are abandoned.
Are you sure? [y|N]

deleted INSTANCE_NAME

$ svcat help deprovision
Deletes an instance of a service

Usage:
  svcat deprovision NAME [flags]

Examples:

  svcat deprovision wordpress-mysql-instance


Flags:
      --abandon bool    Forcefully and immediately delete the resource from Service Catalog ONLY, potentially abandoning any broker resources that you may continue to be charged for.
      --yes,-y bool         Automatic yes to prompts. Assume "yes" as answer to all prompts and run non-interactively.
```

* See the original issue for context and the discussion that lead up to this issue, #1723 
* I wrote an [example plugin that does this for pods](https://github.com/carolynvs/kubectl-kill-plugin/blob/7fa39d6bf5620e7bcb590611f6610e594ff5920d/main.go#L57-L67) that you can use as a reference.
* Add documentation for the feature to the [cli page on our website](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/cli.md)

**Comment by nilebox** [comment]
> the cli will first confirm the action and then remove ALL finalizers from the service instance so that it is deleted immediately, without giving service catalog a chance to try to delete it with the broker.

AFAIK DELETE request doesn't have a request body. If you DELETE first, and then send PUT/PATCH, then in between those two requests Service Catalog *will* get a chance to deprovision (especially given the queue/cache)? So the correct order would probably be to remove finalizer first, and only after that send a DELETE?

Also, removing ALL finalizers sounds wrong to me - svcat should only remove `kubernetes/service-catalog` finalizer, other custom finalizers should be managed by appropriate controllers, since we don't know their purpose and side effects.

**Comment by amckague** [comment]
Similar to the notion of exporting an instance here https://github.com/kubernetes-incubator/service-catalog/issues/2250 just a different use case.

**Comment by amckague** [comment]
Similar to the notion of exporting an instance here https://github.com/kubernetes-incubator/service-catalog/issues/2250 just a different use case for "don't actually attempt deprovisioning".

**Comment by jboyd01** [comment]
The abandon should probably also support Bindings and Brokers.  See issue https://github.com/kubernetes-incubator/service-catalog/issues/2466

**Comment by taragu** [comment]
@carolynvs I'd like to work on this issue
/assign
