### ISSUE TITLE
Document how to become a member/reviewer of our project

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#2288]
* We follow the [K8s membership guidelines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) but request to join the `kubernetes-incubator` org.
* Good people to ask to be your sponsor are:
  * @carolynvs
  * @pmorie 
* Good people to help mentor if you aren't sure how to get established are:
  * @carolynvs
  * @jeremyrickard

**Comment by MHBauer** [comment]
Sounds like a good thing to put in the dev-guide. The process is now to create an issue on a repo, and not to send an email.

**Comment by carolynvs** [comment]
Doh! Thanks for the heads up that I'm out-of-date. 😊

**Comment by carolynvs** [comment]
#dibs
