### ISSUE TITLE
Add support for synchronising namespaced brokers via svcat

### ISSUE THREAD

**Issue by aszecowka** [kubernetes-incubator/service-catalog#2291]
Currently, in svcat (v0.1.29) it is possible to synchronize only ClusterServiceBrokers.
`svcat sync broker <broker-name>`
This command should also support namespaced brokers. To be consistent with other commands, `sync` should accept flag `n` to specify namespace.

**Comment by jichenjc** [comment]
If no one is doing this, I will work on it

**Comment by carolynvs** [comment]
@jichenjc Great!
