### ISSUE TITLE
 svcat register  doesn't support namespace

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-incubator/service-catalog#2292]
looks like even if -n give , the code still don't honor the namesapce ? 

bin/svcat/svcat   register mysqlbroker1 --url http://mysqlbroker.com -n test-ns

      NAME       NAMESPACE                              URL                                     STATUS
+--------------+-----------+-----------------------------------------------------------+----------------------+
  mysqlbroker                http://mysqlbroker.com                                      ErrorFetchingCatalog
  mysqlbroker1               http://mysqlbroker.com                                      ErrorFetchingCatalog
  nasty-broker               http://nasty-service.default.svc.cluster.local              ErrorFetchingCatalog
  ups-broker                 http://ups-broker-ups-broker.ups-broker.svc.cluster.local   Ready

pkg/svcat/service-catalog/broker.go has following code ,seems any way it will create cluster wide service broker? 

func (sdk *SDK) Register(brokerName string, url string, opts *RegisterOptions) (*v1beta1.ClusterServiceBroker, error) {
        var err error
        var caBytes []byte
        if opts.CAFile != "" {
                caBytes, err = ioutil.ReadFile(opts.CAFile)
                if err != nil {
                        return nil, fmt.Errorf("Error opening CA file: %v", err.Error())
                }

        }
        request := &v1beta1.ClusterServiceBroker{

**Comment by carolynvs** [comment]
This was fixed in #2345 .
