### ISSUE TITLE
Relist behaviour differs between ServiceBroker and ClusterServiceBroker

### ISSUE THREAD

**Issue by aszecowka** [kubernetes-incubator/service-catalog#2306]
# Bug Report 

**What happened**:
For controller manager I set `broker-relist-interval` to 1minute.
My definitions for ClusterServiceBroker and ServiceBroker are simple, I specify only broker URL. In logs I see the following error:
```
E0828 07:11:05.871077       1 controller_servicebroker.go:117] ServiceBroker "default/ns-broker" v37: Unable to process because RelistBehavior is set to Duration with a nil RelistDuration value
```
(every 5 minute which is also strange).
In the case of ClusterServiceBroker there is the following line:
```
duration := defaultRelistInterval
```
 (https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_clusterservicebroker.go#L127)
and it is prepopulated from `ControllerManagerConfiguration.ServiceBrokerRelistInterval`.
In case of ServiceBroker this line is missing. Is it on purpose?
As a result ServiceBrokers probably won't be relisted at all.

**What you expected to happen**:
ServiceBroker and ClusterServiceBroker relist behaviour is the same

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- service-catalog version: 0.1.30
- Cloud provider or hardware configuration: minikube
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
helm install svc-cat/catalog  --name catalog --namespace catalog
- Are you trying to use ALPHA features? Did you enable them?

**Comment by MHBauer** [comment]
I missed it in #2125.
Needs a similar change as in https://github.com/kubernetes-incubator/service-catalog/commit/ea84fa59baf8899b85f76354804fc98f9894b220#diff-1aa1085b3dd6f459f3f1e5d2ec2ec35b
/help-wanted
