### ISSUE TITLE
Improve namespaced service broker docs

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/service-catalog#2332]
We have documentation for namespaced service brokers at https://svc-cat.io/docs/namespaced-broker-resources/

It would be very helpful if someone could review the original proposal and make sure that we aren't missing any documentation from there.

Needs Docs:
- [ ] Update documentation for svcat to include the namespaced broker functionality, columns, etc.
- TBD by whoever takes this issue on.

**Comment by jeremyrickard** [comment]
Seems like a pretty big one here is that provision doesn't work on namespaced class and plans?

```

**Comment by jboyd01** [comment]
We've got several outstanding issues with namespaced resources:  https://github.com/kubernetes-incubator/service-catalog/milestone/47  which includes [enhance `svcat provision` to support namespace scoped resources](https://github.com/kubernetes-incubator/service-catalog/issues/2371)

**Comment by jberkhahn** [comment]
think we're happy with the for now
