### ISSUE TITLE
enhance `svcat provision` to support namespace scoped resources

### ISSUE THREAD

**Issue by jboyd01** [kubernetes-incubator/service-catalog#2371]
`svcat provision` can only provision cluster scoped resources.  It needs functionality to enable a user to specify using a NS scoped Broker's class & plans for provisioning.   It maybe as simple as adding a --scope parameter.

**Comment by shubheksha** [comment]
I can pick this up!

**Comment by jberkhahn** [comment]
Was talking with Carolyn about what this behavior should look like. I think this might be a good point to add a little bit more magic than we normally do. Maybe query the system state and only require a --scope flag if there are multiple classes with the requested name? something like:

```console
$ svcat provision foo --class mysql --plan 10mb // there's both a cluster and namespaced class mysql
Error: multiple mysql service classes found, please specifiy namespace or cluster scope
$ svcat provision foo --class mysql --plan 10mb --scope namespaced
```
There's still a problem that it's technically possible for multiple cluster classes or namespaced classes to have the same external name, but I'm not sure how to fix that.

**Comment by jberkhahn** [comment]
One idea is to maybe skip scope entirely, and if we find multiple classes with the same ExternalName, ask the users to specify the exact UID of which they want.

**Comment by carolynvs** [comment]
In our SIG meeting today we discussed this issue and settled on:

* Fix --uuid to reflect that it is the k8s name
* When more than one class/plan matches by name, print the matching results with the k8s name and prompt the user to pick one and use the specific k8s name instead of the external name

**Comment by jberkhahn** [comment]
this is currently under active work
