### ISSUE TITLE
Catalog Controller Manager Pods keep crashing

### ISSUE THREAD

**Issue by jldeen** [kubernetes-incubator/service-catalog#2380]
# Bug Report 

**What happened**:

Catalog Controller Manager Pods keep crashing

**What you expected to happen**:

For the pods to only crash or restart on failure

**How to reproduce it (as minimally and precisely as possible)**:

Install the chart as outlined, watch crashes occur

**Anything else we need to know?**:

Currently tested on 3 different brand new clusters version 1.11.2 on AKS, same issue persists.

Also updated the chart locally to allow for replicas of both apiServer and controllerManager, controllermanager pods (3 replicas) all still crash intermittently with "crashLoopBackoff"

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- service-catalog version: 0.1.33
- Cloud provider or hardware configuration: AKS
- Do you have api aggregation enabled? I believe so?
  - Do you see the configmap in kube-system? Yes, I even see a config map for each time I run "helm upgrade --intall"
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
Yes:
`requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
requestheader-group-headers: '["X-Remote-Group"]'
requestheader-username-headers: '["X-Remote-User"]'`
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
Yes. I ran:
`helm upgrade --install catalog svc-cat/catalog --namespace catalog --set apiserver.storage.etcd.persistence.enabled=true --wait`
- Are you trying to use ALPHA features? Did you enable them?
No.

**Comment by jboyd01** [comment]
I've seen this as well, I figured it was only me and an underpowered machine.  I think the liveness probes are triggering it, perhaps we need to loosen the timeoutSeconds.

**Comment by jldeen** [comment]
> I see this regularly on AKS and it seems to relate to the heath checks. When I disable the health checks on AKS, I have no issues. Jessica could you you try to diable the health checks?

Yes, I have confirmed if you disable the health checks the problem is resolved. I have been playing with tweaking the health checks, but I wonder if you feel this problem is specific to AKS?

**Comment by carolynvs** [comment]
@jldeen I believe that this problem is unique to the default service catalog configuration (super chatty) and a problem with AKS's routing that should be resolved over the next few weeks. I've seen it happen on gke as well but it wasn't easily reproducible.

I'll update the install instructions for service catalog on AKS and report back.

**Comment by jldeen** [comment]
@carolynvs Thank you and please let me know if I should go back to the AKS engineering team with a bug/patch to improve communication. FWIW I have noticed some intense timeouts overall with service catalog and OSBA on AKS. In fact, I filed a bug [here](https://github.com/Azure/open-service-broker-azure/issues/595) as I don't find it currently stable if one wishes to use it in a prod scenario. I wasn't sure if this was an AKS explicit problem or SC prob, or if all of this is related.
