### ISSUE TITLE
Running `dep ensure -v` results in an error

### ISSUE THREAD

**Issue by shubheksha** [kubernetes-incubator/service-catalog#2386]
# Bug Report 

**What happened**:
Running `dep ensure -v` results in some deps not being installed and gives the following error (screenshot):
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/7693422/46503904-57960100-c7fa-11e8-9f0b-8761aa8b767c.png">

**What you expected to happen**:
All deps should be installed correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Run `dep ensure -v` on the current master

**Comment by carolynvs** [comment]
From the error message, you don't have `hg` (Mercurial) installed. Dep using git and hg directly, and since one of our dependencies is a mercurial repo, you will need it installed to work with dep on our repo.

**Comment by shubheksha** [comment]
Thanks, @carolynvs! Can't believe I missed that :|
