### ISSUE TITLE
Chart `v1.35` installation failing with spec validation error for field `minReadySeconds`

### ISSUE THREAD

**Issue by ashokkkannan** [kubernetes-incubator/service-catalog#2390]
# Bug Report 

**What happened**:
The catalog chart version v1.35 installation fails with the following error
```
Error: error validating "": error validating data: found invalid field minReadySeconds for v1beta1.DeploymentStrategy
```
**What you expected to happen**:
The chart installation to go through fine
**How to reproduce it (as minimally and precisely as possible)**:
```
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
```
```
helm install svc-cat/catalog --name catalog-sample
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.1-2+e49fe6296d12ea", GitCommit:"e49fe6296d12ea823430bb7bda457d1201b17277", GitTreeState:"clean", BuildDate:"2018-07-24T14:24:53Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- service-catalog version: ```v1.35```
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
    No
- Are you trying to use ALPHA features? Did you enable them? No
https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.35/charts/catalog/templates/controller-manager-deployment.yaml

The issue seems to be with the addition of `minReadySeconds` done as aprt of v1.35 release. According to the [API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#deploymentspec-v1beta1-extensions) it should be under spec and not under the `strategy`.

**Comment by carolynvs** [comment]
@ashokkkannan Thank you for reporting this and explaining the fix! 👍
