### ISSUE TITLE
Validation of ClusterServicePlan Name or UID fails when it contains "/"

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-incubator/service-catalog#2427]
# Bug Report 
We recently changed the validations of class/plan names and UIDs to make them more permissive per upcoming changes to the OSB API spec to make it more similar to Cloud Foundry. However, we're still failing validation when the plan name/id contains a "/". Like so:

```
I1019 23:32:54.653863       1 request.go:942] Response Body: {
  "kind": "Event",
  "apiVersion": "v1",
  "metadata": {
    "name": "fake-broker.155f2683bf28cefa",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/events/fake-broker.155f2683bf28cefa",
    "uid": "3bd13bc4-d3f7-11e8-bfab-08002721ca17",
    "resourceVersion": "9796",
    "creationTimestamp": "2018-10-19T23:32:24Z"
  },
  "involvedObject": {
    "kind": "ClusterServiceBroker",
    "name": "fake-broker",
    "uid": "3bae66c8-d3f7-11e8-80cb-0242ac110005",
    "apiVersion": "servicecatalog.k8s.io/v1beta1",
    "resourceVersion": "3"
  },
  "reason": "ErrorSyncingCatalog",
  "message": "Error reconciling ClusterServicePlan (K8S: \"08de49c7/62b3-4e0f/b442/1ed19b644bca\" ExternalName: \"fake/plan\"): ClusterServicePlan.servicecatalog.k8s.io \"08de49c7/62b3-4e0f/b442/1ed19b644bca\" is invalid: metadata.name: Invalid value: \"08de49c7/62b3-4e0f/b442/1ed19b644bca\": may not contain '/'",
  "source": {
    "component": "service-catalog-controller-manager"
  },
  "firstTimestamp": "2018-10-19T23:32:24Z",
  "lastTimestamp": "2018-10-19T23:32:54Z",
  "count": 6,
  "type": "Warning",
  "eventTime": null,
  "reportingComponent": "",
  "reportingInstance": ""
}
```
I tracked this down to [this line](https://github.com/kubernetes-incubator/service-catalog/blob/master/vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L158), which should only be passing errors up from the passed in validation function, called 'nameFn'. Except as near as I can tell, that is the function passed in [here](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/validation/serviceplan.go#L57), which is the function that we loosened up the requirements in [here](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/validation/serviceplan.go#L33).

So, I'm not really sure where this validation is actually coming from. This is also likely a problem with Class names/UIDs, but I have not reproduced it there yet myself.

**Comment by duglin** [comment]
@jberkhahn any update on this?

**Comment by duglin** [comment]
ping @fmui just so you can track this

**Comment by jberkhahn** [comment]
@duglin 
no, I haven't done any further investigation. I thikn @jboyd01 said he was going to take a look at this?

**Comment by MHBauer** [comment]
The specific error is `metadata.name: Invalid value: \"08de49c7/62b3-4e0f/b442/1ed19b644bca\": may not contain '/'"`
Which is an upstream kube apiserver thing, and you can't change it.

**Comment by jberkhahn** [comment]
this was fixed
