### ISSUE TITLE
`svcat describe` should support namespaced resources

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes-incubator/service-catalog#2451]
Seems we never created an issue for this. I imagine we could end up using whatever desired behavior we come up with for #2371

**Comment by jberkhahn** [comment]
Hey there. I've been working on the related issue for provision, and I would like if we could make a consistent UX for these commands. Something like 'svcat describe class FOOBAR' finds and describes a class foobar in the current context, regardless of whether it's a clusterserviceclass or namespaced serviceclass, and if it finds more than 1 of those things with a matching name, it errors out to the user with "please specifiy an exact class with --kube-name".

Does that sound good?

**Comment by artmello** [comment]
Hey, thanks for the heads up. Sure, makes totally sense have a consistent UX, I will follow the same approach.
