### ISSUE TITLE
ErrorWithOriginatingIdentityReason doesn't follow convention since it includes spaces

### ISSUE THREAD

**Issue by luksa** [kubernetes-incubator/service-catalog#2530]
# Bug Report 

All ServiceCatalog condition reasons are written in camel case, without spaces. But `errorwithOriginatingIdentity` contains spaces: 

https://github.com/kubernetes-incubator/service-catalog/blob/37b874716ad709a175e426f5f5638322a600849f/pkg/controller/controller_instance.go#L64

The constant is used as a condition reason here: https://github.com/kubernetes-incubator/service-catalog/blob/37b874716ad709a175e426f5f5638322a600849f/pkg/controller/controller_instance.go#L2185

We should remove those spaces.

**Comment by wayilau** [comment]
#dibs

**Comment by imcsk8** [comment]
@kubernetes-incubator/maintainers-service-catalog Is it okay if I take this?
