### ISSUE TITLE
Trouble getting setup on the walkthrough instructions

### ISSUE THREAD

**Issue by hev** [kubernetes-incubator/service-catalog#2535]
# Bug Report 
Following the [walkthrough](https://svc-cat.io/docs/walkthrough/) I have gotten stuck after deploying the ups-broker. 

**What happened**:
I setup helm, deployed the chart for the ups-broker using the included values.yml file. I went to the next set of instructions for `svcat get brokers` and started getting errors in the response.

```
hev@Adams-MacBook-Pro-2 ~ $ svcat get brokers
Error: unable to list cluster-scoped brokers (the server could not find the requested resource (get clusterservicebrokers.servicecatalog.k8s.io))
hev@Adams-MacBook-Pro-2 ~ $ svcat describe broker ups-broker
Error: unable to get broker 'ups-broker': the server could not find the requested resource (get clusterservicebrokers.servicecatalog.k8s.io ups-broker)
```

Additionally when I try to follow the step to create ClusterServiceBroker I also get an error. 
```
hev@Adams-MacBook-Pro-2 service-catalog (master)$ kubectl create -f contrib/examples/walkthrough/ups-clusterservicebroker.yaml
error: unable to recognize "contrib/examples/walkthrough/ups-clusterservicebroker.yaml": no matches for kind "ClusterServiceBroker" in version "servicecatalog.k8s.io/v1beta1"
```

**What you expected to happen**:
After deploying the helm chart for the ups-broker I was expecting to be able to create the ClusterServiceBroker.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster (I used GKE)
1. Deploy ups-broker using helm
1. Run the commands above. 

**Anything else we need to know?**:
I am just messing around. 

**Environment**:
- Kubernetes version (use `kubectl version`): `1.10.9-gke.5`
- service-catalog version:I just checked out `master`
- Cloud provider or hardware configuration: GKE
- Do you have api aggregation enabled? no
  - Do you see the configmap in kube-system? yes (`ups-broker.v1`)
  - Does it have all the necessary fields? I dunno
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values? I just used the chart provided in the repo with values.yml. No special values. 
- Are you trying to use ALPHA features? Did you enable them? No

**Comment by jberkhahn** [comment]
you need to install service catalog first. You're getting that error because you haven't installed service catalog, so the API server doesn't recognize the clusterservicebroker type.

**Comment by klaudiagrz** [comment]
Hello @jberkhahn 

It seems that I have the same problem with the ups-broker. I have the Service Catalog installed and I have such an error:
![screen](https://user-images.githubusercontent.com/35192450/53252572-859fb300-36bf-11e9-828a-63a33efab15b.png)

**Comment by jberkhahn** [comment]
@klaudiagrz ups broker is currently broken. You can either point your helm chart at the 0.1.39 version, or wait for the next release.

**Comment by klaudiagrz** [comment]
@jberkhahn Thank you for your reply :)

**Comment by hev** [comment]
I had mis-interpreted the instructions and have since figure this out. Closing this item.
