### ISSUE TITLE
test-integration failed

### ISSUE THREAD

**Issue by wayilau** [kubernetes-incubator/service-catalog#2538]
make test-integration falied. 
log:
error: error when creating "contrib/examples/apiserver/clusterserviceclass.yaml": Post https://localhost:32785/apis/servicecatalog.k8s.io/v1beta1/clusterserviceclasses: dial tcp 183.207.215.240:32785: i/o timeout

**Comment by jberkhahn** [comment]
this looks like just a flake, your apiserver not coming up quick enough
