### ISSUE TITLE
Version 0.1.40 not available in svc-cat helm chart repo

### ISSUE THREAD

**Issue by Tarkleigh** [kubernetes-incubator/service-catalog#2569]
# Bug Report 

**What happened**:
I tried to get version 0.1.40 version of service catalog from the official (?) helm chart repo (https://svc-catalog-charts.storage.googleapis.com) but it does not seem to be there. The newest version are 0.1.41 and 0.1.40
**What you expected to happen**:
I expected it to be there
**How to reproduce it (as minimally and precisely as possible)**:
Have a look at the helm chart repo (https://svc-catalog-charts.storage.googleapis.com) or use helm search for "catalog"

**Comment by jberkhahn** [comment]
There was an error in our build pipeline when we published 0.1.40. We fixed the images on quay but I guess we forgot to manually update the helm repo. I'll take a look at this.

**Comment by jberkhahn** [comment]
This should be fixed now, we had to manually publish the helm charts. Let us know if anything else needs to be done.
