### ISSUE TITLE
Provisioning error "no OSB client created"

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kubernetes-incubator/service-catalog#2576]
# Bug Report 

**What happened**:
The OSB operation, for example provisioning, fails with an error like:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Install any broker, then restart the controller-manager. Then any operation with OSB client fails with an error like: "The instance references a broker "hb-azure-service-broker-default-8d3f0e68-4018-11e9-9d-azure-ser" which has no OSB client created"

**Anything else we need to know?**:
The following condition could break the method processing:
https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_clusterservicebroker.go#L165

**Environment**:
- service-catalog version: 0.1.41

**Comment by jboyd01** [comment]
ouch, hard to believe this slipped through and hasn't been reported before.
