### ISSUE TITLE
Cannot use service-catalog chart with `helm template`

### ISSUE THREAD

**Issue by gree-gorey** [kubernetes-incubator/service-catalog#2592]
# Bug Report 

**What happened**:
When use Helm without Tiller, one can do `helm fetch --untar` and `helm template . | kubectl apply -f -`. But using this with service-catalog chart results in invalid manifests rejected by `kubectl`.

**What you expected to happen**:
One can use this chart with `helm template`

**How to reproduce it (as minimally and precisely as possible)**:
```
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
helm fetch --untar svc-cat/catalog
cd catalog/
helm template . | kubectl apply -f -
```

**Anything else we need to know?**:
https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/apiregistration.yaml#L7 here there is `if .Capabilities.APIVersions.Has` which needs a server to get info, meaning that it won't work locally. Maybe need to provide at least default values.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- service-catalog version: 0.1.42
- Cloud provider or hardware configuration: Azure AKS
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by baikai** [comment]
In service-catalog helm chart, the resources(like deploymemts, services...) name pattern is ${release name}-catalog-*, the release name will be passed by helm install, for example, create release by command "helm  install svc-cat/catalog --name catalog --namespace catalog", it means the release name is catalog, then the apiserver service name will be catalog-catalog-apiserver. (If your not specify release name by cmd, helm will use a random name like "wishing-duck").

But when user try to deploy service-catalog charts by cmd "helm template .|kubectl apply -f -", there's no way to specify release name here and helm will use RELEASE-NAME-catalog-* as defaut resources name, unfortunately such name are invalid.  kubectl apply -f will throw errors like below:
"Error from server (Invalid): error when creating "STDIN": Service "RELEASE-NAME-catalog-apiserver" is invalid: metadata.name: Invalid value: "RELEASE-NAME-catalog-apiserver": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
Error from server (Invalid): error when creating "STDIN": Deployment.apps "RELEASE-NAME-catalog-apiserver" is invalid: metadata.name: Invalid value: "RELEASE-NAME-catalog-apiserver": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
Error from server (Invalid): error when creating "STDIN": Deployment.apps "RELEASE-NAME-catalog-controller-manager" is invalid: metadata.name: Invalid value: "RELEASE-NAME-catalog-controller-manager": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
error validating "STDIN": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false"

**Comment by gree-gorey** [comment]
> But when user try to deploy service-catalog charts by cmd "helm template .|kubectl apply -f -", there's no way to specify release name here

@baikai it's actually not right. You **can**  (and usually should) specify release name by passing `--name` to `template` command like this:
```console
$ helm template --name myrelease --namespace myns . | head
---
# Source: catalog/templates/apiserver-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: myrelease-catalog-apiserver
```

And then everything is working well, except for the thing with `if .Capabilities.APIVersions.Has` which does require an API call to the server

**Comment by baikai** [comment]
@gree-gorey sorry, I'm not expert for helm, and thanks for your comments.
After use option “--name” to pass release name,  resources name works well, but apiVersion are missing:
[root@host-10-1-236-142 catalog]# helm template --name catalog --namespace catalog .|kubectl apply -f -
service/catalog-catalog-apiserver unchanged
deployment.extensions/catalog-catalog-apiserver configured
deployment.extensions/catalog-catalog-controller-manager configured
error: error validating "STDIN": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false
