### ISSUE TITLE
RBAS null apiVersion

### ISSUE THREAD

**Issue by kramvan1** [kubernetes-incubator/service-catalog#2602]
# Bug Report 

**What happened**:

Output from rbac templates is missing apiVersion which causes failures in other tooling (lint, kustomize)
```
# Source: catalog/templates/rbac.yaml

apiVersion: v1
kind: List
items:

### API Server ###

# TODO: if this is just for namespace lifecycle admission, move to a generic role
# the role for the apiserver 
- apiVersion: 
```
The template as these in a list, but no version is being put in the output,
```
- apiVersion: {{template "rbacApiVersion" . }}
```

**What you expected to happen**:

All resources have a valid apiVersion.

**How to reproduce it (as minimally and precisely as possible)**:

helm template service-catalog-${SC_VERSION}/charts/catalog --name catalog --namespace test

Wanted Solution:
- Remove list, it's not needed here.
- Add apiVersion: v1 to each resource.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- service-catalog version:
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by MHBauer** [comment]
dup of #2604 which has root cause as helm template cmd does not support this helm/helm#3377
