### ISSUE TITLE
ServiceAccount template wrong indenting and unneeded list

### ISSUE THREAD

**Issue by kramvan1** [kubernetes-incubator/service-catalog#2603]
# Bug Report 

**What happened**:

https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/serviceaccounts.yaml#L5-L13
The above template has the wrong indenting for a list.
The list is not needed here and should be removed, using `---` instead.

**What you expected to happen**:

The list would be removed for formatted properly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- service-catalog version:
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by MHBauer** [comment]
Indenting looks fine to me:
```
➜  test cat sa.yaml
apiVersion: v1
kind: List
items:
  # The SA for the apiserver
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: svc-cat-apiserver
  # The SA for the controller-manager
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: svc-cat-cm
➜  test kubectl create -f sa.yaml
serviceaccount/svc-cat-apiserver created
serviceaccount/svc-cat-cm created
➜  test kubectl get serviceaccount
NAME                SECRETS   AGE
default             1         47d
svc-cat-apiserver   1         36s
svc-cat-cm          1         36s
```

Please provide guidance on:
` The list is not needed here and should be removed, using --- instead.`

**Comment by kramvan1** [comment]
@MHBauer can we at least get rid of this unneeded list?    And technically the list indent is incorrect from the spec, but since there was an early kubectl bug (cant find the ref right now), it's allowed as legacy support, which will someday be removed.

**Comment by kramvan1** [comment]
Can we at least get rid of this unneeded list? And technically the list indent is incorrect from the spec, but since there was an early kubectl bug (cant find the ref right now), it's allowed as legacy support, which will someday be removed.
 
Mark VanderwielIBM Watson and Cloud Platform - IBM Cloud Kubernetes ServiceRochester, MN==================================================================Internet Address: vanderwl@us.ibm.com
 
 
----- Original message -----From: Morgan Bauer <notifications@github.com>To: kubernetes-incubator/service-catalog <service-catalog@noreply.github.com>Cc: Mark Vanderwiel <vanderwl@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [kubernetes-incubator/service-catalog] ServiceAccount template wrong indenting and unneeded list (#2603)Date: Wed, Apr 10, 2019 2:36 PM 
Indenting looks fine to me:
➜  test cat sa.yamlapiVersion: v1kind: Listitems:  # The SA for the apiserver  - apiVersion: v1    kind: ServiceAccount    metadata:      name: svc-cat-apiserver  # The SA for the controller-manager  - apiVersion: v1    kind: ServiceAccount    metadata:      name: svc-cat-cm➜  test kubectl create -f sa.yamlserviceaccount/svc-cat-apiserver createdserviceaccount/svc-cat-cm created➜  test kubectl get serviceaccountNAME                SECRETS   AGEdefault             1         47dsvc-cat-apiserver   1         36ssvc-cat-cm          1         36s
Please provide guidance on:The list is not needed here and should be removed, using --- instead.

**Comment by MHBauer** [comment]
I am not able to find another yaml parsing tool that cannot interpret the file.

It's multiple items, that's a list.

Can you make a PR with the change you want? It looks like you have a very specific idea about what it should be.
