### ISSUE TITLE
k8s client-go dependency is outdated

### ISSUE THREAD

**Issue by polskikiel** [kubernetes-incubator/service-catalog#2616]
# Bug Report 

**What happened**:
SC uses client-go in version 1.11, because of that it may be hard to use SC dependency with some new projects which use client-go in versions 1.12-1.14

**What you expected to happen**:
SC uses client-go in newest version

**Comment by MHBauer** [comment]
client-go versions are different from kubernetes versions.

See https://github.com/kubernetes/client-go#compatibility-matrix
and note that client-go 11.0 is for kubernetes 1.14
