### ISSUE TITLE
Implement handlers in Fake Broker Server

### ISSUE THREAD

**Issue by kibbles-n-bytes** [kubernetes-incubator/service-catalog#263]
Right now the update service instance, bind, and unbind handlers in the fake broker server (`pkg/brokerapi/openservicebroker/util/fake_broker_server.go`) are unimplemented. We need to implement them to sufficiently test the broker client.

**Comment by pmorie** [comment]
@vaikas-google I think this is a necessary follow-up after #415 to ensure that the correct parameters got through to the broker api.

**Comment by vaikas-google** [comment]
This was addressed by #494 and #500
