### ISSUE TITLE
examine types and determine proper validation for each type

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#268]
The broker type has mostly complete validation. The remaining field to be validated is the `OSBGUID` field, which is unstructured text, but should probably be limited in size, if only for basic sanity reasons.

The remaining validations to complete are for objects:
- [x] service class (https://github.com/kubernetes-incubator/service-catalog/pull/507)
- [x] service plan (https://github.com/kubernetes-incubator/service-catalog/pull/507)
- [x] instance (https://github.com/kubernetes-incubator/service-catalog/pull/509)
- [x] binding (https://github.com/kubernetes-incubator/service-catalog/pull/510)

**Comment by arschles** [comment]
completed by #507, #509 and #510, closing
