### ISSUE TITLE
Add configuration API for controller and tie to CLI options for controller binary

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#273]
For example, pkg/brokerapi/openservicebroker/open_service_broker_client.go  has some config knobs (like PollingAmountLimit), we should allow for these to be configurable.  E.g. cmd line flags, config file, etc...  something.

**Comment by pmorie** [comment]
@duglin we have config APIs in k8s for this type of stuff.  Agree that we will need one for this project.

**Comment by pmorie** [comment]
I'm going to move this to MVP 2, since it is more in the spirit of that milestone.

**Comment by pmorie** [comment]
This is done; example: #631
