### ISSUE TITLE
unable to install service catalog using helm 3

### ISSUE THREAD

**Issue by sheena1537** [kubernetes-incubator/service-catalog#2906]
**helm install catalog svc-cat/catalog --namespace catalog --version 0.3.1** command gives the following error

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", unable to recognize "": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"]

Would be nice if you'll could help us fix this issue.

**Comment by poblin-orange** [comment]
Wich k8s version do you use (we install it successfully on k3s 1.20)

**Comment by breygonsnow** [comment]
It appears the chart refers to deprecated artifacts as of 1.22.  Example:

“The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22.”

**Comment by yanqingjin** [comment]
any updates on this issue? We are facing the same error when installing service catalog v0.3.1 to K3S v1.23.3+k3s1.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
