### ISSUE TITLE
Admin user not able to provision serviceinstance

### ISSUE THREAD

**Issue by Maellooou** [kubernetes-incubator/service-catalog#2907]
# Bug Report 

**What happened**: 

I installed the service catalog and I try as admin user (not cluster-admin) to create a serviceinstance on my namespace.
I installed only a clusterservicebroker.
I have the following error :

`User "titi" cannot get resource "serviceinstances" in API group "servicecatalog.k8s.io" in the namespace "toto"`

**What you expected to happen**:
I would like to create my serviceinstance on my namespace

It is not possible for admin user just on one namespace to provision serviceinstance through clusterservicebroker ?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.6
- service-catalog version: 0.3.1

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
