### ISSUE TITLE
a new service-catalog fork

### ISSUE THREAD

**Issue by duanhongyi** [kubernetes-incubator/service-catalog#2908]
It seems that this project has not been maintained for a long time. We try to take over it. But there was no response, so we temporarily established a fork whose address is:

github: https://github.com/drycc/service-catalog
website: https://service-catalog.drycc.cc/docs/install/
charts: https://charts.drycc.cc/testing/catalog

We have upgraded Kube's API as a whole, and it runs well on versions above 1.22, It is temporarily in our testing charts; After extensive testing, we will put it in stable charts.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
