### ISSUE TITLE
Stop relying setting RemoveSelfLink=false feature-gate - we're locking it to true with GA graduation in 1.24

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes-incubator/service-catalog#2909]
Upstream Kubernetes is going to get rid of ability to set SelfLink in release 1.24 (basically graduate graduate RemoveSelfLink feature gate to stable - see the KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1164-remove-selflink, for a bit more details).

It seems that volcano is still vendoring Kubernetes version that is setting it to false:
https://github.com/kubernetes-sigs/service-catalog/blob/master/vendor/k8s.io/apiserver/pkg/features/kube_features.go#L145

This is one more heads'up to stop relying on it (if you do in any place).

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
