### ISSUE TITLE
Is this project in use by anyone?

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-incubator/service-catalog#2913]
At this time, the kubernetes project is considering archiving this project. It may still be forked and maintained externally, however there does not appear to be enough momentum in project to keep it going.

If you are a user of this project, please chime in on this thread.

**Comment by piotrmiskiewicz** [comment]
We are using Service Catalog in SAP, but only for next few weeks. We are planning to remove it from Kyma.

**Comment by jpp06** [comment]
We are using this project at OrangeFrance to ease marketplace services usage in our K8s multi-tenant clusters.
As we also build and run CF clusters, ServiceCatalog offers our customers a similar user experience in both environments :

- OSB
- Easy service broker enrolment
- Easy service subscription
 
Even if SC was already nearly inactive when we started, we choose it as we did not find any appropriate replacement.

**Comment by nikileshsa** [comment]
We are using service catalog at Cisco for providing managed data services in k8s clusters for multiple internal use-cases.

**Comment by gsingh2712** [comment]
We are using it at JPMorganChase for providing MarketPlace Services on  K8s clusters

**Comment by siennathesane** [comment]
We're evaluating using it at Ada to provision internal platform services.

**Comment by mrbobbytables** [comment]
At this time, we're likely to try and move to the Cloud Foundry Foundation (if they want the projects). There isn't enough momentum here in K8s to keep things going and most of the consumers are using it through Cloud Foundry.

**Comment by 2rs2ts** [comment]
We are using it at Braintree. Quite a lot, actually. We're ramping up using it for RDS databases, and have used it for a lot of S3 buckets too.

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
