### ISSUE TITLE
Implement the ProvisionedService duck type as defined in https://github.com/servicebinding/spec

### ISSUE THREAD

**Issue by Samze** [kubernetes-incubator/service-catalog#2914]
# Feature
The [k8s binding spec](https://github.com/k8s-service-bindings/spec) provides a mechanism for automatically mounting a secret with Service credentials into an Application. This is somewhat similar to the Cloud Foundry mechanism of [VCAP_SERVICES](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES). 

If the service-catalog binding resource implemented the ProvisionedService duck-type, `.status.binding.name` then it would allow Workloads on Kubernetes to automatically connect to services when using libraries like [spring cloud binding](https://github.com/spring-cloud/spring-cloud-bindings).

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
