### ISSUE TITLE
Should Instance.Spec.ServiceClassName be ServiceClassRef?

### ISSUE THREAD

**Issue by bmelville** [kubernetes-incubator/service-catalog#297]
Currently instances point to their service class as just a string containing the name, while bindings point to instances using a kapi.ObjectReference. I think that instances should point to service classes using this as well, but not quite sure.

Same is probably true of service classes referencing their brokers.

**Comment by duglin** [comment]
I think this is based on whether objects MUST be in the same namespaces or not. I think in a previous f2f we agreed that service classes are scoped to namespaces, which means instances would be as well. Bindings can span namespaces though since that's how two apps, in different namespaces, can share the same instance/data.

**Comment by krancour** [comment]
I don't pretend to have all the answers, but just to add another perspective to this, referencing service classes by (sufficiently generic) _names_ could be important if in the future we want to have the possibility that an application, chart, etc. can ask for a _kind_ of service and not know or care how that is fulfilled. e.g. Imagine an application that expresses a dependency on a service class such a "Postgres 9.4" without caring whether the broker that handles that service class is provisioning the database in RDS, locally (in-cluster), or elsewhere.

**Comment by arschles** [comment]
Punting this to beta to decide.

**Comment by pmorie** [comment]
We currently use fields named `ThingName` as references to global (ie, non-namespaced) resources in Kubernetes.  See https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#object-references.
