### ISSUE TITLE
README

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes-incubator/service-catalog#311]
@pmorie what does this do??  TLDR; 

I will rewrite and put it in the readme...  Because I show this to my client, and he will be like ... well it does not say what it does ...

**Comment by chrislovecnm** [comment]
@duglin thoughts?

**Comment by duglin** [comment]
@chrislovecnm can you elaborate on what you're trying to say? Are you saying our README needs work?  I'm hoping to find some time, soon, to write-up more docs that describe our design choices which should help someone new understand a bit more of what's going on - perhaps that will help?

**Comment by duglin** [comment]
@chrislovecnm very rough outline to show where I'm headed:
https://github.com/duglin/service-catalog/blob/moreDocs/docs/design.md

**Comment by chrislovecnm** [comment]
Can you push a pr so we can comment on it?

**Comment by chrislovecnm** [comment]
Great start, I would love to see a short paragraph about what needs this component fullfils. Orchestration of helm charts. Approach it from a biz perspective, not tech.

**Comment by duglin** [comment]
Yup almost ready

-Doug

**Comment by chrislovecnm** [comment]
Be good to have a demo of sc if you want more comments. I am a new customer and have really no idea what it does. One of the Deis developers was super execited about it, and that peeked my interest.
