### ISSUE TITLE
enhance href check to check for anchor links

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#318]
see: https://github.com/kubernetes-incubator/service-catalog/pull/275/files#r98456823

**Comment by pmorie** [comment]
Moving to 0.0.3 because this isn't done yet.

**Comment by arschles** [comment]
@duglin please update this issue with the status. I am moving this out of a milestone until we decide exactly what we are doing here.

**Comment by duglin** [comment]
done - latest verify-href checker does this.
