### ISSUE TITLE
Generate OSB UUIDs instead of having the operator provide

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#324]
As @duglin suggested [here](https://github.com/kubernetes-incubator/service-catalog/pull/322#discussion_r98607940), creating these UUIDs is an onerous thing for operators to have to. We should generate these for them.

**Comment by krancour** [comment]
Actually, upon further investigation, we are already doing this.

**Comment by pmorie** [comment]
> Actually, upon further investigation, we are already doing this.

What makes you say that?

**Comment by krancour** [comment]
https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/handler.go#L110-L112

**Comment by krancour** [comment]
Just to wrap up this thread...

@pmorie and I discussed and agreed that managing these defaults needed to become an API responsibility, but that in the meantime (for as long as the controller watches TPRs instead of API types), we can leave the equivalent functionality in the controller as well.

See #334
