### ISSUE TITLE
Registry images should be prefixed

### ISSUE THREAD

**Issue by agonzalezro** [kubernetes-incubator/service-catalog#331]
Hi!

I've run `make image push` as explained in the documentation and (as expected) some images where pushed to my registry (in my case hub.docker.com).

The problem resides that at least 2 of this images have common names that could easily be already in usage. It's not a big deal since only a tag with the `$VERSION` is pushed but I think there is room for improvement.

Other of the issues with this model (pushing all to common names) is that it's a little bit more difficult to do a clean up after testing.

What do I propose? Prefix the images with a configurable prefix that by default is set to something like `catalog-service`.

I am still trying to get the project up and running but congratulations for the work, it seems promising! 👍🏽

**Comment by pmorie** [comment]
@agonzalezro has a good point -- I think we should use `service-catalog-` as a prefix for the name of each image.

**Comment by agonzalezro** [comment]
I am happy to do the change if it's what you want. Do you want a configurable prefix defaulting to `service-catalog-`?

**Comment by MHBauer** [comment]
@duglin What do you think? 

The proposed prefix is desirable. There are a lot of docs and charts and yamls and such that would need to be updated in addition to the image generation code.

**Comment by duglin** [comment]
I'm ok with a prefix, although "service-catalog-" is kind of long and a lot to type. What about `svc-cat` or `svc` ?  But if others want the verbose name I can live with it.

**Comment by agonzalezro** [comment]
I would agree with `svc-catalog` but I think that `svc-cat` isn't specific enough.

**Comment by MHBauer** [comment]
I like the long one. I have autocomplete.

**Comment by MHBauer** [comment]
I'm giving/assigning this to @agonzalezro provisionally if they still want it.

**Comment by mdshuai** [comment]
How do you think add prefix to the binary too? now k8s binary most has prefix

**Comment by agonzalezro** [comment]
I've started the change and I have the `Makefile` ready. It's configurable if you set `IMAGES_PREFIX`, the default value for that env var is `service-catalog-`.

My question is regarding the helm charts, the image names are required there, should I continue with this "configurable" prefix or simplify it with a hardcoded prefix? Because if I accept configuration in the helm chart I think that I will need to add a new value, something like:

```
    helm install \
        --set "registry=${REGISTRY},version=${VERSION},images_prefix=${IMAGES_PREFIX}" \
        --namespace catalog \
        ./deploy/catalog
```

I am ok with both solutions, but I would go with the "non configurable" one.

**Comment by pmorie** [comment]
@agonzalezro will you make a PR?

I would prefer not to have a configurable prefix unless we have a strong need for it, and to just produce these image names:

- `k8s-service-catalog-apiserver`
- `k8s-service-catalog-controller-manager`

**Comment by agonzalezro** [comment]
Yes @pmorie, I did some work on it already, I just didn't have clear if we should allow configuration or not.

Since we both agree in disallow configuration for now the PR should be pretty simple. Will let you know soon.

PS: should we go with `k8s-service-catalog-` or keep with the original `service-catalog-`?

**Comment by duglin** [comment]
`k8s-service-catalog` is really really long!
