### ISSUE TITLE
The server doesn't have a resource type "servicebrokers"

### ISSUE THREAD

**Issue by agonzalezro** [kubernetes-incubator/service-catalog#332]
Hi,

I've been following the guides, but when I get to this step: https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/DEVGUIDE.md#walkthrough instead getting an empty list I get the following error:

```
the server doesn't have a resource type "servicebrokers"
```

At the beginning I thought it was ok because as the docs said: _...we didn't create any services yet, kubectl get will return an empty list_, but after following the next step:

```
kubectl create -f broker.yaml
```

I get the following error:

```
unable to recognize "contrib/examples/walkthrough/broker.yaml": no matches for catalog.k8s.io/, Kind=ServiceBroker
unable to recognize "contrib/examples/walkthrough/broker.yaml": no matches for catalog.k8s.io/, Kind=ServiceBroker
```

It seems that the third party resource doesn't exist. I've been checking the code and I don't see any yaml referencing to it as a ThirdPartyResource (perhaps it's create via API or other).

In case it helps this is the state of my `catalog` namespace:

```
$ kubectl get deployments,services --namespace catalog
NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/controller   1         1         1            0           23h
deploy/k8s-broker   1         1         1            0           23h
deploy/registry     1         1         1            0           23h
deploy/ups-broker   1         1         1            0           23h

NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
svc/k8s-broker   10.0.0.169   <none>        8000/TCP   23h
svc/registry     10.0.0.87    <none>        8001/TCP   23h
svc/ups-broker   10.0.0.131   <none>        8000/TCP   23h
```

Thanks again!

**Comment by vaikas-google** [comment]
Take look at the controller logs, the TPRs should get created once the controller comes up. And older versions of k8s had a problem where this didn't work, so you should be running at least 1.4.

**Comment by vaikas-google** [comment]
The TPRs get created here:
https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/watch/watcher.go#L157

**Comment by agonzalezro** [comment]
@vaikas-google I am using the latest version of minikube:

```
$ k version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

Also, this is the describe for the controller in case it helps:

```
$ k describe deployments controller --namespace catalog
Name:                   controller
Namespace:              catalog
CreationTimestamp:      Tue, 31 Jan 2017 15:05:03 +0100
Labels:                 app=controller
Selector:               app=controller
Replicas:               1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Conditions:
  Type          Status  Reason
  ----          ------  ------
  Available     True    MinimumReplicasAvailable
OldReplicaSets: <none>
NewReplicaSet:  controller-2036095763 (1/1 replicas created)
No events.
```

**Comment by pmorie** [comment]
We're going to remove the TPR stuff imminently.

**Comment by agonzalezro** [comment]
Just curious, if you will not use TPR how are you going to do this? I thought that TPR+controllers was the magic here :) Is there any doc where you explain the future design concept?

**Comment by MHBauer** [comment]
@agonzalezro we're going to use the federated/aggregated/whatever api mechanism provided by upstream. Thus we have an apiserver based on upstream code.

**Comment by MHBauer** [comment]
with the new controller, does this still require resolution?

**Comment by arschles** [comment]
The API server doesn't have resource types for `Service*` at all - they are only `broker`/`brokers`, etc...

I'll fix the dev guide and close this out.
