### ISSUE TITLE
Fix upstream code gen tools so it passed the verification checks (eg. lint)

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#346]

**Comment by spzala** [comment]
#dibs

**Comment by MHBauer** [comment]
remove the comment in the makefile for golint/govet when they pass
`@# Exclude the generated (zz) files for now, as well as defaults.go`

**Comment by pmorie** [comment]
Theoretically this might be doable by MVP 2.

**Comment by spzala** [comment]
@pmorie thanks Paul!! Newbie question, where is the milestone dates/schedule? I am wondering what's MVP 2 deadline. It seems like multiple repos (like. k8s/gengo /ugorji/go where I have some PR under review) needs to be fixed first and then update those libraries in k8s and eventually update the service-catalog k8s dependencies. Thanks!

**Comment by pmorie** [comment]
@spzala We don't have a firm schedule at this point - but I would like for everything we consider to be MVP to be done before kubecon, if at all possible.  I'm moving this to MVP 3 because it is less urgent than many of the other things we have for MVP 2.

**Comment by spzala** [comment]
@pmorie Thanks!! and sounds great.

**Comment by pmorie** [comment]
@duglin @spzala is this done?

**Comment by spzala** [comment]
@pmorie @duglin no, most changes (except one for conversion which I am looking into) are checked in with PRs opened in different libraries like gengo, go and also one in kubernetes base repo. But they all are under review, I sent them reminder before Kubecon and hopping them to review the changes. Here is a list of PRs, just FYI: 
https://github.com/kubernetes/kubernetes/pull/42781
https://github.com/kubernetes/gengo/pull/40
https://github.com/kubernetes/gengo/pull/41
https://github.com/ugorji/go/pull/190

**Comment by pmorie** [comment]
Moving out of 0.0.2

**Comment by arschles** [comment]
@spzala can you update what the status of this issue is?

I am moving out of a milestone until we figure out when we need to finish this

**Comment by spzala** [comment]
@arschles sure, that's a good idea. Because of dependency on multiple external repositories, this is taking longer and we can't exactly tell when all changes will be merged. So sounds good to me. Thanks!

**Comment by spzala** [comment]
Update:  /cc @duglin for two of the lint failures i.e. remove "_" from generated function names and re-writing "if...else" loop, reviewers are reluctant to make change, the comments I received are,
1. it's per design
2. changes promotes non-idiomatic code, not good
3. lint is moving target and we can't take care of every lint requirements etc.. 
However many lint errors are fixed e.g. adding comments programmatically to the generated code public functions 
Thanks!

**Comment by duglin** [comment]
ok it seems like things are as good as they're going to be given the resistance you got.
Thanks for pushing on this and getting the other changes in.
Going to close this.

**Comment by spzala** [comment]
@duglin yes, agree. No problem Doug and Thank you for all your help !!
