### ISSUE TITLE
Fix Package servicecatalog lint verification 

### ISSUE THREAD

**Issue by spzala** [kubernetes-incubator/service-catalog#355]
'make' gives following minor verification issue, 
pkg/apis/servicecatalog/doc.go:20:1: package comment should be of the form "Package servicecatalog ..."
Found 1 lint suggestions; failing.

**Comment by spzala** [comment]
#dibs

**Comment by arschles** [comment]
@spzala what is the status of this issue?

**Comment by spzala** [comment]
@arschles Hi, @MHBauer wanted to do some investigation here because of all the changes made in the generated files. I will follow up on it and update the latest. Thanks!

**Comment by arschles** [comment]
@spzala thanks

**Comment by spzala** [comment]
@arschles you are welcome and thank you! The issue is fixed under https://github.com/kubernetes-incubator/service-catalog/pull/417 by adding a comment as expected by lint, so I am closing this one.
