### ISSUE TITLE
Update pkg/genericapiserver to k8s.io/apiserver

### ISSUE THREAD

**Issue by mdshuai** [kubernetes-incubator/service-catalog#384]
When read the code I find current we use ```"k8s.io/kubernetes/pkg/genericapiserver"``` in apiserver
But upstream PR https://github.com/kubernetes/kubernetes/pull/40863, Moved ```pkg/genericapiserver``` to ```k8s.io/apiserver```, we need update code to use ```k8s.io/apiserver``` make service-catalog more compatible.

**Comment by pmorie** [comment]
My plan is to get everything working with the version of kubernetes that we currently vendor and then rebase onto all the refactored API server bits once things are working and stable.

**Comment by pmorie** [comment]
Closing as duplicate of #413
