### ISSUE TITLE
evaluate clean targets and directories to clean

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#385]
Follow up to #383 

We have multiple hidden directories that are created. Should clean delete them? `.kube/`, `.pkg/`, `.var/`

We have generated code that is checked in. Should that be subject to a clean? `pkg/client` is entirely generated.

**Comment by MHBauer** [comment]
I vote to clean the generated code. I've created a PR as such.

**Comment by MHBauer** [comment]
`.pkg` should be cleaned as part of `clean-build-image` as it gets mounted into the build image `.scBuildImage`.

**Comment by MHBauer** [comment]
`.var` is a result of running the integration tests.

**Comment by MHBauer** [comment]
`.run` is also, from running the built in kubectl script.

**Comment by MHBauer** [comment]
`.kube` is also the intergation tests + kubectl script.

`.out` results when the verify script fails.

**Comment by arschles** [comment]
I am moving this issue out of a milestone as it's not required for our beta release. Please close this when it's completely addressed.

**Comment by duglin** [comment]
@MHBauer what's the status of this?  Moving to post-v1.0.0 since I don't think its critical for v1

**Comment by MHBauer** [comment]
/cc @jberkhahn 
Does this has a place anymore? If not, I'm fine with closing it.
