### ISSUE TITLE
What's our SSL strategy for the API server?

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#389]
Trying my best to succinctly summarize a very nuanced question with lots of background context...

Currently, our Helm chart for the apiserver includes a secret that contains a hard-coded cert. This is bad. This cert _always_ causes problems because the CN/SANS in the cert don't contain the IP(s) that `kubectl` or our own controller would use to communicate with the apiserver. This is a recipe for a cert error.

Trying to rectify this has been a dead end.

Options, as I see them:

1. Before chart installation, use a script to generate a CA. Use that CA to sign both client and server certificates. During install, pass the server key and cert to the apiserver along with the CA, which will go in its trust store.
\
The problem with this approach is that is requires clairvoyance! We'd need to know the apiserver's service IP(s) when we generate the certificates, i.e. _before_ the apiserver is deployed.
\
It's easy to see this won't work.

1. Generate the server certificate on startup, similar to how the upstream/core apiserver does. Like the upstream apiserver, we do currently do this if a cert isn't explicitly provided, and in fact we do it using upstream code. This doesn't work, however...
\
Upstream cert generation code makes some assumptions that are true for _their_ apiserver, but not for ours. The first is an assumption that their apiserver either runs natively (i.e. not containerized) on the master node _or_ containerized, but with host-only networking. In either case, it's easy for cert generation code to determine the master node's IP address so this can be added as a SAN.
\
The second assumption made upstream is that the apiserver's service IP is the _first_ in the range reserved for service IPs. So, with a range of `10.0.3.0/24` reserved, for instance, it's a safe assumption that the apiserver's service IP is `10.0.3.1`. This to gets added as a SAN. _Our_ apiserver can't make such an assumption.
\
We could work around those issues by abandoning reuse of upstream cert generation code and writing a substantial amount of custom code. This custom code would do nothing to advance the ease with which future aggregated APIs can be authored.
\
Lastly, if we wanted our apiserver to generate its certificate at startup (and assuming we'd solved for all of the above) we'd still have the issue that the generated cert had better be one the client will trust. That means we'd have to sign it with a CA that was passed in as a secret in the Hem chart. (The client would put that same CA in its own trust store.) Unfortunately, upstream cert generation code only supports self-signed certificates. So this is even _more_ custom code we'd have to introduce.

Taking a giant step back and looking at the big picture, aggregated APIs are coming... and while that might solve parts of this equation for us (for instance, `kubectl` will only ever have to talk to the core apiserver), it will really just kick other parts of this equation down the road... or so we think.

Before we spend too much time iterating on a one-off solution to all this that won't benefit the _next_ aggregated API to come along or, worse, will prove unnecessary or incompatible with the forthcoming aggregator, we'd like to get some idea of how (or if) any of this is being addressed upstream as part of the aggregator work.

@liggitt, I'm tagging you because @pmorie tells me you are someone who would be in the know on this topic. _Any_ insight at all is most appreciated.

**Comment by MHBauer** [comment]
'Fix it upstream' is the only real sane thing to do, but that might take a while. Whatever we need to get it working before then is unfortunate work, but should be something that goes into upstream to help everyone else in the same position in the future.

I'd like to have clear support from core before we do that and start working on it.

**Comment by krancour** [comment]
Ya. That's kinda the point of this issue. I'm inviting commentary and insight from core contributors.

**Comment by liggitt** [comment]
a few quick pointers to related work.

For obtaining certs (client certs or serving certs):

1. The [CSR API](https://kubernetes.io/docs/api-reference/certificates.k8s.io/v1alpha1/operations/) (in v1alpha1 in 1.5, v1beta1 in 1.6) allows submitting requests for certificates with a specific CSR and usage (client or serving cert, etc).
2. The kubelet uses the CSR API to request/rotate client certs:
  * https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/
  * https://github.com/kubernetes/kubernetes/blob/03837fe6075590aea3a71d36a93b14cf9ce8e7b3/cmd/kubelet/app/bootstrap.go#L45
  * https://github.com/kubernetes/kubernetes/blob/03837fe6075590aea3a71d36a93b14cf9ce8e7b3/pkg/kubelet/certificate/certificate_manager.go

[OpenShift has the capability](https://docs.openshift.org/latest/dev_guide/secrets.html#service-serving-certificate-secrets) to annotate a service indicating you want a serving certificate, and one is generated and placed in a secret for you. Your pod spec can then reference that secret and your pod will block until it is available. It's possible something similar might be done in Kube (possibly backed by a controller using the CSR API, even), but that hasn't been determined yet. 

For delegated authentication, the example API server illustrates the info you need to plug into three types of auth setups:
1. sitting behind an authenticating proxy (as you would in the kube-aggregator case)
2. recognizing client certs (if a cert user contacted your server directly)
3. recognizing bearer tokens (if a token user contacted your server directly)

[Example API server code](https://github.com/kubernetes/kubernetes/blob/03837fe6075590aea3a71d36a93b14cf9ce8e7b3/staging/src/k8s.io/sample-apiserver/pkg/cmd/server/start.go#L42)

Recommended [generic server options](https://github.com/kubernetes/kubernetes/blob/03837fe6075590aea3a71d36a93b14cf9ce8e7b3/staging/src/k8s.io/apiserver/pkg/server/options/recommended.go#L38-L47)

Recommended delegating [authentication](https://github.com/kubernetes/kubernetes/blob/6a65964d0ebd909e0aa9f7738aae058cb55a0b7a/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go#L103-L131)/[authorization](https://github.com/kubernetes/kubernetes/blob/6a65964d0ebd909e0aa9f7738aae058cb55a0b7a/staging/src/k8s.io/apiserver/pkg/server/options/authorization.go#L46-L71) options

**Comment by krancour** [comment]
> The CSR API (in v1alpha1 in 1.5, v1beta1 in 1.6) allows submitting requests for certificates with a specific CSR and usage (client or serving cert, etc).

> Kubelet TLS bootstrapping uses the CSR API to request and rotate client certs.

@liggitt this is interesting-- good information, but I'm honestly still feeling a bit stuck.

Prioritizing all the pieces of the puzzle here, my number once concern is getting a certificate for the apiserver. The existence of the CSR API is interesting. I'm wondering if it means I could write code against client-go that would allow _our_ apiserver to obtain a certificate from the _core_ apiserver at startup...

But my very next thought is that the _next_ apiserver to come along will just have to duplicate that code, won't they? That strikes me as a clear indicator that this should all be accounted for upstream. To be fair, it's not entirely clear to me that it _isn't_ accounted for upstream, although, tbh, I can't spot anything that suggests it is. I'm left wishing that apart from the meager examples I have seen, that there some good documentation that spelled out the general procedure and considerations for implementing an API that extends k8s. In its absence, I'd gladly settle for anyone who can provide some guidance.

Do you have specific thoughts on how (i.e. "the right way") our apiserver should go about obtaining its own certificate that is signed by a user provided CA?

**Comment by liggitt** [comment]
the least coupling implementation you can make today is to require a cert to be mounted in via a secret. that can be satisfied by any process capable of creating a cert and putting it in the secret. that could be a manual process, one driven automatically by an external signer, or one that makes use of the CSR API. if you build your app to expect to be given the certs, and make a throwaway script that scrapes a service IP and makes a cert for it, you're well positioned to consume cert-building solutions from upstream

**Comment by krancour** [comment]
@liggitt are you proposing that we create the apiserver's service _before_ we create the rest of it (cert-bearing secret, deployment, etc.)?

That's simple and it would certainly work. My only concern about it is that it complicates the installation process quite a bit by making service catalog something that cannot be installed with a simple `helm install`. I think we could live with that, but only short-term.

Want to make sure I understand where we go from there...

> if you build your app to expect to be given the certs... you're well positioned to consume cert-building solutions from upstream

This part isn't entirely clear to me yet. We can build our apiserver to "expect to be given the certs." But, as we've discussed, the conventional way of doing that is through a secret that our apiserver's pod will mount to a specific location on its file system. When we eventually throw away the throwaway script you've proposed, who or what takes over the management of that secret? Is it the aggregator?

**Comment by liggitt** [comment]
> When we eventually throw away the throwaway script you've proposed, who or what takes over the management of that secret?

more likely something resembling openshift's [service serving cert signer](https://docs.openshift.org/latest/dev_guide/secrets.html#service-serving-certificate-secrets) (name trips off the tongue, doesn't it?), possibly backed by the CSR API

**Comment by krancour** [comment]
> more likely something resembling openshift's service serving cert signer

But do we really want something in kubernetes-inclubator that hopes to graduate into the kubernetes org someday to depend on something downstream like openshift?

Or are there plans to try and move the cert signer upstream?

**Comment by liggitt** [comment]
> @liggitt are you proposing that we create the apiserver's service before we create the rest of it (cert-bearing secret, deployment, etc.)?

You can create all of it except the secret, then create the secret out of band. That mimics what I would expect to happen with a cert signing service as well (with the only likely change being indicating in a yet-to-be-determined way that your app requires a cert for its service in a given secret)

**Comment by liggitt** [comment]
> But do we really want something in kubernetes-inclubator that hopes to graduate into the kubernetes org someday to depend on something downstream like openshift?

Not depending on openshift. Depending on a cert issuing actor of some sort seems more reasonable than embedding one deeply inside a single component.

Worst case, one doesn't materialize in the short term and your throwaway one persists, but in an easily replaced way when someone wants to plug in their own cert issuer.

**Comment by krancour** [comment]
> You can create all of it except the secret, then create the secret...

I can try that. I was supposing that wouldn't work because upstream code that the apiserver re-uses will generate a self-signed cert if a cert isn't provided. I was imagining that this would stop our apiserver from failing in the case that the secret is missing, and that would prevent it from re-starting when the secret become available...

But now that I think about it more, I think if our pod mounts a secret that is nowhere to be found, even scheduling will fail and we won't get to the point of generating an undesired self-signed cert. I'd try this to be sure, but I thin now that that would be ok.

Thanks for that suggestion.

**Comment by liggitt** [comment]
> if our pod mounts a secret that is nowhere to be found, even scheduling will fail and we won't get to the point of generating an undesired self-signed cert

scheduling succeeds, kubelet blocks starting the container

**Comment by krancour** [comment]
> scheduling succeeds, kubelet blocks starting the container

👍 That'll do.

**Comment by liggitt** [comment]
by making your server container just consume the secrets, there are other possible mechanisms for obtaining them as well - an emptydir volume to hold the certs and an init container whose sole job is to obtain the cert could work as well.

**Comment by krancour** [comment]
> Not depending on openshift. Depending on a cert issuing actor of some sort seems more reasonable than embedding one deeply inside a single component.

👍 

That seems very reasonable.

Now I'm just trying to imagine how I can somehow unify all the steps needed to effect install into a simple process, given the constraints of Helm.

> an emptydir volume to hold the certs and an init container whose sole job is to obtain the cert could work as well

That is a very interesting thought. This has been very helpful. Thanks!

**Comment by arschles** [comment]
Moved to the 1.0.0 milestone, as that is when we are planning to have full aggregation support. Please see [the roadmap](https://github.com/kubernetes-incubator/service-catalog/wiki/Roadmap#100)

**Comment by MHBauer** [comment]
@DirectXMan12 does API Aggregation solve this for us in the case where we are using aggregation?

As I understand it, 
The service-catalog apiserver will be behind the aggregator and not able to be contacted.

**Comment by liggitt** [comment]
> The service-catalog apiserver will be behind the aggregator and not able to be contacted.

Not quite. The aggregator<->service-catalog-server connection will still need to be TLS-secured, and nothing prevents you from contacting the service-catalog server directly if it's pod or service IPs are network accessible.

**Comment by DirectXMan12** [comment]
>  contacting the service-catalog server directly if it's pod or service IPs are network accessible

A "smart client" could, eventually, contact the aggregator to obtain the APIService records, and then use those to talk directly to the various API servers, if it wanted to bypass the aggregator for some reason (e.g. bottleneck considerations), for instance.

**Comment by krancour** [comment]
I don't believe there is any issue of consequence remaining here.

With API aggregation, only the core k8s apiserver speaks to the svc cat apiserver. It does so using s hostname that is resolved via the k8s dns addon _that has also been added as an alternate name on the svc cat apiserver's serving certificate._

Ref:

https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/apiregistration.yaml#L3-L4

The only parties that should now receive an SSL warning when communicating with the svc catalog apiserver, would be those who _aren't_ the k8s core apiserver. Unless I'm sorely mistaken, that is increasingly a more and more outlying use case... making this issue inconsequential.

I move to close.
