### ISSUE TITLE
Broker from `contrib/examples/walkthrough` doesn't load

### ISSUE THREAD

**Issue by spadgett** [kubernetes-incubator/service-catalog#398]
```
$ contrib/hack/kubectl create -f contrib/examples/walkthrough/broker.yaml
unable to recognize "contrib/examples/walkthrough/broker.yaml": no matches for catalog.k8s.io/, Kind=ServiceBroker
unable to recognize "contrib/examples/walkthrough/broker.yaml": no matches for catalog.k8s.io/, Kind=ServiceBroker
$ contrib/hack/kubectl version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.4118+597e938e3a1a95-dirty", GitCommit:"597e938e3a1a95cc01f9656c71aa366ca6ef0d26", GitTreeState:"dirty", BuildDate:"2017-01-28T16:02:27Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

cc @pmorie

**Comment by krancour** [comment]
This looks like the resource types used by the service catalog haven't been defined. They're defined when the service catalog itself starts up.

Have you completed the steps [here](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/DEVGUIDE.md#deploying-to-kubernetes) to deploy the service catalog apiserver and controller?

**Comment by spadgett** [comment]
@krancour Thanks, I'm running the catalog using

```
$ contrib/hack/start-server.sh
```

The examples from `contrib/examples/apiserver` load OK. It looks like those use `servicecatalog.k8s.io/Broker` instead of `catalog.k8s.io/ServiceBroker`?

**Comment by krancour** [comment]
I can't vouch for much of what's on `contrib/hack`. I think we might have a lot of bitrot in there.

Your best bet is to install using the instructions in the link I gave. We're more actively ensuring that the steps documented in there are accurate.

**Comment by MHBauer** [comment]
`contrib/hack/start-server.sh` starts the apiserver only, and does not use the TPR backend like the walkthrough.

**Comment by pmorie** [comment]
I'm removing this in #485; closing.
