### ISSUE TITLE
Add TPR storage to the tests in test/integration/clientset_test.go

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#407]
They currently test just the etcd-based server. I believe there is a bug with service class creation as well, so this will force fixing that bug.

Left to do:

- [x] Mock out the client interface and pass it to the TPR options in integration.go
    - Probably using `github.com/kubernetes-incubator/service-catalog/pkg/client/clientset_generated/clientset/fake` -- requires #505, as @krancour is writing a mock `RESTClient` that this fake will need to use.
- [ ] Re-enable the TPR storage type in clientset_test.go

**Comment by MHBauer** [comment]
I wouldn't consider this closed since some of the tests are just skipped.

**Comment by arschles** [comment]
@MHBauer correct, reopening. I believe @krancour is working now on fixes and re-enabling the rest of the tests for TPR

**Comment by arschles** [comment]
Related to #599

**Comment by pmorie** [comment]
Moving to 0.0.3 because this isn't complete.

**Comment by pmorie** [comment]
Moving to the next alpha release for now.

**Comment by arschles** [comment]
Instead of writing TPR integration tests, we are going to add better [e2e tests](https://github.com/kubernetes-incubator/service-catalog/issues/698) and more thorough [unit tests](https://github.com/kubernetes-incubator/service-catalog/issues/700). I am closing this issue.
