### ISSUE TITLE
Handle conversion of service and plan metadata into our API

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#412]
Currently the logic to do this is commented out -- we need to put this back in and add tests to ensure that service classes and plans are created correctly based on the OSB catalog response.

**Comment by pmorie** [comment]
Related: https://github.com/kubernetes-incubator/service-catalog/issues/513

**Comment by MHBauer** [comment]
Link to the code where the commented out section is?

**Comment by arschles** [comment]
I'm probably looking in the wrong place, but this looks like conversion logic: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller.go#L278-L295

**Comment by vaikas-google** [comment]
That's the update path from what I understand, 

https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller.go#L263

**Comment by vaikas-google** [comment]
It's L 264 that's creating the error.
