### ISSUE TITLE
wip-catalog chart's apiserver svc type dependent on debug?

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#423]
The `wip-catalog` Helm chart has the apiserver's `Service` type dependent on whether `debug=1` is set or not.

I can't understand why the type of service we use should be dependent on whether we're debugging or not. Additionally, when debugging, one gets a service of `type: LoadBalancer` and that avoids this error, which arises if _not_ debugging  / using service of default `type: ClusterIP`:

```
$ helm install     --set "registry=${REGISTRY},version=${VERSION}",storageType=etcd,insecure=true     --namespace catalog     ./deploy/wip-catalog
Error: release lumpy-bee failed: Service "apiserver" is invalid: spec.ports[0].nodePort: Invalid value: 30001: may not be used when `type` is 'ClusterIP'
```

https://github.com/kubernetes-incubator/service-catalog/blob/master/deploy/wip-catalog/templates/apiserver.yaml#L59-L61

**Comment by arschles** [comment]
I am moving this out of MVP 1

**Comment by krancour** [comment]
This was addressed when the charts were completely re-written in #546. Closing.
