### ISSUE TITLE
integration test framework leaks servers

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#434]
Each call to getFreshApiserverAndClient leaks a server on a random port.

**Comment by arschles** [comment]
@MHBauer do the servers _eventually_ shut down? my understanding is that the shutdown function closes the stop chan, which asynchronously does the shutdown

**Comment by MHBauer** [comment]
On exit of the binary, yes.

There was a similar issue in kubernetes which caused flakes.
