### ISSUE TITLE
For: WIP Controller, figure out who populates various GUIDs

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/service-catalog#437]
Currently controller (wip) does not populate the GUIDs before talking to the broker, say, when creating a Service Instance. My understanding is that the controller is responsible for this.
There's a TODO in wip controller so if you resolve this, also update / remove the comment.

**Comment by vaikas-google** [comment]
From @pmorie :  It's the API server's job to create GUIDs for: Instance, Binding. GUIDs for ServiceClass and ServicePlan come from the broker.

**Comment by pmorie** [comment]
@vaikas-google It seems like we should encode this information somewhere in docs and possibly types.go, agree?

**Comment by vaikas-google** [comment]
Absolutely. I think controller should also check that it's indeed populated as bad things will happen if it's not. Not sure what the guarantees there are however from the API server side, but seems safer to make sure it's there always?
