### ISSUE TITLE
Add utilities to give uniform representations of objects for logging

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#451]
One thing that happens naturally in codebases is that when someone adds a logging statement that prints information about an object, they will inevitably choose something that make sense to them, which may not be uniform with the rest of the codebase.  In practice, this means that logs wind up full of differing representations of the same object.  We should move toward utility methods for each API type that print the representation of that type for logging purposes.  That will ensure that:

1.  Representations of objects are uniform throughout the logs
2.  Those representations can be changed easily in one place

**Comment by MHBauer** [comment]
It would be nice to implement `String()` for all of our objects such that the default printing is pleasant to read. Maybe there is a library for that? A quick grep on upstream shows the generated protobufs have pretty formats.

**Comment by MHBauer** [comment]
The pretty context-builder handles this. Not sure if we need to consider implementing `String()` anymore, use of go-spew or other libraries.

https://github.com/kubernetes-incubator/service-catalog/tree/v0.1.23/pkg/pretty
