### ISSUE TITLE
Enable delegated authn and authz back to the core API server

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#457]
In order to support unified authn and authz, we should enable delegation back to the core API server.  There is code in master now, which is commented out, that does this.

**Comment by pmorie** [comment]
I would like for this to be in MVP 2 but that might be optimistic.  I've heard the magical-thinking 'it should just work' about this.

**Comment by MHBauer** [comment]
I think it relies on being in-cluster. So we'll need a flag to turn it off or otherwise disable it to prevent it from crashing on startup when running unit/integration tests and other general tomfoolery.

**Comment by pmorie** [comment]
@MHBauer 

> I think it relies on being in-cluster. So we'll need a flag to turn it off or otherwise disable it to prevent it from crashing on startup when running unit/integration tests and other general tomfoolery.

Agree, that matches my expectations / understanding as well.

**Comment by pmorie** [comment]
Moving to 0.0.3 since this is not ready yet.

**Comment by arschles** [comment]
Moving to 1.0.0 since we will need this by the time we add full support for aggregation

**Comment by pmorie** [comment]
@DirectXMan12 isn't this addressed by your auth PR?

**Comment by DirectXMan12** [comment]
yeah, this was implemented as part of the auth PR.  This can probably be closed.

**Comment by MHBauer** [comment]
buh-bye.
