### ISSUE TITLE
Create consensus on deprovision

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#46]
Forking from #39 

We need to establish a consensus for the API mechanics for deprovision.  I think this can be similar to the mechanics described in #39.  This would go something like:

1.  In order to deprovision an instance, a user issues a DELETE request for that `Instance`
2.  The REST API endpoint accepts the request and updates the status of the Instance to show that it is being finalized
3.  The service-catalog controller calls the deprovision endpoint at the instance's broker
4.  On a success response from the broker, the service-catalog controller deletes the `Binding` instances associated with the `Instance`
5.  The service-catalog controller issues the final DELETE for the `Instance` once the `Bindings` are ultimately deleted

@arschles asked about where deprovision should mean that bindings are deleted.  I do think deletes should cascade -- if an instance has been deprovisioned, a binding against is has no meaning.

**Comment by arschles** [comment]
I'm good with the algorithm described above, and cascading deletes

**Comment by pmorie** [comment]
We have since agreed on this, implemented in #403
