### ISSUE TITLE
Add events to resources

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#463]
Currently we're just setting status. We should add events to resources to give more detailsd information back to users.

**Comment by jwforres** [comment]
Question that just came up during UX discussions is whether we can get events for async operations completing.  This lets us have notifications to let users know their service provision has completed or their binding as completed (when we eventually have async bind).  Or in both cases if the async operation perm failed.

**Comment by pmorie** [comment]
Moving to 0.0.3 because this isn't done.

**Comment by pmorie** [comment]
@jpeeler is going to take this one

**Comment by arschles** [comment]
Moving to 0.0.4. @jpeeler is currently working on this
