### ISSUE TITLE
List requests should return an empty array for items and not null

### ISSUE THREAD

**Issue by jwforres** [kubernetes-incubator/service-catalog#465]
Example, if I request a list of service classes and there are none, the response should not have `items: null` it should have `items: []` to be consistent with all k8s APIs.

**Comment by pmorie** [comment]
@jpeeler interest in this?

**Comment by jpeeler** [comment]
I'll take it.

**Comment by MHBauer** [comment]
remember to add a test for it as well.

**Comment by arschles** [comment]
@jpeeler @pmorie can you add a milestone to this issue?
