### ISSUE TITLE
Set up a basic CI

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#47]
We need someone to volunteer to set up and tend a basic CI setup for the service catalog.  We will undoubtedly increase complexity of the CI setup as we go, and can graduate to more sophisticated setups, but travisci is probably sufficient for the next couple weeks.

Any takers?

@kubernetes-incubator/maintainers-service-catalog

**Comment by martinmaly** [comment]
I'd be happy to give it a shot, something that does build, lint, runs unit tests (for now). The e2e tests will be tricky because they need to spin up k8s clusters.

There is some setup only repo admin can do (I believe) so one of the admins will need to do that.

**Comment by martinmaly** [comment]
I cannot assign the issue to myself but here is the PR:
https://github.com/kubernetes-incubator/service-catalog/pull/62
and here is an example Travis run on my fork of service-catalog:
https://travis-ci.org/martinmaly/service-catalog

**Comment by duglin** [comment]
I think we can close this since #62 is merged.

BTW - if you put something like:
Closes: #47

in your PR then it would auto-close #47 as the PR is merged and we don't need to do it manually.
