### ISSUE TITLE
What conditions should we have in the API?

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#476]
We (arguably prematurely) added some additional conditions beyond the ready condition as constants in the API.  After implementing things in the new controller, I am not certain at this time that we need any condition for any resource beyond the ready condition.

@jwforres, as someone who will be writing a UI around this API, do you think we need additional conditions, or, can we get away with ready + status + message for now?

**Comment by jwforres** [comment]
for both provision and bind we care about whether the async operation has completed or not, and if not why not. So the why not is covered by the status + message.  Right now I'm not sure there is anything else we care that much about.

**Comment by arschles** [comment]
We have a clear direction for this issue, which is outlined in #535

**Comment by jwforres** [comment]
Having Ready condition is sufficient for clients for now, it tells us whether the provision / bind are complete and if not then why not.

**Comment by pmorie** [comment]
I'm going to close this out; we can create an issue to add other conditions as needed.
