### ISSUE TITLE
Have an e2e for the walkthrough

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#487]
I would like for this statement to evaluate to true:

```
Basic demo == walkthrough == 1 e2e testcase
```

Goals are:

1. Make it for easy for anyone to give a basic demo by going through the walkthrough 
2. Ensure the walkthrough stays running

**Comment by arschles** [comment]
@pmorie are we still on track for delivering this by the MVP2 due date? Also, does this depend on #456?

**Comment by arschles** [comment]
cc/ @kibbles-n-bytes

**Comment by kibbles-n-bytes** [comment]
@arschles Yes, we will have at least e2e tests that go through the walkthrough with an etcd-backed API server. Finishing up that work now.

**Comment by kibbles-n-bytes** [comment]
@arschles #456 depends on this issue.
