### ISSUE TITLE
Codify how asynchronous provision and deprovision responses are handled in the service catalog controller

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#49]
See https://github.com/kubernetes-incubator/service-catalog/pull/40/files#diff-7bc5ab85846e6317175a21b5acb68061R65

Acceptance criteria for this issue:

- Documentation that describes how the controller should modify the `status.state` fields of relevant Kubernetes resources when it receives an asynchronous response
- Documentation that describes, at a high level, what logic the controller should implement to handle async responses. This should include what state the controller may need to store internally

**Comment by pmorie** [comment]
Moving this to MVP-2 since it didn't wind up being in scope for legos-1

**Comment by pmorie** [comment]
Closing; dupe of #249
