### ISSUE TITLE
Add costs associated with Plan to the API

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#496]
We currently don't have the cost fields for plans in the API; I left them out because I wasn't sure how to represent them.  Now, we have people coding to the API and they're wondering where costs are, so we should sort this out and put costs back in.

**Comment by pmorie** [comment]
cc @jwforres

**Comment by jwforres** [comment]
FYI @dtaylor113 @jeff-phillips-18

**Comment by pmorie** [comment]
@jpeeler this might be a good one for you to pick up when you have a chance.

Moving to 0.0.3 for now because this isn't done yet.

**Comment by jpeeler** [comment]
After reading the spec, I realized that the cost field is in the metadata section. The metadata section is treated as a binary blog by the controller, so there's no work to be done here. Agree?

**Comment by pmorie** [comment]
I agree, if this is a metadata field, then we should not have a first-class field for it in the API.  @jwforres, will you be able to work with metadata to get cost information?

**Comment by jwforres** [comment]
sure if we need to, its unfortunate that something like cost is not defined in the spec

**Comment by pmorie** [comment]
It's arguable that it's fortunate, since the definition of costs is...
somewhat loose, let's say.

**Comment by pmorie** [comment]
Since this is part of metadata, and not a first-class field, this issue can be closed.
