### ISSUE TITLE
Namespaced resources should be finalized when the k8s namespace is finalized

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#499]
In Kubernetes, when a namespace is deleted, all of the resources in that namespace are deleted.  We should make the service catalog API resources participate in this.  When a namespace is deleted, all of the bindings and instances in that namespace should be deleted.

**Comment by pmorie** [comment]
Moving to 0.0.3 because this isn't done yet.

**Comment by arschles** [comment]
This hasn't been started, but it would be nice to have this done by 0.1.0. Setting milestone accordingly.

**Comment by arschles** [comment]
I am moving this to 0.2.0, since it doesn't require any API surface changes but would be beneficial to have this before our 1.0.0 release

**Comment by jboyd01** [comment]
per Paul, this is done automatically for us.
