### ISSUE TITLE
Document code review / merge protocol

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#50]
To approve a PR, 3 committers must LGTM it. We should create PR labels so that committers can simply label a PR if they have LGTM-ed it. Additionally, the labels should accommodate the veto policy.

**Comment by duglin** [comment]
I wonder if using PullApprove would be good - it won't let the PR be merged until a certain # of people have LTGM'd it.  Then we don't need any more process than just an LGTM comment, like normal.

**Comment by krancour** [comment]
fwiw, what we have found at Deis is that LGTM1/2/3 labels > LGTM comments for two major reasons. The first is that we found a lot of project followers don't want want to be spammed with notifications for trivial comments. The second, more important reason is that when querying open PRs, review status can be assessed at a glance in an index view.

**Comment by arschles** [comment]
Here's a more concrete proposal

We create the following 4 labels.

- `LGTM1`
- `LGTM2`
- `LGTM3`
- `Veto`

Here's how they'll be used.

Reviewers should look at the complete list of open PRs in this reposutory and choose to review anything they see fit without an `LGTM3` label and without a `Veto` label.

When they review, they should do one of the following:

- Add the next `LGTM*` label if they completely approve of the changes, or approve of the changes pending existing comments
  - If the PR already has `LGTM1`, for example, then they should add `LGTM2`
- Add comments indicating what needs to be fixed before they will add the next `LGTM` label
- Add the `Veto` label if they don't want the PR merged even if it does get all 3 `LGTM` labels. 
  - Reviewers should add this label iff they believe there is something fundamentally wrong and it should be addressed in an interactive session (i.e. Zoom).
  - We expect vetos to happen infrequently
  - This is the "nuclear option"

**Comment by vaikas-google** [comment]
* I think it's insufficient to just apply a VETO label without justifications, so a VETO label must have some reasoning behind it.
* What's the difference between LGTM3 and merge? Once LGTM3 has been granted, why not just merge? Is this for example, LGTM but there's a few tiny things that need fixed and once thay are fixed, merge can proceed?

**Comment by duglin** [comment]
I agree - you can't veto with a comment explaining it.

**Comment by arschles** [comment]
added note that veto-er must add a veto explanation

**Comment by arschles** [comment]
As discussed in the 11/29/2016 SIG meeting, we're going to only adopt a `Veto` label for now, and leave this issue open. We'll come back to the `LGTM`-as-labels discussion later if needed.

**Comment by arschles** [comment]
https://github.com/kubernetes-incubator/service-catalog/pull/61 fixes; closing
