### ISSUE TITLE
Tag docker images with appropriate labels.

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/service-catalog#504]
In order to make debugging issues easier and making sure that deployments are consistent, we should tag our images with meaningful labels and update the deploy charts to match these releases. For example:
in our deploy/catalog/README.md there are several options to override the values for the docker images, and I don't think some of those defaults make sense necessarily.

**Comment by arschles** [comment]
@vaikas-google and I talked offline and agreed to the following tagging strategy:

1. every commit on master builds and pushes a new image with the sha (not `canary`, so images are immutable and we get reproducibility for bug reports)
2. every git tag has a similarly named docker tag (kubernetes/helm does this too. see [here](https://github.com/kubernetes/helm/blob/master/scripts/ci/deploy.sh#L21-L28))
3. the helm chart's docker tag value (`version`) is set to the most recently released tag (as of this writing, there is no tag, so default it to a non-existent docker tag)

**Comment by vaikas-google** [comment]
I also think at some point we should have semver for the released images, but that didn't seem to make it here. So either we deem that something that's not necessary, or we create a new bug to track that.

**Comment by arschles** [comment]
@vaikas-google if we use semver for our Git tags (something I absolutely think we should do), then we'd get semver docker tags for free

**Comment by vaikas-google** [comment]
@arschles Super :) Should we (or is there an issue?) somewhere to track that work?

**Comment by krancour** [comment]
Adding my $0.02. 100% on board with @arschles' proposal _and_ with the notion of using semver tags for both github and docker, with the latter being the product of the former.
