### ISSUE TITLE
Idea: Have a single representation of valid API resources for testing

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#514]
This is just an idea; no need to do it if people don't want to.

As we have begun adding tests, we've begun to accumulate valid representations of objects in:

1.  unit tests (versioned and unversioned)
2.  integration tests
3.  YAML descriptors for use with the API server integration test

This is natural, but has a couple not-great effects we should seek to mitigate:

For example, tests get very gorpy and repetitive:

```go
{
	name: "missing instance name",
	binding: &servicecatalog.Binding{
		ObjectMeta: kapi.ObjectMeta{
			Name:      "test-binding",
			Namespace: "test-ns",
		},
		Spec: servicecatalog.BindingSpec{
			SecretName: "test-secret",
		},
	},
	valid: false,
},
{
	name: "invalid instance name",
	binding: &servicecatalog.Binding{
		ObjectMeta: kapi.ObjectMeta{
			Name:      "test-binding",
			Namespace: "test-ns",
		},
		Spec: servicecatalog.BindingSpec{
			InstanceRef: v1.LocalObjectReference{
				Name: "test-instance-)*!",
			},
			SecretName: "test-secret",
		},
	},
	valid: false,
},
```

Eventually someone will take a look at a single test and go and refactor it to have object-mother methods like:

```go
func ValidBinding() *v1alpha1.Binding { /* ... */ }
```

...which improves readability, but then eventually adds entropy as these methods accumulate in different tests.

I was thinking about this last night as I slammed out many PRs adding validation tests.  I think we can limit entropy and improve test readability by doing the following:

1.  Make two golang packages that provide object-mother methods that return valid versioned and unversioned, internally consistent API resources:
    - `pkg/apis/servicecatalog/valid/internal` for unversioned
    - `pkg/apis/servicecatalog/valid/v1alpha1` for versioned
2.  Use these everywhere in the system to create objects
3.  Make a generate that creates valid YAMLs from the valid versioned objects
4.  Have a test that verifies that:
  1.  The versioned and unversioned valid objects are `DeepEqual` once versioned is converted to unversioned
  2.  The YAMLs are `DeepEqual` to the unversioned objects once deserialized

Advantages of doing this:

1.  Lower entropy in tests - no need to make up valid objects
2.  When an invalid object is required, it's easy to understand how it's invalid:
```go
invalidBinding := v1alpha1valid.Binding()
invalidBinding.Name = "" // binding is now invalid
```
3.  Table tests get much easier to read:
```go
{
	name: "missing instance name",
	binding: func() *v1alpha1.Binding {
		binding := v1alpha1valid.Binding()
		binding.Spec.InstanceRef.Name = ""
		return binding
	}(),
	valid: false,
},
{
	name: "invalid instance name",
	binding: func() *v1alpha1.Binding {
		binding := v1alpha1valid.Binding()
		binding.Spec.InstanceRef.Name = "192fw(@(*&!"
		return binding
	}(),
	valid: false,
},
```

Disadvantages of doing this:

1.  Not strictly necessary
2.  Additional work to make it work and test that it stays working in CI

With that said, I have used pieces of this pattern before and it has made tests a lot more readable and saved a lot of lines of code.  I haven't done the parts where we have a single representation in both versioned and unversioned that are `DeepEqual` after conversion, or the generator that creates the YAMLs.

**Comment by pmorie** [comment]
Didn't mean to set the milestone, unset for now

**Comment by arschles** [comment]
Assigning to the beta cycle.

**Comment by arschles** [comment]
This issue is unnecessary, closing.
