### ISSUE TITLE
Controller integration tests

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#515]
We need to add integration test coverage for the controller.  There's a stub in `test/integration/controller_test.go` which needs additional scenarios.  To implement these, we will need to implement methods that poll the API server and wait for a status condition to reach a certain value.

**Comment by MHBauer** [comment]
speaking of coverage, is there a way to actually see the whole project coverage for the integration-tests?

**Comment by pmorie** [comment]
@MHBauer not that I know of.

**Comment by pmorie** [comment]
Closed by https://github.com/kubernetes-incubator/service-catalog/pull/522
