### ISSUE TITLE
Catalog request not sending Broker API version

### ISSUE THREAD

**Issue by dymurray** [kubernetes-incubator/service-catalog#516]
For our implementation of the ansible-service-broker (https://github.com/fusor/ansible-service-broker/) we require that all requests have a header specifying the broker API version. (see here for an example request using this header: https://github.com/fusor/ansible-service-broker/blob/master/test/catalog.sh#L5).

Without the header the catalog request 404s and fails to bind the broker to the service catalog.

**Comment by pmorie** [comment]
This seems like a candidate for componentconfig API (#273)

**Comment by pmorie** [comment]
We should have this in MVP-2 - it's required per the spec: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#api-version-header

**Comment by MHBauer** [comment]
@dymurray can you try again and let us know if it still fails. We should be sending a v2.11 header now.
