### ISSUE TITLE
`organization_guid` and `space_guid` in instance should be a required field

### ISSUE THREAD

**Issue by simonleung8** [kubernetes-incubator/service-catalog#528]
Currently we don't enforce these fields to be present when creating an instance. We should enforce the policy as it is a required field as stated in Open Service Broker Api

**Comment by arschles** [comment]
I am moving this out of MVP2

**Comment by pmorie** [comment]
I don't think these fields have any meaning in our API right now, and in any event, I do not want to force users to supply them.  I think this needs to have some design around it before we make any plan to do this or not.

**Comment by duglin** [comment]
let's discuss this on Friday because w/o these fields we are not spec compliant. Plus I'm hopeful that the point will be moot by then
