### ISSUE TITLE
Rename controller to catalog

### ISSUE THREAD

**Issue by martinmaly** [kubernetes-incubator/service-catalog#53]
As a result of the initial seed code evolution, the catalog component is named 'controller' rather than catalog. It should be renamed to match the terminology used by the SIG.

Proposal:
 * directory /controller is renamed to /catalog
 * identifiers, or their parts, in the code which refer to the same will be renamed from [Cc]ontroller to [Cc]atalog.
 * update any documentation `*.md` files as well.

**Comment by pmorie** [comment]
I disagree with this, actually.  The 'controller' is eventually going to be split into two things:

1.  The API server that hosts the API resources
2.  The controller that establishes watches and implements the 'controller' behaviors we discussed in F2F meetings

I have a more fundamental and broad refactoring that I would like to do -- i'll create an issue for that one.

**Comment by martinmaly** [comment]
I'm not opposed to that. My primary concern is that today's controller does things beyond its scope which will be addressed by the refactoring.
Also, my historical bias shows here in that the name controller was picked initially to mean something slightly different, but it turns out it is still applicable to part of the functionality on  @pmorie list :)
