### ISSUE TITLE
Remove the HTTP/JSON implemented by the controller/server package

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#54]
Per discussion in #52, this predates the watch on k8s 3prs of interest to the controller, isn't strictly needed, and should probably be eliminated.

However... I would propose that we do implement a single `/healthz` endpoint to facilitate HTTP-based health checks.

**Comment by pmorie** [comment]
I would like to avoid adding functionality to the existing controller.  Instead, we need to refactor to the correct architecture ASAP so that we're investing effort in the right way.

**Comment by martinmaly** [comment]
I'd still support removal of the HTTP surface (less code to then refactor) and if it turns out /healthz-style handler is needed in the future, re-add it. Would that be acceptable?

**Comment by pmorie** [comment]
Upon further consideration, we can leave the http muxing in, since we will likely need a healthz endpoint in the future for the controller process.

**Comment by vaikas-google** [comment]
Should we modify the issue to reflect the decision? Is this simply:
remove the API methods, add healthz?

**Comment by pmorie** [comment]
@vaikas-google yes -- go for it.
