### ISSUE TITLE
Controller should fail health check until API server comes up

### ISSUE THREAD

**Issue by simonleung8** [kubernetes-incubator/service-catalog#545]
Currently the controller returns `200 ok` on it's health check endpoint as soon as it starts serving.
We should wait until it can communicate with the API server before returning `200 ok`.

**Comment by MHBauer** [comment]
The code to do the healthz actions looks to move into apimachinery. Potentially should wait to do work until after rebase in #596.

**Comment by pmorie** [comment]
Moving to 0.0.3 because this isn't done yet.

**Comment by MHBauer** [comment]
How much of this will https://github.com/kubernetes-incubator/service-catalog/pull/615/files#r110766510 solve since it won't stay up? 

Should we move the http server AFTER that block?

**Comment by simonleung8** [comment]
I might not understand your question entirely but this issue is not relevant if the controller fails on startup. We only care about checking the API server if controller comes up healthy.

**Comment by MHBauer** [comment]
Right now, before 615, there is a gap [when 129-141 runs](https://github.com/kubernetes-incubator/service-catalog/blob/master/cmd/controller-manager/app/controller_manager.go#L129-L141) and when the [controller is started](https://github.com/kubernetes-incubator/service-catalog/blob/master/cmd/controller-manager/app/controller_manager.go#L168).

We also don't install a handler that says whether we can contact the apiserver.

There are two remedies, part of which is done in 615
1. don't start up
1. install a handler that itself does a ping on the apiserver

Additionally, we could fail and blowup the controller if the apiserver fails to respond.

I think I know what to do now.

**Comment by pmorie** [comment]
Moving to 0.0.4 because this isn't done yet.

**Comment by arschles** [comment]
@MHBauer any progress toward this issue? I am moving to the beta cycle for now

**Comment by arschles** [comment]
This issue is unrelated to the API surface, moving to 1.0.0
