### ISSUE TITLE
[Proposal] Provide an example for Kubernetes and BlueMix integration

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-incubator/service-catalog#548]
The BlueMix can help provide some service for Kubernetes, so that Kubernetes can leverage those services especially for some database services.

**Comment by arschles** [comment]
cc/ @duglin @MHBauer in case you guys are more familiar with BlueMix

**Comment by arschles** [comment]
thanks @gyliu513!

**Comment by krancour** [comment]
I would humbly suggest that there's no need for us to be providing cloud-provider-specific examples. k8s is supposed to be our common denominator over all infrastructure.

**Comment by gyliu513** [comment]
Thanks @krancour , how about adding sth like `docs/contrib/xxx.md` as some examples for specified integration example? The `contrib` folder can make life easier for people with a specified requirement.

**Comment by arschles** [comment]
@gyliu513 would you be interested in adding such a document in that location?

**Comment by gyliu513** [comment]
Sure, I do have such plan and also want to contribute for this @arschles

**Comment by arschles** [comment]
@gyliu513 any progress here?

**Comment by gyliu513** [comment]
Sorry @arschles , not yet started, planning to start this next week, will have you updated if any progress. Thanks.

**Comment by arschles** [comment]
I am moving this out of a milestone. @gyliu513 please comment here when you have started.

**Comment by MHBauer** [comment]
IBM Cloud Kubernetes has everything necessary to install service-catalog with no changes to either side.
