### ISSUE TITLE
Flaky test in ./pkg/storage/tpr

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#551]
Not sure exactly which test, but we've seen one of the tests in this package fail intermittently. Will update this issue with details the next time we see it.

cc/ @duglin

**Comment by pmorie** [comment]
I saw the same thing - in my case it was `TestInstallTypesAllResources`.

I'd recommend running it 1000 times (`-count 1000`) and seeing if you can get it to fail

**Comment by MHBauer** [comment]
Seeing the failed tests take 1 second.

Poll has a 1 second timeout on a 1 second retry.

**Comment by MHBauer** [comment]
TestInstallTypesAllResources is racy in a way. There is no checking that each resource is not seen and then seen. It checks that there are four gets, and then four more gets. Given the threading, all four 'pre'-gets could be used up by checking on the first tpr, with a fifth to be 'found' leaving any and all others to be found as if they were installed the whole time.
@simonleung8

**Comment by MHBauer** [comment]
`go test -i -v  ./pkg/storage/tpr -race -c &&  ./tpr.test -test.v -v 10 -logtostderr -test.run 'TestInstallTypesAllResources|TestInstallTypesResourceExisted'`
I think the race detector helps repro.

**Comment by simonleung8** [comment]
I think I see the problem. First we used a map of channel, first create then poll, the actions were sequential, but that is not the case anymore after we wrap the polling into the go func() and that causes the flakiness. I will fix this after finishing what I have on hand. Unless somebody else get to it first.

**Comment by simonleung8** [comment]
actually #dibs
I might have an easy fix
