### ISSUE TITLE
Publish charts/catalog helm chart to a public chart repository

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#590]
A good place to publish would be a public Google Cloud Storage or AWS S3 bucket, as various helm charts do.

See https://github.com/kubernetes/helm/blob/master/docs/charts.md#chart-repositories for a description on what a chart repository is.

**Comment by pmorie** [comment]
I must admit that I am not super-clear on what this means.  Is repository here a 'chart repository'?

**Comment by arschles** [comment]
>Is repository here a 'chart repository'?

Yes. I've changed the title to be more specific

**Comment by arschles** [comment]
This should be done in a beta release. Assigning to `0.1.0` to indicate.

**Comment by arschles** [comment]
Dupe of #735, closing
