### ISSUE TITLE
Make e2e tests run by default

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#591]
The `jenkins` label should be changed to `no jenkins` (or similar) to specifically turn off e2e tests. 

cc/ @kibbles-n-bytes

**Comment by kibbles-n-bytes** [comment]
The thought here was that anyone can open PRs, and when others become more active with this project we wouldn't have control over who is running what on our Jenkins. But for now I'll remove the tag requirement, and if an issue occurs then we'll readdress it.
