### ISSUE TITLE
Add documentation on how to configure & use Third Party Resource storage mode

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#598]
The API server can store its resources in etcd or third party resources. Our walkthrough documentation explains how to interact with the server running in etcd mode. That document as well as appropriate other docs should be expanded to describe how to run and interact with the server in TPR mode.

This includes doing actions directly against TPRs.

Things to think about:

- If you’re running in TPR mode, make sure to clean up TPRs
- Make sure to delete all instances via the catalog API server so they get deprovisioned

**Comment by arschles** [comment]
We should only write docs once #599 and #600 are fixed. Since #600 is in 0.0.3, I am moving this to that milestone as well

**Comment by krancour** [comment]
> This includes doing actions directly against TPRs.

While I know that _can_ be done, shouldn't the walkthrough w/ TRP-backed storage be _exactly_ the same, save for the step that installs the catalog chart?

```
$ helm install charts/catalog --name catalog --namespace catalog -- set apiserver.storage.type=tpr
```

**Comment by arschles** [comment]
I'd still like to have directions that indicate that you can modify TPRs directly. Until we run behind the aggregator (scheduled for 1.0.0), it's important to tell users that they have an option to talk directly to the core server (when they run in TPR mode)

**Comment by arschles** [comment]
We should have these docs around the 0.1.0 cycle. Moving milestones accordingly
