### ISSUE TITLE
tpr-based storage needs some work

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#599]
In working on #576, some flaws in the tpr-based storage implementation were uncovered, but not corrected.

- Compared to the etcd-based storage upstream, we have put update logic in the wrong spot. A direct consequence of that is when performing an update, our storage impl isn't returning a copy of the _updated_ object (e.g. with _new_ resource version). This is in direct contrast to the behavior of update using etcd-based storage. The two implementations should be made consistent.

- The tpr-based storage impl uses a restclient to talk to the upstream apiserver... but it completely ignores HTTP response codes. One known case where this is problematic is where a get returns a 404. Because we're ignoring the 404, we proceed with attempting to decode an empty response body, which leads to a panic.

There may be other issues lurking as well. Re-enabling some of the disabled tests from #576 should help to uncover them.

**Comment by krancour** [comment]
Add to this list that updates do not work for, it seems, just the namespaced objects (instances and bindings).

**Comment by pmorie** [comment]
Moving to 0.0.3 because this isn't complete.

**Comment by arschles** [comment]
This issue covers multiple bugs, so I'm labelling it as a meta and moving out of a milestone

**Comment by arschles** [comment]
@krancour I have verified that the walk-through works in TPR mode for API server and controller images tagged `dc73f2b`, except that deletes still don't work (https://github.com/kubernetes-incubator/service-catalog/issues/600). Can we close this issue now?

**Comment by duglin** [comment]
re-pinging... can we close this?

**Comment by duglin** [comment]
marking this as 0.1.0 since if its not done I believe MSFT needs it to work on-par with etcd support, right @arschles ?

**Comment by pmorie** [comment]
@arschles - what do you think about this?  still applicable?

**Comment by nilebox** [comment]
Even though the TPR storage will be deprecated soon, we still need to make the same change for CRD storage (I have a PR based on TPR storage code). So I can take a look at this issue.

**Comment by arschles** [comment]
@nilebox thank you. I am removing this from 0.1.0 since TPR will still be in alpha (per the documentation) after we hit beta

**Comment by MHBauer** [comment]
TPR storage is gone in #1322, and #1088 covers CRD implementation.
