### ISSUE TITLE
overall error recovery

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#601]
I'm not sure what's at fault, but we need better handling of error cases.

Some examples:
 - the namespace does not exist. I got to a point where I could not delete something that referenced a non-existent namespace
 - I couldn't delete a binding that was created while the service broker was down
 - I could not delete an instance that was created before the broker was created.

**Comment by arschles** [comment]
I'd like to see this fixed in one of our beta quality releases. Assigning to 0.1.0.

**Comment by arschles** [comment]
Moving to 1.0.0, since this is error message cleanup only, and does not affect our API surface

**Comment by duglin** [comment]
@MHBauer is this just error message cleanup?  When you said things like "I couldn't delete..." that doesn't sound like just an error message tweak to me.

**Comment by MHBauer** [comment]
closing as I don't remember the details or have a test case.
