### ISSUE TITLE
Support leader election in controller

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#603]
Our controller should support leader election for clusters where there are multiple copies of the controller run.

**Comment by pmorie** [comment]
@directXman12, this one has your name all over it, hoss

**Comment by arschles** [comment]
I have some questions here, because I'm concerned with the amount of complexity that leader election will add (even though the code is already written), both in comprehending the codebase and more importantly, debugging user submitted issues:

- Do you have a use case for multiple controllers in a single cluster?
- What will the replicas do?

**Comment by MHBauer** [comment]
Very interested in learning the deeper internals here, as well as understanding the upstream design decisions.

**Comment by arschles** [comment]
moving this into the beta cycle

**Comment by pmorie** [comment]
> Do you have a use case for multiple controllers in a single cluster?

Yes.  We deploy all k8s controllers in an active/passive HA mode in OpenShift clusters with HA masters.  We plan to deploy an instance of the service catalog controller in the same way - one controller instance per master, colocated with each master.

> What will the replicas do? Wait until they're elected?

Yep.

> If we do run multiple controllers, can we use a distributed lease to provide mutual exclusion for side-effecting operations (such as REST calls to brokers)?
>    Note that I don't necessarily believe this is a better solution than leader election. I do want to understand the overall goal here

This is basically exactly how leader election is implemented.  See #647
