### ISSUE TITLE
Wrong TPR name for service classes

### ISSUE THREAD

**Issue by kibbles-n-bytes** [kubernetes-incubator/service-catalog#609]
Running `kubectl get thirdpartyresources` on the main Kubernetes API server gives `service-class.servicecatalog.k8s.io`, but when you try to run a `kubectl get` on this resource you get the response:

```the server doesn't have a resource type "service-class" in group "servicecatalog.k8s.io"```

It seems the resource is actually called `serviceclass.servicecatalog.k8s.io` (without the dash).

**Comment by krancour** [comment]
Believe it or not... that's how it works (upstream). I'll try to find references tomorrow.

**Comment by MHBauer** [comment]
I recall this as well. TPR does a bunch of munging to the name you give it. Can we give it serviceclass no-dash everywhere?

**Comment by krancour** [comment]
See my comment at https://github.com/kubernetes-incubator/service-catalog/pull/614#issuecomment-289505703. Closing.
