### ISSUE TITLE
Need output version for apiserver & controller-manager

### ISSUE THREAD

**Issue by mdshuai** [kubernetes-incubator/service-catalog#624]
When I file a issue I want paste the version but I can't find it.
There is no version for apiserver and the version of controller-manager output is not correct.

```
# ./apiserver --version
I0401 05:31:11.358551   24481 server.go:88] using etcd for storage
Error: unknown flag: --version
# ./controller-manager --version
Kubernetes v0.0.0-master+$Format:%h$
```

**Comment by MHBauer** [comment]
Tried to hack it into the apiserver quickly, and discovered I'm not sure how to do it.

The values are set by a script which sets ldflags. `kube::version::ldflags` in `hack/lib/version.sh` looks like a function that should move to repo-infra to be upstream reusable along with the contents of `k8s.io/kubernetes/pkg/version`. Does that make sense @pmorie ? Or is there a better place?

**Comment by apelisse** [comment]
I've tried to implement it in #646
