### ISSUE TITLE
Controller shouldn't continually relist a broker's catalog

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#627]
Current the controller will continually re-list a broker's catalog, even if the broker is already in a ready condition.  In CF, broker re-list is driven by a command from the user.  I think eventual reconciliation with the broker is more the kubernetes way, but we should not continually re-list brokers that are ready.  As an initial step, I think that we should add transition time to conditions, and think of a more sensible relist period to use for brokers that are already ready.  Ultimately, users should be able to trigger broker re-list via a command as well.

**Comment by duglin** [comment]
Yep - allow for:
- relist automatically every X
- never relist automatically
- relist now

**Comment by arschles** [comment]
This would be nice to have well before the 0.1.0 cycle. Moving to 0.0.4 accordingly.

**Comment by pmorie** [comment]
This one can get in for 0.0.3 if we get reviews today

**Comment by pmorie** [comment]
I want what @dug said here on a per-broker basis, eventually: https://github.com/kubernetes-incubator/service-catalog/issues/627#issuecomment-290998496

There should be a porcelain command for relist now, created #704

**Comment by arschles** [comment]
#702 fixed this. Closing. There is remaining work to be done in this issue; @jpeeler will create a focused issue to track that work.
