### ISSUE TITLE
Add flag to enable 'free-only' mode

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#633]
I have a use-case for deploying the catalog in a free-only mode, where only free services would be shown and be able to be provisioned.

**Comment by duglin** [comment]
Would be nice to deal with this when we talk about curation since this feels like a special case of the bigger issue.

**Comment by arschles** [comment]
Punting this to stable to decide.

**Comment by pmorie** [comment]
I'm closing this because I don't think my original idea is the write way to go - but I have some new ideas prompted by #1124 that I will open an issue for.
