### ISSUE TITLE
Integrate pod presets into service-catalog

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#637]
After #413, we will have Kubernetes 1.6 as a dependency and will have access to `v1alpha1` `PodPreset` data types, so we need to integrate them. This entails at least:

1. Defining fields in a `Binding` that describe parts of the `PodPreset`
2. Creating the `PodPreset` during the bind operation

**Comment by pmorie** [comment]
I will take this one on in 0.0.3

**Comment by arschles** [comment]
Moving to 0.0.4, as we didn't get to this in 0.0.3

**Comment by arschles** [comment]
Note that #266 was a duplicate. See the OP in that issue for more detail

**Comment by arschles** [comment]
I am moving this to 0.1.0, as it doesn't look like it will be worked on this week

**Comment by duglin** [comment]
Minor nit but if there are dups usually you close the later ones, not the original.

**Comment by pmorie** [comment]
@dug is right, I will re-open the earlier issue.
