### ISSUE TITLE
What are we going to do to change the public data types?

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#638]
Data types should be cleaned up in preparation for our beta release (at which point we should keep them backward compatible. see https://github.com/kubernetes-incubator/service-catalog/wiki/Roadmap#010 for detail). Some ideas:

- Removing `OSB` prefixes from some fields in `Instance`s (https://github.com/kubernetes-incubator/service-catalog/issues/583)
- Moving the checksum (#852)

Note that this issue specifically targets the `0.0.7` release for changes to the public data types. We will create another issue for future milestones if necessary.

**Comment by pmorie** [comment]
Moving this to the beta release milestone.

**Comment by arschles** [comment]
I'd like everyone to look at our data types (`Broker`, `ServiceClass`, `Instance` and `Binding`) between 5/1/2017 and 5/8/2017. Come to the SIG meeting on 5/8 with suggestions for changes. We'll decide on the final data types and implement necessary changes for the 0.1.0 release scheduled for 5/17/2017

**Comment by MHBauer** [comment]
For top-level names:

In the context of Service-Catalog and Service-Broker, I think the ServiceClass and ServicePlan names are the odd ones out and should be `Service` and `Plan`. 

Within the context of kubernetes, `Service` could be problematic`. I do not see any problem with `Plan`.

**Comment by duglin** [comment]
I'd like to better understand why we need a Checksum property. For Binding it should write-once so at worst we may need a boolean flag to indicate if we've created the binding on the broker yet or not.  For Instances it seems like a boolean to indicate that we need to sync with the broker should be sufficient. Do we care which field changed?  Especially when the checksum won't tell us which one, and right now only "plan" can change anyway.  I'm not sure I see the value of the extra complexity of a Checksum when a boolean "dirty" type of flag will do.

**Comment by duglin** [comment]
Also, whether we keep checksum or not, it seems like that should be in the Status struct since its read-only to the user, right?

**Comment by MHBauer** [comment]
I think checksum to status makes sense.

**Comment by pmorie** [comment]
> I'd like to better understand why we need a Checksum property.

For posterity: we need the checksum field because we can't query the OSB API to see what the last successful state we reconciled to was. (See #582 and #573)

I agree - for now binding should be write-once.  We could change to a boolean in the status if we wanted to.  If we ever become able to update binding parameters, and we do not yet have a way to query the last values sent (see https://github.com/openservicebrokerapi/servicebroker/issues/159), we would need to add the checksum back for bindings.

**Comment by pmorie** [comment]
Related:

- #813 
- #828 
- #814
- #802

**Comment by MHBauer** [comment]
How about #297 ?

**Comment by pmorie** [comment]
@MHBauer I just closed #297, but that would have been in scope if there was work to do :)

**Comment by duglin** [comment]
opened https://github.com/kubernetes-incubator/service-catalog/issues/852 to deal with the checksum topics

**Comment by duglin** [comment]
@arschles can we close this since it appears we have PRs and issues to track the issues mentioned?

**Comment by pmorie** [comment]
I think #1080 supercedes this
