### ISSUE TITLE
Flake: API server did not come up successfully

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#643]
Jenkins build [#106](https://service-catalog-jenkins.appspot.com/job/service-catalog-PR-testing2/106/console), which started from https://github.com/kubernetes-incubator/service-catalog/pull/642, caused a flake. The offending logs seem to be these:

```console
+ error_exit 'API server pod did not come up successfully.'
+ echo '/var/lib/jenkins/workspace/service-catalog-PR-testing2/src/github.com/kubernetes-incubator/service-catalog/contrib/hack/test_walkthrough.sh: line 85: API server pod did not come up successfully. (exit 1)'
/var/lib/jenkins/workspace/service-catalog-PR-testing2/src/github.com/kubernetes-incubator/service-catalog/contrib/hack/test_walkthrough.sh: line 85: API server pod did not come up successfully. (exit 1)
```

cc/ @kibbles-n-bytes

**Comment by arschles** [comment]
The same flake appears to be in https://service-catalog-jenkins.appspot.com/job/service-catalog-PR-testing2/142/console, except the controller pod was reported as not up successfully:

```console
+ error_exit 'Controller pod did not come up successfully.'
+ echo '/var/lib/jenkins/workspace/service-catalog-PR-testing2/src/github.com/kubernetes-incubator/service-catalog/contrib/hack/test_walkthrough.sh: line 87: Controller pod did not come up successfully. (exit 1)'
/var/lib/jenkins/workspace/service-catalog-PR-testing2/src/github.com/kubernetes-incubator/service-catalog/contrib/hack/test_walkthrough.sh: line 87: Controller pod did not come up successfully. (exit 1)
```

**Comment by arschles** [comment]
@MHBauer I've seen the same flakes in travis's integration tests. those do not run our components inside pods afaik, correct?

**Comment by MHBauer** [comment]
Correct. I have not seen those myself, hence my description. Sounds like there's some general weirdness then.

**Comment by kibbles-n-bytes** [comment]
Definitely general weirdness. There seem to be three different things being reported in this issue:

1. API server image pull error
2. Controller-manager crash loop
3. Integration test timeout failures

I think some of the Jenkins changes that went in the other day should alleviate the first two. The integration test failures are a separate issue.

I'm going to close this issue for now and make a separate one just for the integration tests timing out. If we see any non-integration-test flakes, then let's make separate issues for them as they come.
