### ISSUE TITLE
master builds failing on travis

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#649]
Last two here https://travis-ci.org/kubernetes-incubator/service-catalog/builds

```
pkg/storage/tpr/keyer_test.go:33: undefined: "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api".NewContext
pkg/storage/tpr/keyer_test.go:34: undefined: "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api".WithNamespace
pkg/storage/tpr/keyer_test.go:40: undefined: "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api".NewContext
pkg/storage/tpr/keyer_test.go:48: undefined: "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api".NewContext
pkg/storage/tpr/keyer_test.go:49: undefined: "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api".WithNamespace
FAIL	github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr [build failed]
```

**Comment by MHBauer** [comment]
I think the keyer tests from #642 need to be rebased on the 1.6 era master.

**Comment by arschles** [comment]
@MHBauer yep, I think you are right. I wasn't able to rebase #642 before it was merged. https://github.com/kubernetes-incubator/service-catalog/pull/639 fixes the build. Apologies all!

**Comment by arschles** [comment]
For those reading later, these are the two failing builds: 

- https://travis-ci.org/kubernetes-incubator/service-catalog/builds/219038044
- https://travis-ci.org/kubernetes-incubator/service-catalog/builds/219030098
