### ISSUE TITLE
Travis CI's tag based builds do not push docker images

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#651]
This build: https://travis-ci.org/kubernetes-incubator/service-catalog/builds/218181643 was kicked off when I created the `v0.0.1` GitHub release (and tag). As seen in the build logs, however, it did not `docker push`. I believe that the problem might lie in [line 2790](https://travis-ci.org/kubernetes-incubator/service-catalog/builds/218181643#L2790):

```console
Skipping a deployment with the script provider because this branch is not permitted
```

**Comment by MHBauer** [comment]
That's very confusing to me. It's a tag, not a branch, right?

Do we need to take out https://github.com/kubernetes-incubator/service-catalog/blob/master/.travis.yml#L15 ?

**Comment by arschles** [comment]
@MHBauer I'm not sure if this answers your question completely, but here's a start. We want to `docker push` both on all `master` builds and all tags. The tags are the "official" images.

Taking out https://github.com/kubernetes-incubator/service-catalog/blob/master/.travis.yml#L15 would be the same thing as what's in master right now because travis automatically deploys only the github-default branch (`master` for us). Travis is not 100% clear on what happens if both `tag: true` and `branch: abcde` are set. From https://docs.travis-ci.com/user/deployment:


```
tags: When set to true, the application is deployed when a tag is applied to the commit. This causes the branch condition to be ignored.
```

My interpretation here is that tags will be deployed, and otherwise deploys will be subject to the `branch` value

**Comment by MHBauer** [comment]
Reading that, try `tags: true` ?

**Comment by arschles** [comment]
@MHBauer yep
