### ISSUE TITLE
Remove entire contents of deps dir

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#66]
This directly seems to include helm and glide binaries, README, etc. for both Linux/64 and Darwin/64. I can't think of any good reason to package these with this repository.

**Comment by pmorie** [comment]
Agree - go for it

**Comment by martinmaly** [comment]
Please make sure make docker still works though -- I am assuming being able to build Docker image of the catalog (and example brokers) is desirable.

**Comment by martinmaly** [comment]
ditto re: 'make init'
