### ISSUE TITLE
How can I verify the `binding` works in walkthrough.md

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-incubator/service-catalog#660]
In https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md , we only show example of the `binding` ready, but how can I verify the `binding` works? i.e. How can I verify that the `binding` can help me talk to the `UPS` broker server?

**Comment by MHBauer** [comment]
I think this is addressed in the walkthrough. The example broker doesn't provide a real service. You can look at the secret that gets created, but there isn't any provisioned service to talk to.

**Comment by gyliu513** [comment]
The walkthrough is difficult to understand, @MHBauer , can you please show more detail for how does the `created secret` related with `UPS broker`?

**Comment by gyliu513** [comment]
Ah, I see, there is a ups controller doing this https://github.com/kubernetes-incubator/service-catalog/blob/master/contrib/pkg/broker/user_provided/controller/controller.go#L125-L138 , so each broker need to have their own controller binging logic.

**Comment by gyliu513** [comment]
I created a PR https://github.com/kubernetes-incubator/service-catalog/pull/662 to help navigate the UPS to its controller which can help people to understand the logic of UPS more clear.
