### ISSUE TITLE
[Question]How to use user-bookstore-client.yaml

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-incubator/service-catalog#675]
I found there have user-bookstore-client yaml file under here: https://github.com/kubernetes-incubator/service-catalog/blob/master/contrib/examples/user-bookstore-client/bookstore.yaml

Does there have any guide to make it run?

And it seems this yaml file required the secret which created after binding success, does there have any steps to create the mysql broker server?

**Comment by pmorie** [comment]
This is part of an old walkthrough and should really be removed.
