### ISSUE TITLE
pprof should be enabled by default for master and controller

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/service-catalog#679]
similar to kube-apiserver and kube-controller-manager, i should be able to get a pprof dump for support purposes for the service catalog api server and controller.

**Comment by MHBauer** [comment]
it is not obvious how apiserver does it, but controller-manager manually registered the mux.

**Comment by MHBauer** [comment]
Looks like maybe `k8s.io/apiserver/pkg/server/options/feature.go#FeatureOptions`.

**Comment by arschles** [comment]
Moving this to 1.0.0 - not necessary to have to reach beta requirements.
