### ISSUE TITLE
Consider running etcd in-process for integration tests

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#685]
The change at https://github.com/coreos/etcd/pull/650 should allow us to run an etcd server inside the integration test process.

**Comment by MHBauer** [comment]
this should be easier now that we're after the 1.6 rebase.

**Comment by fraenkel** [comment]
Can't do it until you go to etcd 3.1.x which has the embed package.

**Comment by arschles** [comment]
Good to know - thanks @fraenkel.

Is there anything right now that provides the REST API but just stores data in-memory, for example?

**Comment by MHBauer** [comment]
Not sure about 'cannot' but probably 'should not'. If we need 3.1, what's the likelihood we get that in a kube v1.6 update vs having to wait 6 months till cube 1.7?

I suppose it is possible we could do a manual pull of 3.1 with glide, but I'm not sure I would advocate for it.

**Comment by MHBauer** [comment]
resolved by #1570
