### ISSUE TITLE
build package on Mac OS shows stat usage error

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-incubator/service-catalog#687]
I build the package on Mac OS and below error will throw:

hchenxa@hchen-mac:~/Documents/hchenxa/src/hchenxa_github/service-catalog$ make build
stat: cannot read file system information for '%c %N': No such file or directory
stat: cannot read file system information for '%c %N': No such file or directory
stat: cannot read file system information for '%c %N': No such file or directory
stat: cannot read file system information for '%c %N': No such file or directory
stat: cannot read file system information for '%c %N': No such file or directory

hchenxa@hchen-mac:~ uname  -a
Darwin hchen-mac.cn.ibm.com 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin

**Comment by MHBauer** [comment]
Root causing this, in my opinion it would be better to entirely get rid of the stat call and let the go compiler do it's job of checking if packages are up to date.
