### ISSUE TITLE
Make TPR integration tests run against a real Core API server

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#693]
Current TPR integration tests use a fake rest API client to mock out the core API server. The TPR tests are mirrors of the etcd based tests, but we had to cut the codepaths for TPR in these tests short because they didn't pass. I'd like us to execute against a real server for two reasons:

1. We won't have to maintain a fake client & keep parity with the real TPR API
2. We can be sure that test failures expose bugs in our TPR storage implementation (not the fake client)

After this is done, we should re-enable all of the tests for TPR storage (the same code that tests etcd) and create one issue (as necessary) for each bug in our TPR storage implementation.

_Note_: @krancour has significant knowledge on what we've done with the fake client and he has done work to begin running a core server in the same process as the tests in https://github.com/kubernetes-incubator/service-catalog/pull/683.

cc/ @pmorie

**Comment by arschles** [comment]
If this is done, #640 should be closed

**Comment by pmorie** [comment]
We should remove this if we adopt #698

**Comment by pmorie** [comment]
Moving this out to the next alpha release for now.

**Comment by arschles** [comment]
Closing in favor of #698
