### ISSUE TITLE
Proposal: How to slice up integration tests vs. E2E and etcd vs. TPR

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#698]
Our current state in the repo is:

- Integration tests
  - Embed a service catalog API server
  - Run etcd in process to test etcd
  - Fake out a REST client to emulate a real API server in TPR
- E2E tests run in jenkins against a real cluster

We have found that the approach of faking a REST client to emulate TPR to be extremely troublesome and difficult.  We have also tried embedding a Kube API server in tests (see #683), which has its own problems.  We also had issues integrating admission controllers in the service catalog API server with the core (see #669).

@derekwaynecarr and I discussed each of these approaches and how we might make them work to allow for TPR coverage in integration tests, and additionally tried running a DIND setup with a real API server, which was just too complex to be viable.  In the end we decided that integrating the core API server, especially TPR, is just too challenging for integration tests.  What we really need is to build out e2e coverage.

So, what we propose is:

1.  Keep existing integration tests basically the same, but do not try to test with the API server backed by TPR in the integration tests.  This eliminates the need to deal with the complexities of TPR and keeps the test conceptually simple.
2.  Push TPR coverage out of integration tests and into E2E tests that run against a real kubernetes cluster
3.  Have an E2E binary that you can run against any catalog/kube API server
4.  Have E2E versions of the clientset and controller tests

**Comment by MHBauer** [comment]
Yay e2es! Should be much easier to reuse some upstream stuff after the rebase. I haven't looked at it.

Since TPRs need a real server, it makes sense that they can only be done with e2e.

**Comment by arschles** [comment]
I am :+1: on this, with the addition that we need to build out more unit coverage for TPR (see https://github.com/kubernetes-incubator/service-catalog/issues/700) as well.

**Comment by derekwaynecarr** [comment]
@sjenning and myself are going to pair up and get an initial stub of an e2e framework put together.

**Comment by pmorie** [comment]
@arschles @krancour any objection to me removing the TPR support in the integration tests?  I'd like to just get that done if we all agree on this.

**Comment by pmorie** [comment]
Do we now think this issue is defunct, @arschles + @krancour ?

**Comment by arschles** [comment]
@krancour has turned integration tests back on for TPR support, so we can close this and continue with our plan as-is for e2e tests. Closing
