### ISSUE TITLE
Add unit tests for the TPR storage interface

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#700]
#699 adds a unit test for the TPR storage interface's `Create` func. This issue is for finish tests for all the rest of the storage interface's functions. Note that we'll need #640 to add watch support to the fake REST client in order to unit test the watch endpoint.

**Comment by arschles** [comment]
Moving to the beta cycle, as @krancour is still in progress on writing tests and fixing issue they uncover.

**Comment by krancour** [comment]
This was addressed collectively by #715, #730, #738, #751, and #752
