### ISSUE TITLE
Jenkins flake: timed out waiting for external IP for catalog API server

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#701]
Present in: https://service-catalog-jenkins.appspot.com/job/service-catalog-PR-testing2/300/console

**Comment by pmorie** [comment]
@kibbles-n-bytes can we close this, now that you requested a quota increase for static IPs?

**Comment by kibbles-n-bytes** [comment]
@pmorie Yes, should be fine.
