### ISSUE TITLE
Porcelain command for relisting broker catalog

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#704]
Created from #627; there should eventually be a porcelain command to relist a broker's catalog.

**Comment by duglin** [comment]
@pmorie could we solve this by adding a "stale" type of flag to Broker such that when set to "true" the controller would requery the broker?

**Comment by duglin** [comment]
#dibs for @jberkhahn

**Comment by MHBauer** [comment]
I think svcat can handle this in both standalone and kubectl plugin mode.
