### ISSUE TITLE
Address Quay security scanner issues.

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/service-catalog#706]
Quay security scanner shows several vulnerabilities for our builds, one such example:
https://quay.io/repository/kubernetes-service-catalog/apiserver/image/95b8cef81ef4107c7124a208ef430a5c04bb361cf2f43a519376f09a2b6a8796?tab=vulnerabilities

**Comment by MHBauer** [comment]
when 0.1.18 or higher is released, this will be solved as we will have a scratch image with binary only.

**Comment by MHBauer** [comment]
using scratch for image now https://github.com/kubernetes-incubator/service-catalog/releases/tag/v0.1.18 shows "unsupported" for scanning result.
