### ISSUE TITLE
User initiated trigger for broker re-list

### ISSUE THREAD

**Issue by jpeeler** [kubernetes-incubator/service-catalog#709]
Users should be able to trigger broker re-list via a command

**Comment by arschles** [comment]
@jpeeler any idea what the command should be?

I think our API should stay as declarative as possible, so I'd like to avoid an imperative command to relist.

**Comment by pmorie** [comment]
I already made an issue for this, look for 'porcelain'.

**Comment by jpeeler** [comment]
Closing this duplicate (see https://github.com/kubernetes-incubator/service-catalog/issues/704)
