### ISSUE TITLE
Fix race condition in reconcileServiceClassFromBrokerCatalog

### ISSUE THREAD

**Issue by rifung** [kubernetes-incubator/service-catalog#710]
Right now we have a race condition in this section of pkg/controller/controller.go (around line 325 as of this writing)

```go
existingServiceClass, err := c.serviceClassLister.Get(serviceClass.Name)
if errors.IsNotFound(err) {
	// An error returned from a lister Get call means that the object does
	// not exist.  Create a new ServiceClass.
	if _, err := c.serviceCatalogClient.ServiceClasses().Create(serviceClass); err != nil {
		glog.Errorf("Error creating serviceClass %v from Broker %v: %v", serviceClass.Name, broker.Name, err)
		return err
	}
```

because between 

```go
existingServiceClass, err := c.serviceClassLister.Get(serviceClass.Name)
```

and

```go
if _, err := c.serviceCatalogClient.ServiceClasses().Create(serviceClass); err != nil {
```

it's possible that the service class would be created elsewhere due to the lack of synchronization.

This is the root cause of #665

**Comment by arschles** [comment]
@rifung can you comment on where exactly that code is found?

**Comment by rifung** [comment]
@arschles absolutely I've updated the original comment to point out where the code is

**Comment by arschles** [comment]
thanks @rifung!

**Comment by rifung** [comment]
#dibs

**Comment by arschles** [comment]
Moving to the beta cycle, as this is still in progress.

**Comment by arschles** [comment]
Moved to 0.0.5

**Comment by vaikas-google** [comment]
So, the one question I had this is that with the introduction of the queues, we should have the guarantee that a single broker _instance_ is being reconciled at a time, so there should be no races between a single broker. However of course if two brokers have the same service class that could still be a problem. Or, am I missing what the race here pertains to?

**Comment by arschles** [comment]
Moving to 0.0.6 for now. @vaikas-google I'll have to look again at how the code in question has changed since this was filed.

**Comment by pmorie** [comment]
I am not convinced this is still a bug.  I vote to close this unless someone can prove to me that we still ahve an isseu

**Comment by arschles** [comment]
I am closing this, as I believe the logic described herein is done in a queue.
