### ISSUE TITLE
Bug: controller fatal error `unknown flag: --broker-relist-interval`

### ISSUE THREAD

**Issue by ultimateboy** [kubernetes-incubator/service-catalog#713]
I'm attempting to install the latest service catalog and I'm receiving the following fatal error from the controller container:
```
unknown flag: --broker-relist-interval
```

I deployed using:
```
$ helm install charts/catalog \
--name=service-catalog \
--set apiserver.storage.type=tpr,\
apiserver.insecure=true,\
apiserver.storage.tpr.globalNamespace=catalog\
 --namespace=catalog
```

Based on the default values in `values.yaml`, the controller image used was:
`quay.io/kubernetes-service-catalog/controller-manager:v0.0.3`

**Comment by arschles** [comment]
https://github.com/kubernetes-incubator/service-catalog/pull/707 caused this, because the `canary` (and what will become the `v0.0.4` release) version supports this flag, but `v0.0.3` does not. Can you use the chart in the `v0.0.3` tag of this repo for now?

**Comment by ultimateboy** [comment]
Thanks @arschles - that gets me up and running.
