### ISSUE TITLE
helm chart assumes a more recent version of the controller-manager than the default image

### ISSUE THREAD

**Issue by kibbles-n-bytes** [kubernetes-incubator/service-catalog#716]
The helm chart tries to pass the `--broker-relist-interval` parameter to the catalog, but this functionality was added after `v0.0.3`, which is the default image specified by `values.yaml`, so the controller-manager crash loops.

**Comment by kibbles-n-bytes** [comment]
Not really sure whether to call it a `bug` or not, but strange behavior regardless.

**Comment by ultimateboy** [comment]
Duplicate of https://github.com/kubernetes-incubator/service-catalog/issues/713

**Comment by kibbles-n-bytes** [comment]
Ah, didn't notice that one was the same, thanks. Closing!
