### ISSUE TITLE
TPR `GuaranteedUpdate()` cannot update existing object.

### ISSUE THREAD

**Issue by simonleung8** [kubernetes-incubator/service-catalog#720]
_Note: this is part of a meta issue: #600_

We always [set the version to 0](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/storage/tpr/storage_versioner.go#L92) during updating an object, which will result in creating a new object instead. There are times we need to update an existing object. For example, calling delete on the object will result in updating the `DeletionTimestamp` on the existing object. 

We have not seen this bug because deleting a TPR object through our api-server is currently broken.

**Comment by arschles** [comment]
This is related to #600

**Comment by arschles** [comment]
Related to #723

**Comment by vaikas-google** [comment]
@krancour and did your PR: https://github.com/kubernetes-incubator/service-catalog/pull/738 do anything here.

**Comment by krancour** [comment]
GuaranteedUpdate is _completely_ rewritten with code from the upstream etcd3-backed storage used as a template of sorts. All (unit) tests are passing. @simonleung8 if you can document steps to follow to re-create this issue, I'd be interested in attempting them against the new implementation to see if the problem has been fixed or not. My gut says it has been.

**Comment by arschles** [comment]
Moving to 0.0.6 for now. @simonleung8 can you give some repro steps that @krancour asked for?

**Comment by simonleung8** [comment]
The [part](https://github.com/kubernetes-incubator/service-catalog/pull/738/files#diff-b92a348abc487b2ee1914b995cb44860L93) that contributed to the bug is completely rewritten. We can close this bug if we can delete an existing TPR resource (which is actually an update).

**Comment by krancour** [comment]
According to the unit tests, we can. I will be trying to re-enable integration tests for tpr-backed storage today and will also try to complete the walkthrough using tpr-backed storage. I will hold off on closing this, pending those activities giving me some sort of verification that this is addressed. I'm going to assign this issue to myself, so consider this issue my problem.

**Comment by arschles** [comment]
As of this writing, the `canary` builds can update non-namespaced resources

**Comment by arschles** [comment]
Additionally, I have now run the walk-through using `dc73f2b` api server and controller images, and have verified that updates work. However, since this update function is used for deletes, I am leaving this issue open for now.

cc/ @krancour

**Comment by arschles** [comment]
Moving to 0.1.0 as this has not been completed

**Comment by arschles** [comment]
Moving to 0.1.0, as #836 is not yet finished
