### ISSUE TITLE
Verify service-catalog OpenAPI config is properly configured

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/service-catalog#721]
The generic machinery has options for configuring OpenAPI but a quick glance at the code appears to me to not do any special case wiring by default if less unspecified.

I believe service-catalog API server should be enabling the following:

```
genericConfig.OpenAPIConfig = genericapiserver.DefaultOpenAPIConfig(openapi.GetOpenAPIDefinitions, api.Scheme)
genericConfig.OpenAPIConfig.PostProcessSpec = postProcessOpenAPISpecForBackwardCompatibility
genericConfig.OpenAPIConfig.SecurityDefinitions = securityDefinitions
```

but we need to understand if that is required when we are using the aggregator.

**Comment by MHBauer** [comment]
We have openapi code being generated. Openapi is behind a flag, but being served with #1612.
