### ISSUE TITLE
service-catalog API server needs to return proper values for /version endpoint

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/service-catalog#722]
for reference, every kube style api server supports a `/version` endpoint.

for example:

```
$ kubectl get --raw /version
{
  "major": "1",
  "minor": "7+",
  "gitVersion": "v1.7.0-alpha.1.408+c5cbecc4547e33-dirty",
  "gitCommit": "c5cbecc4547e33cb72dc3372043abfd22d6cbdce",
  "gitTreeState": "dirty",
  "buildDate": "2017-04-13T19:13:16Z",
  "goVersion": "go1.7.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

after #669 merges, we will have a placeholder values for version info that we need to populate out of a build step.

```
{
  "major": "",
  "minor": "",
  "gitVersion": "v0.0.0-master+$Format:%h$",
  "gitCommit": "$Format:%H$",
  "gitTreeState": "not a git tree",
  "buildDate": "1970-01-01T00:00:00Z",
  "goVersion": "go1.7.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

we need to fill git version, tree, commit, and build date.  major and minor versions are deprecated.  the compiler and platform and go version will just work.

**Comment by MHBauer** [comment]
Is there something we can pull from repo-infra or elsewhere to help us? If it's a common format we want to support there needs to be common infrastructure to support it.
