### ISSUE TITLE
serveral tpr-backed storage methods ignore resource version argument

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#723]
_Note: this is part of a meta issue: #600_

**Comment by arschles** [comment]
See https://github.com/kubernetes-incubator/service-catalog/pull/715/files#r112508069 for context

**Comment by arschles** [comment]
Related to #720

**Comment by vaikas-google** [comment]
@krancour Did your PR: https://github.com/kubernetes-incubator/service-catalog/pull/738 address this issue?

**Comment by krancour** [comment]
@vaikas-google nope. @arschles you were just asking me about this. This PR is probably still relevant. We should compare to the etcd3-backed storage impl upstream and see _what_ they do with that arg and see if we can do something similar with tpr-backed storage. It's also within the realm of possibility that whatever the etcd3-backed impl is doing with this cannot be replicated within the limits of tpr-backed storage, but we'll have to dig in to find out.

**Comment by arschles** [comment]
Moving to 0.0.6, we'll address there

**Comment by arschles** [comment]
Related to #600, because deletion fails due to failure to update the resource version

**Comment by arschles** [comment]
Moving to 0.1.0 as this has not been completed

**Comment by arschles** [comment]
Moving to 0.1.0, as #836 is not yet finished
