### ISSUE TITLE
Refactor to a single Makefile

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#73]
Currently there appears to be a Makefile for each go package in the project.  This is not really sustainable and adds overhead to refactors.  Packages should be buildable with `go build`, and there should be a single make target (in kubernetes, we call this `make all`) that builds all the go packages in the project.

**Comment by krancour** [comment]
@pmorie I both agree and disagree with this. Makefile per package certainly does sound bad, but I think what's really going on here is a Makefile per distinct component or binary, and that does make some sense to me.

**Comment by martinmaly** [comment]
I'll try to summarize how, and why, we ended up with the current setup. At first we had only 'go build' setup. The downsides were:
- default package (and binary) names go build picks
- no support for Docker image build, in-docker build etc.

Doing some research I kept coming across examples of single-Makefile setups which only had a single binary per repo (so it wasn't quite a fit for our needs, having multiple binaries, Docker images etc.).

So after some trial, error, and incremental reduction in boilerplate I managed to figure out a way where each binary component only contributes few basic things and rest is delegated to shared include makefiles. I found particularly desirable the ability to build individual artifacts -- I have come across attempts to optimize makefiles to correctly spell out target dependencies but it is not pretty, so one way to enable build of individual binaries (and faster builds) is to enable 'make build' or 'make test' in that component's directory

I am not opposed to improvements, nor am I against single-makefile setup if it can allow for
- controlling of binary names
- docker, in-docker builds, coverage, test, ...
- build of all packages at once, or with a finer granularity (and with a simple mnemonic such as 'make build-controller' or some such)

I sense it may be doable to achieve this, perhaps by structuring the top makefile as:

BIN=xxx-bin
PKG=xxx-pkg

include "boilerplate.mk"

BIN=yyy-bin
PKG=yyy-pkg

include "boilerplate.mk"

...

but as I try to imagine what the boilerplate.mk would look like, I am seeing something quite gnarly.

**Comment by krancour** [comment]
fwiw, I have been down the same road that @martinmaly is describing. It isn't a trivial proposition to avoid DRY exceptions where the commonalities among the builds for n > 1 components in a single repo are concerned while _also_ allowing each build to be adequately customized for each component's needs.

> So after some trial, error, and incremental reduction in boilerplate I managed to figure out a way where each binary component only contributes few basic things and rest is delegated to shared include makefiles.

That is generally where I have landed after similar attempts on other projects.

I think that what I'd propose here is that we let this issue sit for now-- let the current build process marinate for a bit while we all get accustomed to it. We can continue to improve it incrementally, but any big refactoring such as what's proposed here should probably occur only after we all have the benefit of greater familiarity on our side.

**Comment by pmorie** [comment]
We don't have to do this right now, but it will have to happen naturally as the codebase expands.

**Comment by pmorie** [comment]
@krancour @martinmaly k8s has a system that allows you to:

1.  Build many or single individual binaries from a single makefile; example: `make all WHAT=cmd/hyperkube`
2.  Deterministically give generated binaries the names you desire
3.  Not worry about makefiles for individual packages (which is my biggest motivation, I think that is a very strong anti-pattern smell, personally)
4.  Supports local and in-docker build

I think this is an area that has been explored thoroughly upstream -- why doesn't one of you (or both of you) own this and do some investigation upstream?

**Comment by pmorie** [comment]
Walking the chain of how the local build works in Kube:

1.  [Makefile:85](https://github.com/kubernetes/kubernetes/blob/master/Makefile#L85)
2.  [hack/make-rules/build.sh:27](https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/build.sh#L27)
3.  [hack/lib/golang.sh:466](https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L466)

Docs on docker build: http://releases.k8s.io/HEAD/build-tools/README.md

**Comment by krancour** [comment]
@pmorie something that concerns me a little bit here is that the volume and complexity of build-related scripts in k8s is a bit of a put-off (for me, personally, at least). I know we have all agreed to be like k8s wherever possible, but I have to ask whether we objectively believe that the way k8s does this is ideal. (This is not at all to say that what we're doing now is any better.) The bottom line is I'm looking for some defense for why the way k8s does it is the _right_ way. I'm not opposed to putting some of my own effort into this as long as we can all agree we're heading in the right direction.

**Comment by krancour** [comment]
Let me amend the statement above to say that I have an appreciation (a fondness even) for k8s' approach to this. If we can take the same approach, but pare it down to the essentials, I would be ok with it.

**Comment by krancour** [comment]
This was closed by #182
