### ISSUE TITLE
service-catalog polling is too short

### ISSUE THREAD

**Issue by jmrodri** [kubernetes-incubator/service-catalog#733]
During an async operation, the service-broker will poll 30 times every second resulting in a 30 second poll. Our broker is provisioning things that take 10 minutes, but could take as long as an hour.

```
	pollingIntervalSeconds = 1
	pollingAmountLimit     = 30
```
[lines 48-49](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/brokerapi/openservicebroker/open_service_broker_client.go#L48-L49)

```
	for i := 0; i < pollingAmountLimit; i++ {
		glog.V(3).Infof("Polling broker %v at %s attempt %v", c.name, pollingURL, i+1)
		pollResp, err := sendOSBRequest(c, http.MethodGet, pollingURL, pollReq)
		if err != nil {
			return err
		}
		defer pollResp.Body.Close()

		lo := brokerapi.LastOperationResponse{}
		if err := util.ResponseBodyToObject(pollResp, &lo); err != nil {
			return err
		}

		switch lo.State {
		case brokerapi.StateInProgress:
		case brokerapi.StateSucceeded:
			return nil
		case brokerapi.StateFailed:
			return errFailedState
		default:
			return errUnknownState
		}

		time.Sleep(pollingIntervalSeconds * time.Second)
	}
```
[lines 309-333](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/brokerapi/openservicebroker/open_service_broker_client.go#L309-L333)

**Proposal**
I propose that we increase these to something more appropriate:

```
	pollingIntervalSeconds = 6
	pollingAmountLimit     = 600
```

**Comment by MHBauer** [comment]
Poll 30 times total, one time with a one second pause.

I think this is another chance to reuse the `util/wait` pkg.

There was talk or a comment or an issue somewhere that this should be configurable somehow.

I'm really curious about what service takes an hour to provision.

**Comment by arschles** [comment]
cc/ @vaikas-google, since he is working on #717 and #248

**Comment by arschles** [comment]
I would recommend we add command line flags so that an operator can set custom values.

**Comment by vaikas-google** [comment]
@jmrodri Did #717 fix the problem sufficiently that we can close this issue?

**Comment by arschles** [comment]
Moving to 0.0.6

@jmrodri let us know if #717 fixes the problem sufficiently for your needs

**Comment by jmrodri** [comment]
@arschles @MHBauer yes #717 addressed this issue. I will close it as resolved.
