### ISSUE TITLE
Publish helm charts to a helm repo

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#735]
This is a follow up to https://github.com/kubernetes-incubator/service-catalog/pull/728#discussion_r112563258

Currently, we reference version-tagged images in our helm charts, not `canary`. This keeps our walk-through stable, but long-term I'd like to see us treat our helm charts as published artifacts just like our docker images.

This issue is for the following:

1. Publish helm charts to a helm repo, just like we publish images to quay (iirc, quay now can host helm charts - I don't know any more details right now)
2. Change the image tags in our helm charts back to canary
3. Modify the walk-through to point to the versioned helm charts in the helm repo

**Comment by arschles** [comment]
This is not necessary for 0.1.0, moving to 1.0.0

**Comment by arschles** [comment]
See https://github.com/kubernetes-incubator/service-catalog/issues/1129 for additional discussion

**Comment by MHBauer** [comment]
Is https://kubeapps.com/ the correct place?

**Comment by MHBauer** [comment]
maybe https://github.com/kubernetes/charts but in incubator for now.

**Comment by viglesiasce** [comment]
Hey folks!

Charts maintainer here. 

We don't currently have the ability to add charts to the main Charts repositories (stable/incubator) without the source living in our repo. That said, plans are in motion to figure out a methodology for it.

Would you be willing to have a snapshot of the chart from this repo added to kubernetes/charts and updated/synced periodically until we figure out delegation?

**Comment by duglin** [comment]
@viglesiasce how are they versioned/tagged in that repo?

**Comment by viglesiasce** [comment]
You can choose the versioning scheme you'd like. 

Generally folks use the `appVersion` field of the Chart.yaml to denote the relevant software version and the `version` field to denote the revision of the chart it self. 

The [Istio chart](https://github.com/kubernetes/charts/tree/master/incubator/istio) has decided to use $appVersion-chart$chartversion (0.2.6-chart1) in order to keep things more in sync for users. Inevitably there will be changes to the chart that don't coincide with any application version change so its hard to keep them fully in sync.

**Comment by duglin** [comment]
Sorry, I wasn't clear. If we want to push v0.0.23 of the helm charts into the k9s/charts repo we can put v0.0.23 into the yaml but is there a mechanism for someone to pull down the v0.0.22 version w/o having to try to find which commit was associated with v0.0.22 ?

**Comment by viglesiasce** [comment]
Ah yes all old versions live on. You can always do a `helm install stable/service-catalog --version  0.0.22`.

**Comment by MHBauer** [comment]
Sync on version tag sounds good to me.

**Comment by pmorie** [comment]
I'd be happy to do a snapshot - assuming we can have a script or something to do it during the release process.

**Comment by viglesiasce** [comment]
It would need to submit a PR to the kubernetes/charts repo (and possibly ping a maintainer via comment).

Sound reasonable?

**Comment by arschles** [comment]
I agree RE the way to do chart versioning, but I don't want us to copy our chart into kubernetes/charts while we're in beta. It makes more sense for us to own the helm repository at this point, and that means uploading to an HTTP server. GCS or Azure blob storage make most sense at the point because Google and Microsoft are represented in this group.

kubernetes/charts itself has a [script](https://github.com/kubernetes/charts/blob/master/test/repo-sync.sh) to do this upload for the official repository (they use GCS). I'm suggesting we do this for our own repository for now.
