### ISSUE TITLE
Support plan updates for Instances

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#748]
We currently do not correctly support plan update to Instances correctly from what I can tell.  We should:

1.  Only allow changes to the `PlanName` field of `InstanceSpec` if the `ServiceClass` is plan-updatable (sounds like an admission controller to me)
2.  Send the prior plan ID correctly (this is something that it is not yet obvious to me how we should solve in the API - seems like the admission controller could be responsible for setting a field, perhaps in an `UpdateParameters` field on the spec that the controller could then clear)

**Comment by pmorie** [comment]
Adding this for 0.1.0 because it seems like it should be done before beta.

**Comment by arschles** [comment]
We believe that this can be solved w/o any API surface changes, so I am moving this out to 1.0.0

**Comment by pmorie** [comment]
Part of this change: #869

**Comment by pmorie** [comment]
Setting the milestone to 0.1.0 because it was scoped to beta in #1098

**Comment by pmorie** [comment]
Closed by #1289
