### ISSUE TITLE
Secret generated from a binding should have a reference to the binding

### ISSUE THREAD

**Issue by jwforres** [kubernetes-incubator/service-catalog#750]
When a binding object is created and then a secret is generated for that binding, that secret should have to reference back to its binding.  This is so clients can choose to warn users that try to directly delete the Secret without removing the binding.

**Comment by jwforres** [comment]
cc @pmorie

**Comment by MHBauer** [comment]
I think this is handled now by this owner reference on the created secret. https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.21/pkg/controller/controller_binding.go#L479-L481
