### ISSUE TITLE
Controller only updates an Instance's status, but not its spec

### ISSUE THREAD

**Issue by luksa** [kubernetes-incubator/service-catalog#761]
Judging from the code, the controller only updates the Instance's status during provisioning. The newly added async support, for example, sets the `spec.OSBLastOperation`, but never actually posts the update to the API server.

Also, the `spec.OSBDashboardURL` is never stored (neither for sync, nor async broker responses).

**Comment by luksa** [comment]
I've just noticed #757, which makes half of this issue moot. But it still applies to the `OSBDashboardURL`.

**Comment by luksa** [comment]
I can move it to `status` myself. Just need someone to give me the go-ahead.

**Comment by pmorie** [comment]
@luksa thanks a lot :-)
