### ISSUE TITLE
Proposal: Eliminate GCR bias

### ISSUE THREAD

**Issue by krancour** [kubernetes-incubator/service-catalog#77]
This replaces #67 

The `docker` (Docker build) and `push` (Docker push) `make` targets currently require either a GCP project ID or GCR repository URL to be provided. The `docker` target uses this information when tagging images that are subsequently pushed by the `push` target, however, I propose this bias toward GCR is a hindrance for anyone wishing to use another Docker registry-- Docker Hub, quay.io, a local registry, or other.

Why this is important: The beauty of Docker and k8s is that they run on most any platform, yet give you (more or less) a uniform experience across those many platforms. Expressing a bias toward one vendor in particular harms the developer experience by raising the barrier for entry vis a vis project contribution by requiring familiarity with and a budget for the vendor in question. i.e. What if I have no money and want to push images to a local registry that my minikube can pull from?

What I'd like to propose is we adopt something similar (not necessarily identical) to how we have long managed this issue at Deis. At Deis, all our build processes respect an environment variable `DEIS_REGISTRY`. When building and tagging images, the image's unqualified name (a component name like "router" or "controller") is prefixed with the value of the `DEIS_REGISTRY` environment variable so that a subsequent push uploads the image to the user-specified location.

I would further propose that we maximize the simplicity of this equation by _not_ building in any specific support for authenticating to registries. I propose instead that we simply document the requirement that anyone using the `push` target must already be authenticated to whatever registry it is they intend to push to.

**Comment by martinmaly** [comment]
what exists in the makefiles today is actually very close. Makefile will respect [GCR variable](https://github.com/kubernetes-incubator/service-catalog/blob/master/script/Makefile.mk#L48) which can be easily renamed to REGISTRY. The bias in this case is:
- the name of the variable
- default value (if the value is not supplied)

another bias is use of gcloud (reason is auth) which can be replaced by some other technique (@krancour proposes an acceptable one) without loss of usability.

I'd say we are probably quite close to @krancour proposal already, which is good news.

**Comment by krancour** [comment]
@martinmaly it had not occurred to me that the bias might (partly?) be only in the name of the variable. That is encouraging news.

**Comment by martinmaly** [comment]
That, and the use of gcloud for docker push (I hope that's all of it).
