### ISSUE TITLE
Document all the resources like k8s does

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/service-catalog#78]
We should document all the resources like k8s does, for example Pods:
http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_pod

**Comment by pmorie** [comment]
Completely agree.  k8s uses a swagger API generator for this, which uses the godoc on the resource types for input.  I would love for someone to own making this happen in this repo.

**Comment by pmorie** [comment]
Related:
- #339 
- #349

**Comment by pmorie** [comment]
I'm going to close this now, since we generate this information.  I do think it would be awesome to host it somewhere; created https://github.com/kubernetes-incubator/service-catalog/issues/453.
