### ISSUE TITLE
Adding MySQL broker to service catalog

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-incubator/service-catalog#786]
We have an example here https://github.com/hchenxa/daily_work/tree/master/kubernetes/service-catalog and want to contribute to service catalog.

Can we put all the works related to MySQL under https://github.com/kubernetes-incubator/service-catalog/tree/master/contrib ?

**Comment by gyliu513** [comment]
I also post a question here and want to get some comments for where to put some 3rd party brokers https://groups.google.com/forum/#!topic/kubernetes-sig-service-catalog/RbChgi5hOyc

**Comment by mdshuai** [comment]
Where's the source code of your MySQL broker now?

**Comment by krancour** [comment]
@gyliu513 it's awesome to see growing interest in creating brokers! That said, we don't intend for broker code to be kept in this repository. The one broker you see currently under `contrib` exists only to facilitate tests and walkthrough, so it's deliberately tracked along with service catalog code. In all other cases, brokers should be kept in their own repositories.

**Comment by krancour** [comment]
I don't expect any disagreement from other maintainers on this subject, so I am going to close this. @gyliu513 please still feel free to re-open this or comment further if you feel this is inadequately addressed. Thanks!

**Comment by gyliu513** [comment]
@krancour I post a question here https://groups.google.com/forum/#!topic/kubernetes-sig-service-catalog/RbChgi5hOyc .

It is difficult to use service catalog without enough examples and service brokers. One example is helm, the helm is not only maintaining a helm repo, but also a chart repo to host some charts for helm so that the enduser can use those charts easily.

But for service catalog, there is no such repo and also not enough examples for how to use service catalog, without examples and service brokers, it is difficult for people to put service catalog into production. comments?

**Comment by krancour** [comment]
There are many brokers out there "in the wild." They've been written for use with Cloud Foundry, but they will work just fine with the k8s service catalog as well. You may wish to adapt such brokers for use in k8s by authoring Helm charts for them and submitting those as PRs to the [kubernetes/charts](https://github.com/kubernetes/charts) repo.

**Comment by krancour** [comment]
If you're asking whether the k8s service broker intends to host its _own_ Helm charts repository... that's not at all on our radar.

**Comment by gyliu513** [comment]
So my question is with service catalog, how can I integrate with local oracle, MySQL, Hadoop etc? Where can I get some reference and help to integrate service catalog with external services? There is only one ups example and I think it is not enough.

**Comment by krancour** [comment]
First thing's first. Do brokers exist for all of those things? If so, are they already deployable to k8s? i.e. Are Helm charts available?

**Comment by gyliu513** [comment]
Yes, I already have a MySQL broker [here](https://github.com/hchenxa/cf-mysql-java-broker) and also [some test steps](https://github.com/hchenxa/daily_work/tree/master/kubernetes/service-catalog), I can covert the test steps to charts if needed. Comments?

Basically, I want to put all of the source code for MySQL [here](https://github.com/kubernetes-incubator/service-catalog/tree/master/contrib) and create a chart for MySQL [here](https://github.com/kubernetes-incubator/service-catalog/tree/master/charts).

I think the final goal for service catalog should put all charts and service brokers to a separate repo like where helm host its charts.

**Comment by krancour** [comment]
I will say again, this repo is not the right place to put broker source and Helm charts. Broker source code belongs in its own repo. The charts can be contributed to kubernetes/charts. I'm not sure what isn't clear.
