### ISSUE TITLE
helm deploy will fail when k8s enable rbac

### ISSUE THREAD

**Issue by mdshuai** [kubernetes-incubator/service-catalog#789]
Now there is a know issue for helm deploy with enable rbac in k8s, Need doc what's mini helm version we should use when the issue https://github.com/kubernetes/helm/issues/2224 fixed, or provide a walk around for rbac env.
```
# helm install charts/catalog --name catalog
Error: release catalog failed: the server does not allow access to the requested resource (post namespaces)
```

**Comment by MHBauer** [comment]
@mdshuai if this is still a problem, please reopen.
