### ISSUE TITLE
What value should we use for appID?

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#798]
See: https://github.com/openservicebrokerapi/servicebroker/issues/183

Right now we populate the app_guid with the namespace UID.  Actually we populate the org and space with that value too.  I'd recommend that we populate the app_guid with something more unique - for example, perhaps a hash of the namespace+labelSelector of the PodPreset. Just something that allows us to give the broker something close to a unique pointer representing the scope of the binding.  As I mentioned in the referenced issue, brokers may want to perform some kind of check (like not allowing the same app to bind to the same instance more than once), and w/o some kind of attempt at using a meaningful value for app_guid that represents the scope in which we expect the creds to be used I don't think the broker will be able to perform those checks.

**Comment by pmorie** [comment]
I think we need some information about how this is used to determine what we should send.  AFAIK this is used for charge-back for paid services by the broker, and so we should send something stable.

**Comment by duglin** [comment]
Based on today's call I think we may consider this putting whatever information we use in the binding to identify "the app" (e.g. podpreset labelSelectors) into the bind_resource jsonObject of the binding request - but we'd need to check to see if the spec allows for this. As for the app_guid itself, we could choose to either exclude it, since its optional, or use some unique/related UID from Kube, like the OSB GUID of kube Binding resource.  If we use the binding OSB GUID as the name of the binding too then it would make searching by app_guid easy too - for those cases where the broker calls back into the platform.

If we agree with this general approach then we could implement this post-v0.1.0 and its a non-blocker for beta.  But let's discuss this tomorrow.

**Comment by MHBauer** [comment]
Are you proposing to use `bind_resource.app_guid` specifically? Or a new entry under `bind_resource`?

**Comment by duglin** [comment]
I assume you closed this by mistake

**Comment by arschles** [comment]
I'm moving this to 0.2.0. We believe that it won't be changing the API surface, but we'd like this question answered as soon as we can

**Comment by duglin** [comment]
Based on our decision in https://github.com/kubernetes-incubator/service-catalog/issues/818 to continue to use the namespace GUID for app_guid I'm going to close this issue and we can reopen it if new data pops up.
