### ISSUE TITLE
Broker update semantics

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#801]
See: https://docs.cloudfoundry.org/services/managing-service-brokers.html 

In particular I think we need to discuss:
- purging brokers, instances and bindings - meaning deleting them w/o calling the broker
- re-getting a broker's marketplace and services/plans vanish - need to deal with the case of existing instances/bindings of those removed resoures (see "Catalog Validation Behaviors" section)

CF has the notion of marking things as "inactive" - this allows for services and instances to still be known to the system but additional uses of the resources are banned. Then as those uses are deleted, when no one else is using it, the system will eventually delete the resource.

I'm marking this as v0.1.0 because I think we need to have some initial design discussions around these prior to locking down the resource model in case we think the changes need to support these flows are not just additive.  It could be as simple as adding an "inactive" flag to plans (and perhaps to services), but we should discuss.

**Comment by duglin** [comment]
Note this one is about updating and removing plans/services. I'm opening another one to focus on name changes.

**Comment by arschles** [comment]
This issue recalls our discussion in our last face-to-face meeting in Boulder, about what `kubectl delete broker` or `kubectl delete instance` should do. Here's what we decided, for reference:

- `kubectl delete broker $BROKER` should fail by default if there are any bindings to `Instance`s of `ServiceClass`es for the broker in question
    - Users can force deletion, however, which triggers an unbind on all of the bindings in question
- `kubectl delete instance $INSTANCE` should fail by default if there are any bindings on that instance
    - Similar to the broker case, users can force deletion, which triggers unbinds on all bindings in question
- We did not discuss what happens if a user deletes a `ServiceClass`

I believe we can adapt these decisions to the two cases. When a plan or service is removed (either by the broker or an operator), we can simply "fail" as above, but still delete (or soft-delete, and then garbage collect) it from the in-cluster catalog (i.e. a list of `ServiceClass`es) so that users can't create new bindings or instances on the removed services/plans.

I also believe there should be a command-line flag on the controller to trigger cascading unbinds (i.e. the "force" model from above) that automatically shuts down access to all apps that are bound to an instance of a service/plan that is removed. This would be especially useful for dev clusters.

**Comment by duglin** [comment]
In general I agree, but a couple of points:  we can't "fail" a delete from a broker - its a done deal. The broker removed it from its catalog so we need to take an appropriate action.  And yes I agree the appropriate action is the soft-delete, or marking it as inactive.  As for a delete from the user, I think failing if its in-use is best, not a soft-delete - unless they specify "--force" then we cause havoc :-)

**Comment by arschles** [comment]
>we can't "fail" a delete from a broker - its a done deal. The broker removed it from its catalog so we need to take an appropriate action

I'd like to allow the service-catalog operator to specify what the appropriate action is. For example, some brokers may remove services/plans from their catalogs, but don't actually "delete" (i.e. shut down access to) the resource, so in that case we'd want to leave the binding alone. That overall behavior would be more appropriate for a prod cluster.

>As for a delete from the user, I think failing if its in-use is best, not a soft-delete - unless they specify "--force" then we cause havoc :-)

:+1:

**Comment by duglin** [comment]
See https://docs.cloudfoundry.org/services/managing-service-brokers.html#catalog-validation - the last row- I think it makes sense.  So yeah we don't touch existing instances/bindings we just block new ones from being created.

**Comment by pmorie** [comment]
Related to https://github.com/kubernetes-incubator/service-catalog/issues/705

**Comment by duglin** [comment]
marking as 'api' so we can have an initial design discussion to make sure we plan on solving this via additive things.  I'm hoping we can agree on something as simple as adding an "inactive" flag to plans and serviceClasses.

**Comment by duglin** [comment]
For the case of:
> re-getting a broker's marketplace and services/plans vanish - need to deal with the case of existing instances/bindings of those removed resoures (see "Catalog Validation Behaviors" section)

my proposal is:
- upon the refresh of a broker's catalog if a plan vanishes then:
  1) if there are no instances using that plan then delete it
  2) if there are instances using that plan then mark the plan as "inactive" so that no new uses of that plan will be allowed.  Existing bindings using that plan are not impacted and should still work as before.
- when a new instance is created check to see if the plan is marked as "inactive" and if so then fail the request.

- upon the refresh of a broker's catalog if a service vanished then:
  1) if there are no instances of that service then delete it
  2) if there are instances using that service then mark the service as "inactive" so that no new uses of that service will be allowed. Existing instances/bindings related to that service are not impacted and should still work as before.
- when a new instance is created check to see if the service is marked as "inactive" and if so then fail the request.

Based on previous design sessions the "inactive" flag might actually be the "deleted timestamp" field since that will just mark it for deletion w/o actually doing so until all uses of that resource are also removed.  But I'll leave that as an impl detail for now.

Related: https://github.com/kubernetes-incubator/service-catalog/issues/820

**Comment by pmorie** [comment]
I am basically supportive of @duglin's comment here: https://github.com/kubernetes-incubator/service-catalog/issues/801#issuecomment-317755962

I would suggest that we have a flag on the spec for `Inactive` - there is similar precedent in other API resources ('paused' in deploymentspec).

**Comment by pmorie** [comment]
also, I would be happy to have a porcelain command that you ran manually to clean up classes/plans that are inactive but no longer have instances created.

**Comment by pmorie** [comment]
@eriknelson has expressed interest in writing up a design proposal on this.

**Comment by eriknelson** [comment]
I meant to indicate I was looking at a proposal for #705, which was published yesterday as #1086, so I'm not actively working on this currently if someone else is interested.

**Comment by duglin** [comment]
On Aug7th we agreed with the design proposal.
