### ISSUE TITLE
Make the k8s-bot run against this repo

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#803]
The k8s-bot machinery provides some useful features that we should make use of here:

1.  Automatic management of the 'needs-rebase' label
2.  Commands to manage assignees and labels, and CI
3.  Control over merge of PRs when some conditions are met (we might have to do some coding to use this with our process)

This has long been a goal but we have had bigger fish to fry.  This might be a good starting point for someone looking to get involved with the project.

**Comment by pmorie** [comment]
I've put the meta label on this for now but this is likely to be a precondition of exiting incubation.

**Comment by MHBauer** [comment]
Who do we talk to about this? Do we need to run it ourselves? I am interested, but I do not even know where to start.

**Comment by pmorie** [comment]
@eparis at one point you were managing a lot of this stuff -- are there any docs on it on how to get started, or just oral history so far?

**Comment by eparis** [comment]
I know how to get the k8s-merge-robot up. But that's only 1/2 of the tooling. We also need/want prow. And I don't have a clue how to get it up.

@rmmh @grodrigues3  @spiffxp  might all be able to help or point to who can help.

**Comment by spiffxp** [comment]
@eparis I'm not sure about the need-rebase label, that may be mungegithub; things like assigning and labeling via commands/mentions are handled by prow, configured via PR's to plugins.yaml
- https://github.com/kubernetes/test-infra/tree/master/prow#how-to-enable-a-plugin-on-a-repo
- https://github.com/kubernetes/test-infra/blob/master/prow/plugins.yaml

kubernetes-incubator as a whole should already have /assign available to it

**Comment by spiffxp** [comment]
so, there's that, feel free to ping #kubernetes-sig-testing in slack as well

**Comment by grodrigues3** [comment]
@spxtr can probably help get prow setup

**Comment by spxtr** [comment]
Prow is already running against the kubernetes-incubator org. The plugins are defined [here](https://github.com/kubernetes/test-infra/blob/8a08395258874fbb557ce6d0baae6b2f13869b45/prow/plugins.yaml#L24-L36). Feel free to open a PR enabling the rest if you'd like.

**Comment by eparis** [comment]
cool, I didn't realize prow was already up. I'll try to get the merge bot up this week...

**Comment by pmorie** [comment]
Are there any docs on how to set this stuff up?

**Comment by pmorie** [comment]
Disregard last comment, reading prow docs now.

**Comment by eparis** [comment]
what github status do you want to be true before it can merge a PR?
continuous-integration/travis-ci/pr ? anything else?

**Comment by eparis** [comment]
do you want to allow the 'big green button' or only via the submit queue? probably best to leave the button for now, but we can turn it off like in kube/kube once this is working.

**Comment by MHBauer** [comment]
`Prow is already running against the kubernetes-incubator org.`

What does this mean to me? Is there anything in-repo that needs to be done? If there is something going on outside of the repo, I would like to know about it.

**Comment by spxtr** [comment]
> What does this mean to me? Is there anything in-repo that needs to be done? If there is something going on outside of the repo, I would like to know about it.

It means that, should you choose to, you can easily set up test jobs and other such lovely things on this repo by making a PR to kubernetes/test-infra. Similarly, if you want `/lgtm` and the like to work, you should do the same. Currently on the CLA plugin and `/assign` are enabled on kubernetes-incubator.

**Comment by MHBauer** [comment]
https://github.com/kubernetes/test-infra/issues/8291

**Comment by BenTheElder** [comment]
/cc
Attempting to help with this, along with @cjwagner.
