### ISSUE TITLE
Make it possible to add porcelain commands to kubectl for service-catalog

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#806]
As implied by #704; making this issue to track the work around this in kubernetes

See:

1.  https://github.com/kubernetes/community/pull/308
2.  https://github.com/kubernetes/kubernetes/pull/30086

Once we have a way of doing this, we will need to figure out where in our code these should live, etc.

**Comment by duglin** [comment]
@simonleung8 since you're working on stuff in this space add any links to your issues/PRs as appropriate.  This might even be a dup.

**Comment by pmorie** [comment]
Oh snap, the proposal merged: https://github.com/kubernetes/community/pull/122

**Comment by pmorie** [comment]
@simonleung8 would you mind commenting with how you see these commands being structured within our repo?

**Comment by simonleung8** [comment]
@pmorie Honestly I haven't thought about where these commands will be placed within our repo, currently I am just developing in a separate repo. The ways kubectl plugin work are either have all the plugin binaries placed in "~/.kube/plugin" or have them in a custom location indicated by the env var `KUBECTL_PLUGINS_PATH`.

We can possibly create a new dir `plugins/` for all the plugin source, with our CI creating the binary as releases. Users then can easily install the plugin with curl, for example 
```
curl {repo}/plugins/install.sh | bash
```
There are many ways for us to approach this, we can discuss and decide what is the easiest for users.

**Comment by simonleung8** [comment]
For anyone who is interested and want to discuss, this is the WIP of kubectl plugins, with commands `create-service-broker`, `create-service`, `bind-service`. 
https://github.com/kubernetes-incubator/service-catalog/pull/840

**Comment by MHBauer** [comment]
@carolynvs @jberkhahn is svcat our solution for this?

**Comment by jberkhahn** [comment]
yes?
