### ISSUE TITLE
Figure out how to support OSB 2.12

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#809]
Currently, the catalog supports the 2.11 version of the OSB API spec.  This issue is to determine how we will support the 2.12 version once it is released.  Some background:

1.  Minor version releases of the spec (ie 2.11 -> 2.12) should be backward compatible (ie, not change the behaviors of existing fields or introduce new mandatory fields)
2.  We already have support for an alpha feature (accepted to the OSB spec, but not released): see (https://github.com/kubernetes-incubator/service-catalog/pull/686)

Initial suggestions for how to handle this (and in general, minor version bumps):

1.  Add new fields to the OSB API client package in our code
2.  Change the hard-coded version string that we send in OSB API call request headers
3.  Rename any related flags that include `alpha` which are not release to no longer include `alpha`

There's are a couple other facets beyond code changes:

1.  How do we message to users about OSB API version bumps?
2.  How do we decide that we feel the catalog is ready to 'support' a particular API version?

We should devote some thought to this, because 2.12 is likely to be released soon.

**Comment by arschles** [comment]
Removing from 0.1.0 - @pmorie will fill in details on the plan here

**Comment by MHBauer** [comment]
The 2.12 issue is resolved by #971, but there seems to be a lot to unpack in here to multiple new issues.

**Comment by MHBauer** [comment]
@pmorie I think should be closed as the client is now provided by a dependency.

We are at 2.12 or 2.13 with 2.14 about to be released. We have feature gates to enable features, and that seems to be a comfortable position.
