### ISSUE TITLE
Add support for re-GETting the catalog from a broker

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#812]
Umbrella issue to track adding support for this. Things to consider:
- manually request from a kube admin to re-get
- periodic re-get
- ability to ask for certain brokers to be excluded from the auto-re-get
- do the re-get and reconcile the data

**Comment by pmorie** [comment]
Dupe of https://github.com/kubernetes-incubator/service-catalog/issues/705; closing
