### ISSUE TITLE
Do we need a BindResource field in BindingSpec?

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#817]
The spec refers to a field in the binding request body called `bind_resource`: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-5

This issue is to determine whether we need to have a user-facing field for this in the `Binding` resource.

**Comment by arschles** [comment]
Related to #818 - do we need to expose additional fields to the k8s data model to represent additional data we need to send to brokers?

**Comment by pmorie** [comment]
I no longer this with is an issue, so I'm going to close it.  Anyone should feel free to reopen it if they believe there is some work to do **and** have a specific use-case formulation for it.
