### ISSUE TITLE
Description for ServiceClass and ServicePlan should be required

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#828]
...and not optional, as they seem to be by virtue of being pointers.  Instead these fields should just be strings.

**Comment by pmorie** [comment]
Services: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-objects
Plans: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#plan-object-

**Comment by MHBauer** [comment]
looks easy enough

**Comment by jwforres** [comment]
@bparees since this affects your broker since template descriptions are optional

**Comment by bparees** [comment]
@pmorie what's the justification for making them mandatory?  seems unnecessarily burdensome.

**Comment by duglin** [comment]
the OSB API spec mandates it

**Comment by bparees** [comment]
you're gonna get a lot of "" descriptions.

**Comment by MHBauer** [comment]
They are described as REQUIRED in the API definition.

Do we need a `lax` flag?

**Comment by pmorie** [comment]
@bparees if they're required, I'm inclined to say that we should reject services/plans that do not have them

**Comment by bparees** [comment]
> @bparees if they're required, I'm inclined to say that we should reject services/plans that do not have them

yes i would assume that's what the service catalog is going to do (arguably is obligated to do).

it's more a question for broker authors as to what they want to do if they don't have sufficient information to provide a useful description of the service/plan (in our case, a template where the template author did not provide a description).  I'm inclined to have us just generate one, like "this is a %name% template."

**Comment by bparees** [comment]
@jim-minter fyi.

**Comment by pmorie** [comment]
@bparees i think that is fine.  We should have guidance for template authors intending to integrate with catalog that lets them know there's an incentive to write a description for their template.

**Comment by vaikas-google** [comment]
@bparees @pmorie Yeah, if there's a broker that wraps templates, then I'd push/force/encourage the template writers to provide meaningful descriptions. Not sure how the user of the catalog is going to just choose these serviced templates just based on the name?

**Comment by bparees** [comment]
> @bparees @pmorie Yeah, if there's a broker that wraps templates, then I'd push/force/encourage the template writers to provide meaningful descriptions. Not sure how the user of the catalog is going to just choose these serviced templates just based on the name?

it's pretty easy to envision people just playing around w/ this stuff who just want to quickly see if they can make a template show up in the service catalog tripping over this.

**Comment by vaikas-google** [comment]
For playing around, then they can still just put the description themselves as 'service'? It hardly seems worth it to add extra machinery and not encourage good habits from the get go because adding a description just seems so trivial to do?

**Comment by MHBauer** [comment]
I do not understand the template conversation. There seem to be two separate uses of the word template.

**Comment by bparees** [comment]
i'm pretty sure all the uses of "template" in this thread refer to openshift templates, which are a way of defining a set of openshift/k8s resources that will be created together.  We're creating a service broker which will let you pick a template and deploy it (meaning create the resources it defines).
