### ISSUE TITLE
Sample brokers

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#833]
Related to: https://github.com/kubernetes-incubator/service-catalog/issues/786

While I agree that we don't want to put a ton of sample brokers in our repo, I do think we should think about where people should put them.  For example, we could choose to do nothing and let people google to find them. We could choose to work with the OSB API wg and come up with a nice place (wiki?) to simply allow people to add links to their samples in one spot so they're easy to find - then we just add a pointer in our docs to that info. Same goes for the CF community since they have this page:  https://docs.cloudfoundry.org/services/examples.html

So, while I suspect the action from this issue will not result in something significant for our repo, I do think we need to discuss it and help take some action someplace because having example brokers will help promote our work, and we want make it as easy as possible for people to create new ones.  Sample go a long way for that.

Might be a good topic for a Monday call when we have a small agenda.

**Comment by gyliu513** [comment]
Also related to https://github.com/kubernetes-incubator/service-catalog/issues/548

Yes, echo @duglin , I cannot agree anymore that we should think where put the example brokers to promote the service catalog project to be adopted by more people.

**Comment by MHBauer** [comment]
OSB should have the list.

Brokers aren't specific to kubernetes, so it needs to be some separate repo/place/org.

**Comment by pmorie** [comment]
+1 on a list of known brokers being hosted at OSB

we should ensure that this list does not imply endorsement.

**Comment by gyliu513** [comment]
@pmorie @MHBauer do you mean here https://github.com/openservicebrokerapi ? If so, who can help create a repo for the sample service brokers?

**Comment by duglin** [comment]
we have a f2f next week, I'll add this as a topic to discuss

**Comment by gyliu513** [comment]
Any suggestions for how to proceed this?

**Comment by duglin** [comment]
See: https://github.com/openservicebrokerapi/servicebroker/pull/252

**Comment by MHBauer** [comment]
@duglin closing since that linked pr has been merged, and it is a page we point to within our repo.
