### ISSUE TITLE
Remove OSB prefixes

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#834]
Based on a chat @pmorie and I had yesterday we should remove the "OSB" prefix on our properties since the chances of us supporting something else along side the current stuff seems pretty slim.

w.r.t. OSBGUID, we both liked `ExternalID`.

However, if based on https://github.com/kubernetes-incubator/service-catalog/issues/802 we use the OSB ID as our name then we may not need a OSBGUID property at all.

**Comment by MHBauer** [comment]
I agree that we should remove OSB. Are we all in agreement?

**Comment by duglin** [comment]
discussed on today's call - we're ok headed in this direction

**Comment by MHBauer** [comment]
#839 is part.

**Comment by pmorie** [comment]
https://github.com/kubernetes-incubator/service-catalog/pull/843
