### ISSUE TITLE
Do we still need test-apiserver.sh to run as part of integration tests?

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#842]
`contrib/hack/test-apiserver.sh` is run as part of our integration tests, and it drives `kubectl` commands to simulate creating resources. Two questions:

- These don't appear to simulate any functionality beyond CRUD actions on an etcd-based API server. What was the original intent for this script?
- Because it drives `kubectl` commands, it looks more like an end-to-end test. Can we move it there?

cc/ @duglin @MHBauer since I think one or both of you wrote this script originally

**Comment by duglin** [comment]
its original intent was to make sure we didn't regress on the apiserver as we made changes.
While it starts etcd, we could easily make it use TPRs - the same kubectl cmds should still work, right?

I'm ok with moving it to an e2e bucket if that's where it should live. I'm also ok with removing it if we have other tests that do the same thing.

**Comment by pmorie** [comment]
Effectively this was the forst version of the clientset test.

i don't think we absolutely need to keep it around, because we do have the
client set test.

**Comment by arschles** [comment]
I will remove the script entirely in a PR to come

**Comment by MHBauer** [comment]
Looking at this and #865 we wanted to keep this as it tests compatibility with kubectl.
