### ISSUE TITLE
UPS sample has secret in the wrong place

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#849]
Right now the UPS example, if I'm following it correctly, has people create broker and instance resources that are basically static. The unique part of things are in the binding because that's where we point to the secret that has the creds. This isn't correct. The secret/creds should be part of the instance so that as multiple apps bind to that instance those creds are injected by copying the secret from the instance data. They shouldn't have to specify the secret on each binding.

In the CF world, the equivalent would be something like:
```
cf create-user-provided-service my-db-mine -p "username, password"
```
where this is creating a new service instance called `my-db-mine`.  People can then bind to this instance w/o having to provide the creds each time.

I see code like this: https://github.com/kubernetes-incubator/service-catalog/blob/master/contrib/pkg/broker/user_provided/controller/controller.go#L83   which either seems to imply that UPS instances can have the creds as part of it or this is just a sample and not meant to be used to actually deploy UPS.

Perhaps the walkthru sample yaml just needs to be updated to add the creds to the instance instead - I'm not sure, the way UPS is layed out (code-wise and in the dir structure) is very confusing to me.

**Comment by duglin** [comment]
Looking at that code some more I think the answer here is to just update the walkthru sample yaml so that we include a "credentials" parameter in the instance yaml.  I'll open a PR for this.

**Comment by arschles** [comment]
#851 should close this
