### ISSUE TITLE
BindingSpec.secretName shouldn't be required to be set by the user

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#850]
While creating a binding I got an error message saying that I had to specify a secretName. I seem to recall that we agreed to default to the bindingName for this to minimize the amount of things users had to specify.

**Comment by pmorie** [comment]
Well, it's a required field, but we can default it.

**Comment by duglin** [comment]
We may actually want to force them to give us a secretName if we split out PodPreSet from the Binding because then we're asking people to do more manual wiring of things than we originally intended - which means implicitly naming things could cause confusion for people.
