### ISSUE TITLE
Store written release notes in the repository

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#870]
We currently do not maintain written release notes in the repository.  We should, and should have a way to track what does and does not warrant a release note.  K8s has a process for this, but my gut feeling is that it would not be portable to our repo without modification.

Setting 0.1.0 on this to at least have written release notes.

**Comment by MHBauer** [comment]
They at least partially have a bot or a script that scrapes the PRs to help with that.

**Comment by arschles** [comment]
@pmorie I believe we can close this now that https://github.com/kubernetes-incubator/service-catalog/pull/871 is in. Do you disagree?

**Comment by pmorie** [comment]
Yeah
