### ISSUE TITLE
Use ObjectReference instead of LocalObjectReference in BindingSpec

### ISSUE THREAD

**Issue by duglin** [kubernetes-incubator/service-catalog#890]
To future proof things, should we use ObjectReference instead of LocalObjectReference in BindingSpec when we point to the Instance?  I suspect we may want to allow for a single instance (in one namespace) to having a binding in another namespace.

We should discuss this before beta.

**Comment by pmorie** [comment]
ObjectReference is fully backward compatible with LocalObjectReference from a field standpoint.

**Comment by duglin** [comment]
can you elaborate? When I look at those two resources in the model they have a very different set of properties.

**Comment by duglin** [comment]
oh, do you mean that because they both have "name" (and LocalObjRef **just** has "name") we can upgrade from LocalObjRef to just ObjRef ?

**Comment by duglin** [comment]
If that's true then how does client tooling work? For example, is there tooling that generate client-side artifacts that match the structs in our types?  Perhaps even use the same names? Or is it assumed that any client-side tooling will only focus on the syntax of things on the wire and therefore going from LocalObjRef to ObjRef will be viewed as just adding new properties to a json object? And are there requirements on these clients to not drop unknown properties? Which is what the ObjRef extras would be to an older client.

**Comment by pmorie** [comment]
@duglin sorry for the delayed the response - I didn't mean to be terse, just made the mistake of answering from my phone on vacation and forgetting to come back to it.

> oh, do you mean that because they both have "name" (and LocalObjRef just has "name") we can upgrade from LocalObjRef to just ObjRef ?

That's correct.

> Or is it assumed that any client-side tooling will only focus on the syntax of things on the wire and therefore going from LocalObjRef to ObjRef will be viewed as just adding new properties to a json object? 

Correct, if in a future version we change to ObjectReference, a client sending only the name field from LocalObjectReference will appear to send an object reference with the namespace unpopulated.  The semantics of an ObjectReference field should be that an unset namespace indicates the enclosing namespace of the resource.  So, the behavior is fully backward compatible, ie, an older client sending only the name field will get the exact same behavior.

Make sense?
