### ISSUE TITLE
Replace RawExtension type with raw byte array?

### ISSUE THREAD

**Issue by nilebox** [kubernetes-incubator/service-catalog#911]
[RawExtension](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/types.go#L92) type is being widely used in ServiceCatalog for representing any arbitrary JSON from the OSB spec: [BindingSpec](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go#L350), [InstanceSpec](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go#L259), [ServiceClass](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go#L156), [ServicePlan](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go#L201).

@pmorie @MHBauer according to the code, you two have added fields of this type to the Service Catalog code.

But by looking at the code and docs of `RawExtension` type, it was not designed for this purpose. It has two fields:
```go
type RawExtension struct {
	// Raw is the underlying serialization of this object.
	//
	// TODO: Determine how to detect ContentType and ContentEncoding of 'Raw' data.
	Raw []byte `protobuf:"bytes,1,opt,name=raw"`
	// Object can hold a representation of this extension - useful for working with versioned
	// structs.
	Object Object `json:"-"`
}
```
And the `Object` field has a type of a following interface:
```go
type Object interface {
	GetObjectKind() schema.ObjectKind
}
```
So it's clearly not meant to be used for _arbitrary_ JSON, but rather for a very specific kind of JSON.

By looking at the Service Catalog code we actually never use the `Object` field and only use `Raw []byte` field for marshalling/unmarshalling. So my suggestion is to get rid of using `RawExtension` type and replace it with raw `[]byte` or more appropriate Kubernetes core type (if there is any). For example:

```go
// InstanceSpec represents the desired state of an Instance.
type InstanceSpec struct {
	...

	// Parameters is a YAML representation of the properties to be
	// passed to the underlying broker.
	Parameters []byte `json:"parameters,omitempty"`
}
```

The other candidate type I looked at was [Unknown](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/types.go#L111), but it doesn't seem to be a good fit either. Do we actually need anything but `[]byte`?

**Comment by pmorie** [comment]
RawExtension is exactly for storing arbitrary json -- we used it after discussion with the API Machinery group.  I have an issue opened to document the rationale for why, which still needs to be completed, but this is exactly what RawExtension is for.

**Comment by vaikas-google** [comment]
Yes the main reason for using the RawExtension is that it validates that the bytes are JSON so you get earlier failures without having to validate it yourself.
