### ISSUE TITLE
Determine 'official' namespace where catalog will run

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#926]
We are currently suggesting 'catalog' as the namespace where catalog components run.  I think we should lock down an 'official' namespace' which is less ambiguous.  I would suggest something like `kube-service-catalog`.

**Comment by duglin** [comment]
Any reason not to run it in kube-system?  Similar to kube-dns

**Comment by MHBauer** [comment]
With aggregated api, why does this matter? Does svc cat need it's completely own namespace to own and run in?

**Comment by carolynvs** [comment]
FWIW, I always run service catalog in kube-system since I consider it part of the cluster plumbing.

**Comment by duglin** [comment]
as it should be  ;-)

**Comment by pmorie** [comment]
I don't think mandating an official namespace should be a goal. We lose a
lot of time in this group when trying to force everyone to accept the same
solution.

On Tue, Apr 3, 2018 at 10:29 AM, Carolyn Van Slyck <notifications@github.com

**Comment by MHBauer** [comment]
SGTM
