### ISSUE TITLE
The order of parameters in parameter schema is not preserved

### ISSUE THREAD

**Issue by luksa** [kubernetes-incubator/service-catalog#937]
Due to unmarshalling and re-marshalling of the schemas returned by the broker, the order of entries under `schemas.service_instance.create.parameters.properties` is not preserved. 

Yes, `properties` is an object and properties of a JSON object have no order, but until the OSB spec introduces an additional field like `form: ["firstProperty", "secondProperty"]` or a different mechanism for specifying how the parameter input fields in a form should be ordered, it makes sense to at least try to preserve the order of the properties in the JSON schema.

**Comment by pmorie** [comment]
I'm not sure why this is a problem - can you clarify?  I would expect parameters to be treated as unordered maps, but I realize now that the proposal to the OSB spec doesn't clarify that.

**Comment by luksa** [comment]
They can be treated as unordered for validation, but not when presenting a parameter input form. I mean, the broker must have a way of specifying the parameter order, so a UI can show a proper-looking form. It's a UX thing. Showing parameters in random (or alphabetical) order makes the input form hard to understand for the user provisioning the service. 

For example, in our messaging-as-a-service broker, the name of the queue is the most important parameter and should be at the top. Below it are the less important parameters. Compare the following two screenshots:

Order of parameters as returned by the broker:
![proper-order](https://user-images.githubusercontent.com/823581/27083708-b3c11fde-5049-11e7-92a0-cfb4ba23d14c.png)

Random order:
![random-order](https://user-images.githubusercontent.com/823581/27083727-c0ded152-5049-11e7-8ae7-c1f76acf51e0.png)

The point I'm trying to make is that currently, the Service Catalog doesn't preserve this order and therefore removes vital information from the broker's response. Obviously, because properties of an object have no order, this should be solved in the OSB spec - by allowing the broker to return an array specifying the order of parameters, for example. But until a feature like that is included in the spec, the Service Catalog could at least make sure it doesn't modify the parameter schema in any way.

**Comment by pmorie** [comment]
cc @jwforres

**Comment by jwforres** [comment]
cc @spadgett

This is a fundamental flaw of using JSON schema.  As mentioned we would never be able to rely on it as is.  By convention browsers iterate over a map in the order the keys were created on the object, but that is not guaranteed.

@luksa have you tried this method? https://stackoverflow.com/questions/31691247/how-can-i-define-the-sequence-of-properties-in-json-schema

**Comment by luksa** [comment]
Tried it now. No fields are displayed. Here's the relevant snippet from the serviceclass:

```
"alphaInstanceCreateParameterSchema": {
  "items": [
    {
      "properties": {
        "name": {
          "description": "Enter the name of this address",
          "minLength": 2,
          "required": true,
          "title": "Address name",
          "type": "string"
        }
      },
      "type": "object"
    },
    {
      "properties": {
        "transactional": {
          "description": "Is this a transactional queue/topic or not",
          "title": "Transactional",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    {
      "properties": {
        "pooled": {
          "description": "Is this a pooled queue or not",
          "title": "Pooled",
          "type": "boolean"
        }
      },
      "type": "object"
    }
  ],
  "type": "array"
}
```

**Comment by duglin** [comment]
Seems to me that this might be something for the OSB API spec to solve otherwise we'd be solving it just for Kube and no one else.  I see two options:
1 - change the spec to make it clear that the json order matters and that platforms MUST assume the order in the json is the order that the broker wanted things to be process/displayed/whatever (assuming CF is ok with this change)
2 - add something to the schema to define the order

I'd prefer the 2nd option if we could since trying to force un-ordered maps to be ordered feels non-kosher to me.

**Comment by luksa** [comment]
I agree the 2nd option is what the ultimate solution should be. My PR (#938) was a temporary solution until the OSB API spec introduces a mechanism to specify the order of parameters.

**Comment by duglin** [comment]
Added a comment in the osbapi group's schema PR:  https://github.com/openservicebrokerapi/servicebroker/pull/165#issuecomment-317402212

**Comment by jberkhahn** [comment]
This has been solved on the OSB end
