### ISSUE TITLE
Rebasing Service Catalog onto API machinery 1.7

### ISSUE THREAD

**Issue by nilebox** [kubernetes-incubator/service-catalog#949]
According to the [roadmap](https://github.com/kubernetes/kubernetes/milestones/), Kubernetes 1.7 is planned to be released on June 28.
As of now, Service Catalog depends on API machinery 1.5.5.

In the meantime, we can discuss the implications of rebasing onto 1.7, see comment https://github.com/kubernetes-incubator/service-catalog/pull/944#issuecomment-308722052, and prepare for the migration starting to rebase onto master branch of API machinery, see PR https://github.com/kubernetes-incubator/service-catalog/pull/944.

We could also define the process of regular rebasing onto the latest release of API machinery, see https://groups.google.com/forum/#!topic/kubernetes-sig-service-catalog/Jo5eseslMaI

**Comment by pmorie** [comment]
I do agree with you that we need to do this on a regular basis.  I will say
from our experience in this repo and my own in other repositories that you
have to be very strategic about when you choose to rebase onto the API
machinery and what version to rebase onto.  If you do it too often, it can
burn an entire person's day-job time.  Given that we have only a handful of
people that actively make code contributions to the repository, we do not
have a lot of time-resources to work with currently.

I will say, I am really happy the 944 is started and to have the pool of
people who know how to perform the rebase growing :-)

One other thing that I have made an observation on in another thread today
is that we need to establish a communication channel between the API
machinery SIG and this SIG.  As an example, when PR 944 was started, the
author could not possibly have known what type of changes would be
waiting.  We need to work together to have some guidance for anyone writing
user API servers about what type of changes to expect.

Thoughts?

P

**Comment by MHBauer** [comment]
Do we want a 1.6 intermediate state or wait for 1.7 final?

**Comment by pmorie** [comment]
I think there are bugs present in the last 1.6 point release that are fixed in 1.7, so I'd prefer to wait until 1.7

**Comment by pmorie** [comment]
Closed by #944
