### ISSUE TITLE
Add more granular conditions to BindingStatus and InstanceStatus

### ISSUE THREAD

**Issue by nilebox** [kubernetes-incubator/service-catalog#951]
Currently all Service Catalog resource types have only `Ready` condition supported:
- [BrokerCondition](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go#L98)
- [InstanceCondition](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go#L328)
- [BindingCondition](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/types.go#L430)

In case of any error we just set the status `Ready: False` and put the error details in the `reason` field.
Example: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_instance.go#L245

Such implementation has a bunch of problems:
- There is no reliable way of distinguishing common errors other than by looking at the `reason` text
- There is no condition for terminal errors, when there is no point of continuing to run retry loop unless the resource spec is updated (and this can be checked through [resourceRevision](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L105))

The proper way of implementing status would be defining at least errors with different outcome/behavior as a separate condition.
For example, see [DeploymentConditions](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L352),  [NodeConditions](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L3034) or [Smith Bundle](https://github.com/atlassian/smith/blob/master/types.go#L18).

**Comment by pmorie** [comment]
We've already discussed this as a group, see #476 for background.

> There is no reliable way of distinguishing common errors other than by looking at the reason text

That is exactly what you should do.  Reason has a machine-readable string, and Message is the human-readable message.

> There is no condition for terminal errors, when there is no point of continuing to run retry loop unless the resource spec is updated

That is something we need; I think this is necessary to solve issue like https://github.com/kubernetes-incubator/service-catalog/issues/953.  I will create specific issues for adding failure conditions for instances and bindings.

If you have a specific suggestions, I'd love to see another issue.  We have had far, far more luck with specific proposed changes than broad 'do it differently' ones.  Closing this one for now.

**Comment by nilebox** [comment]
For the record: this issue is substituted with https://github.com/kubernetes-incubator/service-catalog/issues/967 and https://github.com/kubernetes-incubator/service-catalog/issues/968
