### ISSUE TITLE
CI API Registration Aggregration

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#952]
Either by waiting for 1.7 to be ready and in GCE, figuring out another way to run 1.7, or figuring out how to run the aggregator as a separate pod in 1.6 in gce.

**Comment by luxas** [comment]
I think using v1.7 only and ditching v1.6 with kube-aggregator standalone mode makes sense, then we can focus on the essential parts instead of fiddling with setting up things...

kubeadm v1.7 also works with AA out of the box

**Comment by luxas** [comment]
We maybe would be able to use https://github.com/mirantis/kubeadm-dind-cluster

**Comment by kibbles-n-bytes** [comment]
CI has been put behind the aggregator, so I believe we can close this.
