### ISSUE TITLE
Add tests to ensure that AuthInfo is set on a Broker resource

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#958]
https://github.com/kubernetes-incubator/service-catalog/pull/956 is a fix to require that `authInfo` is set on a new broker spec. This issue is a follow-up to add a test for that behavior

**Comment by duglin** [comment]
See https://github.com/openservicebrokerapi/servicebroker/pull/223 - may not be needed

**Comment by arschles** [comment]
As #956 was closed w/o merge, I am closing this.
