### ISSUE TITLE
What type is service metadata?

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#959]
Discovered during #954; the old client in `pkg/brokerapi` treats this field as an `interface{}` while we treat other fields that have the same type in the spec as `map[string]interface{}`.  I treated this field as `map[string]interface{}` Based on the conventions for metadata, it seems like this field is really a dictionary (see https://github.com/openservicebrokerapi/servicebroker/pull/235).

**Comment by duglin** [comment]
@pmorie can we close this?

**Comment by pmorie** [comment]
Yes, closing.
