### ISSUE TITLE
Add a failure condition for Instance

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#967]
Needed to represent a failure returned by the broker (which is terminal); benefits:

- Allows controller to continually retrying provision operations that have failed
- Communicates to user that the resource is in a failed state in a more meaningful way than is done currently

@jwforres has mentioned the need for this (I will create a separate issue for bindings, which have the same concern)

**Comment by jwforres** [comment]
cc @spadgett

**Comment by pmorie** [comment]
Decision plane for needing a new condition type: if we cannot fit the necessary permutations of an instance's status into a single ready condition.  An example of this is when there is a terminal failure that still requires cleanup work.  According to the [orphan section of the spec](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphans), there are scenarios where this can happen.

For example, if the controller is on the last retry of a provision and gets a 500 error, the instance is terminal, but still needs to have orphan cleanup done.  The orphan cleanup may itself fail and need to be retried.  We need a distinct condition to represent that the instance has already terminally failed so that the ready condition can hold information about the orphan mitigation.

The less condition types we have the better, so I would suggest that we introduce a condition type for terminal instance failure and keep it at that for now.  I'm prototyping this now -- we'll see if we wind up needing more (like an orphan mitigation condition).

**Comment by pmorie** [comment]
Closed by #1017
