### ISSUE TITLE
Add a failure condition for Binding

### ISSUE THREAD

**Issue by pmorie** [kubernetes-incubator/service-catalog#968]
Similar to #967, we need a failure condition for Binding to represent a permanent failure that shouldn't be retried.

**Comment by maleck13** [comment]
@pmorie In what circumstances would we consider it failed and use the failure condition? Would that be if the broker returned an unexpected status code as in not 200 or 201? Or would it be the case that we would want to continue to retry in a situation where there was a 500 code as perhaps the broker is offline but may recover, but not retry in the case of the specific 409 or 422 status code as documented by the spec https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-4

Would I be correct in thinking, we would want the bindingQueue to forget the binding if the binding was in a failure condition?

**Comment by pmorie** [comment]
PR: #1057

**Comment by pmorie** [comment]
Actually, this is a dupe of #1051 - going to close the newer issue documents consensus from a design meeting.
