### ISSUE TITLE
Add test to ensure that asynchronously provisioning (and deprovisioning) instances eventually succeed

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#985]
We do not have tests that do the following:

- call `reconcileInstance` for an `Instance` that will be asynchronously provisioned or deprovisioned
- Check to ensure the instance is marked as doing the asynchronous operation
- Re-configure the test broker's last operation endpoint to indicate the async operation is finished
- Ensure that the instance operation is marked done, and not asynchronous

**Comment by pmorie** [comment]
This is actually covered by #1074; closing.
