### ISSUE TITLE
TPRs and Custom Resource Definitions (CRDs)

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#987]
CustomResourceDefinitions (CRDs) will eventually replace Third Party Resources (TPRs). This issue is for tracking that transition and the work we need to do to follow it.

Related issues:

- https://github.com/kubernetes/features/issues/95

**Comment by kibbles-n-bytes** [comment]
Blog post about the change: https://coreos.com/blog/custom-resource-kubernetes-v17

**Comment by MHBauer** [comment]
https://github.com/kubernetes/kubernetes/issues/48152 plan to remove in 1.8

**Comment by mengqiy** [comment]
Anyone working on this already? If not I will pick it up.

**Comment by nilebox** [comment]
> kubernetes/kubernetes#48152 plan to remove in 1.8

So we have ~2-3 months to migrate to CRDs (or drop TPR support completely).
We also should consider what to do for kube 1.6 (as @arschles was working on keeping Service Catalog instructions for 1.6), where CRDs are not available.

**Comment by ash2k** [comment]
@mengqiy I think migration to CRDs is blocked by https://github.com/kubernetes-incubator/service-catalog/pull/944 because client is obviously is not available in old client-go.

**Comment by MHBauer** [comment]
It's the dynamic client, we don't require support from client go.

If it's so different, I would think we fork TPR and have support for etcd, tpr, and crd at the same time.

**Comment by nilebox** [comment]
@MHBauer I don't see the benefit of continuing the support of TPR once 1.8 is out. It will die very soon anyway, and Service Catalog is not even beta yet, why bother.

**Comment by pmorie** [comment]
I think we should ditch TPR for CRD as soon as possible, and not support
TPR at all.

**Comment by nilebox** [comment]
I can take this task after https://github.com/kubernetes-incubator/service-catalog/pull/944, and I would prefer using a typed CRD client for this instead of dynamic one.

**Comment by MHBauer** [comment]
I'm fine with that. I wanted to make the argument for backwards compatibility.

**Comment by mengqiy** [comment]
@nilebox Can you itemize the tasks required for the transition from TPR to CRD.

**Comment by nilebox** [comment]
it's probably easier for @arschles to do, as he has added support for TPRs in Service Catalog.

**Comment by mengqiy** [comment]
Yes, the initial support for TPR seems to be in PR https://github.com/kubernetes-incubator/service-catalog/pull/338.

**Comment by arschles** [comment]
Here is some background on why we wanted a TPR storage backend in the first place. We (Deis) had some customers, and anticipated more, that did not want to connect the service-catalog software to the etcd servers they used with the core API server, and we didn't believe it to be acceptable to ask users to install etcd (i.e. the operator) on their cluster just to use service-catalog (we had experience doing this ourselves in the past, we had some problems, and we didn't want to support customers having the same problems).

So, we looked for a different solution with as few setup and maintenance requirements as possible. TPRs were available and had major issues when we started, but we managed to work around almost all of them and release service-catalog that used them successfully. Now, there are actually two reasons we need to re-evaluate:

1. They are being deprecated (what this issue is about)
1. Setting up RBAC rules to support the TPR backend requires additional work

(1) is, of course, enough to trigger this discussion, but (2) points to a larger problem: MSFT seems to be the only stakeholder in this group that wants a CRD/TPR based implementation. While we don't _need_ to have CRD be a storage backend, I still believe that we should have an alternative to etcd.

I have scheduled us to talk about this in our design meeting on 7/24/2017.

**Comment by ash2k** [comment]
@arschles I think we also want CRD-based storage backed. It should be much easier to maintain vs an etcd.

p.s. I understand that CRDs are not meant to be used that way, but it is hopefully acceptable while there is no alternative.

**Comment by mengqiy** [comment]
@arschles @ash2k We (Google) are also interested in a CRD-based storage. If you guys are not working on that, I can pick it up.

**Comment by arschles** [comment]
@mengqiy we are going to talk about this on today's design meeting. I will update here

**Comment by arschles** [comment]
Here is what I proposed in the design meeting:

- Implement CRD support next to TPRs
- Document the fact that TPR is perpetually in alpha and won't be supported at all after we rebase on 1.8's API machinery
- After we rebase on 1.8, 

@nilebox @ash2k I will meet with you today. @mengqiy please ping me on the slack channel (`arschles`) so we can talk about this implementation.

**Comment by arschles** [comment]
After talking with @nilebox and @mengqiy about the work involved with migrating in this fashion to a CRD storage backend, we have settled on the following work items:

- #1087
- #1088
- #1089

**Comment by MHBauer** [comment]
With the above work items, do we still need this issue?

**Comment by MHBauer** [comment]
TPR is out, so no transition to do, wholly replaced by #1088, #1087 can be a subtask of #1088

**Comment by mszostok** [comment]
done by: https://github.com/kubernetes-sigs/service-catalog/issues/2633

**Comment by MHBauer** [comment]
comment probably better placed on #1088 & #1087

**Comment by mszostok** [comment]
linked with mentioned isssues :)
